### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension must be 6 but is 4 for 'Encoder-1-MultiHeadSelfAttention/transpose_9' (op: 'Transpose') with input shapes: [?,12,?,?,12,64], [4].

### ISSUE THREAD

**Issue by ningshixian** [bojone/bert4keras#1]

**Comment by ningshixian** [comment]
python 3.8

**Comment by bojone** [comment]
经测试是Keras 2.2.5版本的问题，已经做了更新，兼容Keras 2.2.5了，请再测试一下

**Comment by ningshixian** [comment]
> 经测试是Keras 2.2.5版本的问题，已经做了更新，兼容Keras 2.2.5了，请再测试一下

非常感谢，成功跑通了！
可以愉快的使用了

**Comment by lonngxiang** [comment]
麻烦也问下，这种情况是什么原因呢
![image](https://user-images.githubusercontent.com/40717349/109592813-dbc74c80-7b4a-11eb-9676-2f90b54deef7.png)

tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[9,24] = 13613 is not in [0, 13584)
         [[{{node Embedding-Token/embedding_lookup}}]]
