### ISSUE TITLE
请问 `keep_words` 的作用是什么呢？

### ISSUE THREAD

**Issue by echo-ray** [bojone/bert4keras#10]
在 `task_sentiment_albert.py` 的 `vocab.txt` 中，已经有了 `[PAD], [UNK], [CLS], [SEP], [unused1], [unused2]` 等标记，为什么还要在 [`task_sentiment_albert.py`的地42～52行](https://github.com/bojone/bert4keras/blob/master/examples/task_sentiment_albert.py#L42-L52) 手动添加呢？
然后在此处引入的`keep_words` 是起什么作用呢？
（keras_bert 似乎没有这个参数）

**Comment by bojone** [comment]
请仔细阅读
https://kexue.fm/archives/6933#%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E

**Comment by echo-ray** [comment]
天呐。。。太速度了，非常感谢您给的链接！

**Comment by echo-ray** [comment]
引用一下大佬博客里相关的部分
> 另外还有一个 keep_words，这个是用来精简 Embedding 层用的，对于中文Bert来说，总的tokens大概有2万个，这意味着最后预测生成的token时是一个2万分类问题。但事实上这大多数tokens都不会被使用到，因此这2万分类浪费了不少计算量。于是这里提供了一个选项，我们可以自行统计一个字表，然后传入对应的id，只保留这部分token，这样就可以降低计算量了（精简后一般只有5000个左右）。
