### ISSUE TITLE
tf2加载ner模型报错Unknown loss function:sparse_loss

### ISSUE THREAD

**Issue by fushengwuyu** [bojone/bert4keras#101]
keras: 2.3.1
python: 3.6.5
tensorflow: 2.0.1
bert4keras:  0.6.5

测试crf模型的加载，代码如下：

import os
os.environ['TF_KERAS'] = '1'
from bert4keras.layers import *
from bert4keras.models import build_transformer_model
from bert4keras.layers import ConditionalRandomField
from bert4keras.optimizers import Adam
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model, load_model

crf_lr_multiplier = 1000
config_path = '/home/sunshine/pre_models/albert_small_zh_google/albert_config_small_google.json'
checkpoint_path = '/home/sunshine/pre_models/albert_small_zh_google/albert_model.ckpt'
bert = build_transformer_model(
    config_path,
    checkpoint_path,
    model='albert'
)

output = Dense(5)(bert.output)
CRF = ConditionalRandomField(lr_multiplier=crf_lr_multiplier)
output = CRF(output)

model = Model(bert.input, output)

model.compile(loss=CRF.sparse_loss,
              optimizer=Adam(1e-4),
              metrics=[CRF.sparse_accuracy])
model.save('11')
custom_objects = {"CRF": CRF,
                  "sparse_loss": CRF.sparse_loss,
                  "sparse_accuracy": CRF.sparse_accuracy}

model1 = load_model('11', custom_objects=custom_objects)
model1.summary()

运行报错如下：
Traceback (most recent call last):
  File "/home/sunshine/Python/tensorlfow2.0_examples/t.py", line 37, in <module>
    model1 = load_model('11', custom_objects=custom_objects)
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 93, in load
    model._training_config))  # pylint: disable=protected-access
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 336, in compile
    self.loss, self.output_names)
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1351, in prepare_loss_functions
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1351, in <listcomp>
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1087, in get_loss_function
    loss_fn = losses.get(loss)
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py", line 1183, in get
    return deserialize(identifier)
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py", line 1174, in deserialize
    printable_module_name='loss function')
  File "/home/sunshine/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 210, in deserialize_keras_object
    raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
ValueError: Unknown loss function:sparse_loss

加载模型的时候，无论加不加custom_objects参数，都报同样的错误。
麻烦苏神帮忙看一下这个问题，感谢。

**Comment by bojone** [comment]
试了试，得到两个解决方案：

1、保存为h5格式，即`model.save('11.h5')`这样，那么加载就没有问题了；

2、通过`tf.keras.utils.get_custom_objects().update(custom_objects)`传入custom_objects。

但是第二种方案虽然`load_model`没报错，但`model.summary()`这一步报错（tf 2.0），网上搜了搜，发现有相关资料：https://github.com/tensorflow/tensorflow/issues/33454 ，不知道更新版tf修复没有。

**Comment by fushengwuyu** [comment]
感谢苏神的解答。我是想要tensorflow serving部署pb模型，所以才采用tf2。
我试了试你提供的两个方案。第一个方案没啥问题。
第二个方案，报错：
AttributeError: 'ConditionalRandomField' object has no attribute 'trans'

代码如下：
custom_objects = {"CRF": CRF,
                  "sparse_loss": CRF.sparse_loss,
                  "sparse_accuracy": CRF.sparse_accuracy}
tf.keras.utils.get_custom_objects().update(custom_objects)
model1 = load_model('11', custom_objects=custom_objects)
model1.summary()

这是怎么回事呢。

**Comment by fushengwuyu** [comment]
貌似是tf2的一个规范问题，自定义layer，需要在build函数中设置built或者super.build()，不然就需要手动执行crf.build()或者fit。
刚刚在实例化CRF之后，CRF.build()就能解决这个问题了、

CRF = ConditionalRandomField(lr_multiplier=crf_lr_multiplier)
CRF.build(input_shape=[5])
custom_objects = {"CRF": CRF,
"sparse_loss": CRF.sparse_loss,
"sparse_accuracy": CRF.sparse_accuracy}
tf.keras.utils.get_custom_objects().update(custom_objects)
model1 = load_model('11', custom_objects=custom_objects)
model1.summary()

**Comment by bojone** [comment]
> 貌似是tf2的一个规范问题，自定义layer，需要在build函数中设置built或者super.build()，不然就需要手动执行crf.build()或者fit。
> 刚刚在实例化CRF之后，CRF.build()就能解决这个问题了、
> 
> CRF = ConditionalRandomField(lr_multiplier=crf_lr_multiplier)
> CRF.build(input_shape=[5])
> custom_objects = {"CRF": CRF,
> "sparse_loss": CRF.sparse_loss,
> "sparse_accuracy": CRF.sparse_accuracy}
> tf.keras.utils.get_custom_objects().update(custom_objects)
> model1 = load_model('11', custom_objects=custom_objects)
> model1.summary()

对对对，是我的锅，忘记`super`了，感谢测试并反馈，现在添加了这一句了，麻烦你再测测。（其实我当时也郁闷了，为啥就这个层有问题，其他自定义层都没问题...）

**Comment by fushengwuyu** [comment]
好的，对了，顺便说一句，那个 tensorflow/tensorflow#33454中model.summary()的bug，在tf2.1.0已经修复了，不过tf2.1.0又有另外一个小bug，前几天刚遇到。
感觉tf2的小bug还是有点多，有点烦人

**Comment by excelsimon** [comment]
> 感谢苏神的解答。我是想要tensorflow serving部署pb模型，所以才采用tf2。
> 我试了试你提供的两个方案。第一个方案没啥问题。
> 第二个方案，报错：
> AttributeError: 'ConditionalRandomField' object has no attribute 'trans'
> 
> 代码如下：
> custom_objects = {"CRF": CRF,
> "sparse_loss": CRF.sparse_loss,
> "sparse_accuracy": CRF.sparse_accuracy}
> tf.keras.utils.get_custom_objects().update(custom_objects)
> model1 = load_model('11', custom_objects=custom_objects)
> model1.summary()
> 
> 这是怎么回事呢。

您好，我用tf1.14训练了ner_crf模型，用tf2.1存成了pb形式，tf serving也正常启动了，但怎么也请求不到，跟您请教交流一下，我的邮箱j-jingz@microsoft.com，看到望联系
