### ISSUE TITLE
example中的albert 分类代码错误

### ISSUE THREAD

**Issue by natureLanguageQing** [bojone/bert4keras#104]
`optimizer=AdamLR(learning_rate=1e-4, lr_schedule={
        1000: 1,
        2000: 0.1
    }),`    
应该改成
`    optimizer=AdamLR(lr=1e-4, lr_schedule={
        1000: 1,
        2000: 0.1
    }),`

**Comment by bojone** [comment]
没错误，你可以去看一下keras官方github的代码
