### ISSUE TITLE
example question @autotitle

### ISSUE THREAD

**Issue by lidongxing** [bojone/bert4keras#105]
在valid部分，
line109：autotitle = AutoTitle(start_id=None, end_id=tokenizer._token_end_id, maxlen=32)
上述代码tokenizer没有_token_end_id属性，但能成功运行；why??
另外，exposure_bias,end_id=tokenizer._token_sep_id改为end_id=tokenizer._token_end_id才能运行。

tks

**Comment by bojone** [comment]
1. 何来断言tokenizer没有_token_end_id属性？

2. exposure_bias项目中我已经声明了当时的bert4keras版本
