### ISSUE TITLE
pretrain albert加载模型错误

### ISSUE THREAD

**Issue by xuxingya** [bojone/bert4keras#108]
环境：
ubuntu 1.8.04
tensorflow 1.14
使用pretraining在新语料上重新训练albert base模型成功，但是在task_sequence_labeling_ner_crf.py中加载模型遇到错误：
`model = build_transformer_model(config_path, checkpoint_path, model='albert')`
报错信息：NotFoundError: Key bert/embeddings/word_embeddings not found in checkpoint
错误详细信息：
![image](https://user-images.githubusercontent.com/13343428/78209234-07742980-74d9-11ea-9af5-4c2a107deef1.png)

**Comment by bojone** [comment]
用`load_weights`方法重新加载预训练好的模型，然后用`save_weights_as_checkpoint`导出原始格式的权重。

**Comment by xuxingya** [comment]
> 用`load_weights`方法重新加载预训练好的模型，然后用`save_weights_as_checkpoint`导出原始格式的权重。

我用如下方法保存还是遇到了错误：KeyError: 'Pooler-Dense'：
```
    if model == 'roberta':
        bert, train_model, loss = build_transformer_model_with_mlm()
    train_model.load_weights(model_saved_path)
        bert.save_weights_as_checkpoint('/home/xingya/resume_parser/training/albert_ckpt')
```
![image](https://user-images.githubusercontent.com/13343428/78217906-81171200-74ef-11ea-9bd1-8485a39ebd3e.png)
应该是mapping的时候出了错, 使用的是默认的roberta模型。

**Comment by bojone** [comment]
是我的疏忽，我更新一下，你待会同步一下github最新的代码

**Comment by xuxingya** [comment]
> 是我的疏忽，我更新一下，你待会同步一下github最新的代码

非常感谢！

**Comment by luckper** [comment]
> 环境：
> ubuntu 1.8.04
> tensorflow 1.14
> 使用pretraining在新语料上重新训练albert base模型成功，但是在task_sequence_labeling_ner_crf.py中加载模型遇到错误：
> `model = build_transformer_model(config_path, checkpoint_path, model='albert')`
> 报错信息：NotFoundError: Key bert/embeddings/word_embeddings not found in checkpoint
> 错误详细信息：
> ![image](https://user-images.githubusercontent.com/13343428/78209234-07742980-74d9-11ea-9af5-4c2a107deef1.png)

你好，我想问下，预训练的albert模型有多大呀？我checkpoint_path设为google版albert的ckpt，然后预训练报错，tensorflow.python.framework.errors_impl.NotFoundError: Key bert/encoder/layer_0/attention/self/query/kernel not found in checkpoint，请问你有遇到吗？

**Comment by luckper** [comment]
你好，我想问下，预训练的albert模型有多大呀？我checkpoint_path设为google版albert的ckpt，然后预训练报错，tensorflow.python.framework.errors_impl.NotFoundError: Key bert/encoder/layer_0/attention/self/query/kernel not found in checkpoint，请问你有遇到吗？

**Comment by bojone** [comment]
> 你好，我想问下，预训练的albert模型有多大呀？我checkpoint_path设为google版albert的ckpt，然后预训练报错，tensorflow.python.framework.errors_impl.NotFoundError: Key bert/encoder/layer_0/attention/self/query/kernel not found in checkpoint，请问你有遇到吗？

`model='albert'`传入了吗 ...
