### ISSUE TITLE
task_sentiment_albert.py保存模型的问题

### ISSUE THREAD

**Issue by mathxin** [bojone/bert4keras#11]
只存权重的方式试过没有问题，也可以顺利转成pb，都ok。
但还是好奇请问一下，我用model.save存储模型了之后，用load_model，添加了custom_objects，也在layer中添加了get_config，之后，还报shape不一致的问题。请问全模型save的方式是不是行不通？跟input shape为None是否有关系

**Comment by bojone** [comment]
很抱歉，我不懂model.save相关技巧，所以无法给出建议～

**Comment by bojone** [comment]
最新版本已经支持了，欢迎测试。
