### ISSUE TITLE
请问模型预训练好的模型参数和数据在哪里下载？

### ISSUE THREAD

**Issue by fuliufuliu** [bojone/bert4keras#111]
![image](https://user-images.githubusercontent.com/10778586/78629347-551dd700-78c9-11ea-9e79-1ea3423545f5.png)

**Comment by fuliufuliu** [comment]
config_path = '/root/kg/bert/chinese_wwm_L-12_H-768_A-12/bert_config.json'
checkpoint_path = '/root/kg/bert/chinese_wwm_L-12_H-768_A-12/bert_model.ckpt'
dict_path = '/root/kg/bert/chinese_wwm_L-12_H-768_A-12/vocab.txt'

如代码中用到的chinese_wwm_L-12_H-768_A-12到哪里下载？

**Comment by yaleimeng** [comment]
readme 里面有很多不同模型的下载链接啊。
权重——目前支持加载的权重：
Google原版bert: https://github.com/google-research/bert
brightmart版roberta: https://github.com/brightmart/roberta_zh
哈工大版roberta: https://github.com/ymcui/Chinese-BERT-wwm
等等………………

**Comment by fuliufuliu** [comment]
3Q
