### ISSUE TITLE
啥时候支持tf2.0呀

### ISSUE THREAD

**Issue by xuyingjie521** [bojone/bert4keras#112]

**Comment by bojone** [comment]
目前加载模型是支持tf2.0的，部分example在tf 2下也能跑，不过确实有部分example还不能跑

**Comment by wulikai1993** [comment]
> 目前加载模型是支持tf2.0的

这是指什么意思？我想加载模型成 TF2.x 的keras 模型，然后使用 save() 方法保存 savedmodel 模型。请问应该怎么做？是不是直接在 TF2.x 的环境下使用 build_transformer_model() 就行了？

**Comment by bojone** [comment]
> > 目前加载模型是支持tf2.0的
> 
> 这是指什么意思？我想加载模型成 TF2.x 的keras 模型，然后使用 save() 方法保存 savedmodel 模型。请问应该怎么做？是不是直接在 TF2.x 的环境下使用 build_transformer_model() 就行了？

就是字面意思，bert4keras大部分功能支持tf2。至于你的需求，请认真读readme.md，readme已经明确说明支持tf2，支持tf.keras，以及对应的启用方式，并且已经有不少用户成功达到了你的目的。

**Comment by wulikai1993** [comment]
谢谢，已找到。设置环境变量 `TF_KERAS=1` 。
