### ISSUE TITLE
task_seq2seq_autotitle_csl运行报错

### ISSUE THREAD

**Issue by kevinwei1975** [bojone/bert4keras#113]
task_seq2seq_autotitle_csl运行第94行model.add_loss(cross_entropy)此处时报错
tensorflow.python.framework.errors_impl.InvalidArgumentError:  You must feed a value for placeholder tensor 'Input-Segment_7' with dtype float and shape [?,?]
         [[node Input-Segment_7 (defined at d:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_keras_scratch_graph_16203]

Function call stack:
keras_scratch_graph
环境是TF2.0

**Comment by bojone** [comment]
2.0的`add_loss`函数确实有问题，这两天修正～

**Comment by kevinwei1975** [comment]
基本上有使用add_loss的应用在2.0及2.1下都运行失败。

**Comment by kevinwei1975** [comment]
我在TF1.14版本及KERAS2.3.1下运行依旧是报错，请问BOJONE这个应用是在一个什么环境下运行通过的?

**Comment by bojone** [comment]
现在依然有错吗
