### ISSUE TITLE
task_relation_extraction.py不收敛?

### ISSUE THREAD

**Issue by songruifei** [bojone/bert4keras#115]
你好，我用您的代码，在kaggle跑了一遍，不收敛?请问可能是什么错呢？
环境:python3.6,  tf2.1,   keras2.3.1
[INFO] 2020-04-08 06:51:46,580 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 07:09:52,487 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 07:28:02,167 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 07:46:09,981 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 08:04:11,032 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 08:22:20,727 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 08:40:24,054 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 08:58:28,040 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 09:16:45,791 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 09:35:05,893 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 09:53:21,590 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 10:11:39,478 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 10:29:55,907 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 10:48:09,872 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 11:06:20,937 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 11:24:38,170 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 11:42:57,489 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 12:01:13,390 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 12:19:28,173 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 12:37:43,737 [<ipython-input-1-9e69b8176f76>:  338]:	f1: 0.00000, precision: 1.00000, recall: 0.00000, best f1: 0.00000

[INFO] 2020-04-08 12:37:43,743 [<ipython-input-1-9e69b8176f76>:  352]:	{'loss': [4.790001192829101, 4.790159363931562, 4.789937287901153, 4.79029213091552, 4.790219674018656, 4.789931528262627, 4.790020725996665, 4.789924693208287, 4.790140324836965, 4.790008762850034, 4.790119758407909, 4.790211486946426, 4.7901170136336955, 4.790065702346339, 4.78999377036619, 4.790070386345926, 4.790002205540951, 4.7899756184185005, 4.7900054474512945, 4.790188280229561]}

**Comment by bojone** [comment]
不推荐使用tf 2.x，推荐使用tf 1.14/1.15

**Comment by Jim0530** [comment]
我也遇到相同問題 請問為什麼會有這樣的結果？？‘

**Comment by bojone** [comment]
https://kexue.fm/archives/7161#comment-13317
可以参考这里

**Comment by TPF2017** [comment]
已解决，ema 会降低学习率，导致小数据集很难收敛

**Comment by bojone** [comment]
> 已解决，ema 会降低学习率，导致小数据集很难收敛

不是ema小数据集难收敛，是ema需要足够多的步数才收敛。比如你20w数据，跑了一个epoch刚收敛，那么1w数据就至少需要跑20个epoch。

**Comment by TPF2017** [comment]
> > 已解决，ema 会降低学习率，导致小数据集很难收敛
> 
> 不是ema小数据集难收敛，是ema需要足够多的步数才收敛。比如你20w数据，跑了一个epoch刚收敛，那么1w数据就至少需要跑20个epoch。

确实，ema 需要更多的步数，训练会更稳定一点，感谢回复！

**Comment by RingoTC** [comment]
我也遇到同样的问题。我是直接在百度的数据集上训练，用的Adam。
后来发现，无论训练多少个epoch都无法收敛。
后面是通过，替换Tensorflow为1.14、把Adam换回EMA Adam解决。

**Comment by doudouaili** [comment]
请问怎么去掉EMA缓存Adam呢？我也是遇到训练时间好几十个小时。。
