### ISSUE TITLE
simbert相关问题

### ISSUE THREAD

**Issue by binzhouchn** [bojone/bert4keras#117]
os.environ['TF_KERAS'] = '1'
我跑simbert代码的时候想用tf.keras发现没有报错但也没出来结果
我是py36,tf1.14.0,keras2.3.1环境

**Comment by bojone** [comment]
没print？

**Comment by binzhouchn** [comment]
print的，就是跑的时候会出现Call initializer instance with the dtype argument instead of passing it to the constructor这个警告然后就结束了

**Comment by bojone** [comment]
没意识到是什么问题。。。
