### ISSUE TITLE
gpt2-ml finetune

### ISSUE THREAD

**Issue by wind91725** [bojone/bert4keras#120]
请问有没有gpt2-ml finetune的教程呀

**Comment by bojone** [comment]
没有，主要是finetune不起来。如果你想做特定数据集的语言模型，可以参考
https://github.com/bojone/bert4keras/blob/master/examples/task_language_model.py

**Comment by wind91725** [comment]
好的 我看代码里 pretraining里有支持 gpt的训练 这个gpt指的是gpt2-ml吧

**Comment by bojone** [comment]
不是，这个gpt指的是单向语言模型

**Comment by wind91725** [comment]
好的 谢谢您的回复
