### ISSUE TITLE
关于examples中EMA使用过程中的传参问题

### ISSUE THREAD

**Issue by ws1993109** [bojone/bert4keras#122]
苏神，我在查看0.7.2版本的bert4keras中的examples中的时候，发现新的EMA使用方法好像有点问题。
示例代码及报错：
![image](https://user-images.githubusercontent.com/29445038/79298084-a1dd5f80-7f12-11ea-8ab4-6840bb8e1dfc.png)
修改学习率传参名称后正常运行：
![image](https://user-images.githubusercontent.com/29445038/79298117-bfaac480-7f12-11ea-9e1c-c291acfdba8a.png)

**Comment by bojone** [comment]
没什么问题。因为你用旧版本keras，我用2.3.1而已，你用旧版本自己改成lr就好，新版是learning_rate

**Comment by ws1993109** [comment]
好的，谢谢。
