### ISSUE TITLE
zhuiyi自研Roberta模型 (tiny和small) 读取特征报错

### ISSUE THREAD

**Issue by mrbayes** [bojone/bert4keras#123]
在basic_extract_features.py中，如果加上with_pool=True参数， 
那么加载zhuiyi自研的Roberta模型 (tiny和small一共4个)时，报错如下：
“Key bert/pooler/dense/kernel not found in checkpoint”
是因为checkpoint确实没有pooler-dense，还是因为mapping时映射错误呢？

**Comment by bojone** [comment]
确实没有pooler，因为roberta没有nsp任务，所以就没保留pooler了

**Comment by mrbayes** [comment]
了解，那就和electra一样，输出加个Lambda层好了

**Comment by bojone** [comment]
> 了解，那就和electra一样，输出加个Lambda层好了

对的
