### ISSUE TITLE
pairwise训练句对关系预测模型的错误

### ISSUE THREAD

**Issue by KunWangR** [bojone/bert4keras#124]
想尝试通过pairwise的方式训练句对关系预测模型，思路是用bert提取句特征向量，然后通过余弦相似度排序。
打印的模型结构如下图所示
![image](https://user-images.githubusercontent.com/17895382/79566886-db19f900-80e5-11ea-8bc6-ed4cea0ddaea.png)
遇到的问题如下：
![image](https://user-images.githubusercontent.com/17895382/79567013-0a306a80-80e6-11ea-8927-d133dcb333b3.png)

分析原因可能是将bert模型作为三个句子(q, a+, a-)的句编码器，造成的模型嵌套，在优化的时候出错。但因为不知道怎么修改，求助下各位。

代码如下，请作者帮忙看下。
`    q_tokens_input = Input(shape=[None, ], name="q_tokens_input")
    q_segments_input = Input(shape=[None, ], name="q_segments_input")

    pos_tokens_input = Input(shape=[None, ], name="pos_tokens_input")
    pos_segments_input = Input(shape=[None, ], name="pos_segments_input")

    neg_tokens_input = Input(shape=[None, ], name="neg_tokens_input")
    neg_segments_input = Input(shape=[None, ], name="neg_segments_input")

    q_pooled_vec = bert_model.model([q_tokens_input, q_segments_input])
    pos_pooled_vec = bert_model.model([pos_tokens_input, pos_segments_input])
    neg_pooled_vec = bert_model.model([neg_tokens_input, neg_segments_input])

    model = Model(inputs=[q_tokens_input, q_segments_input, pos_tokens_input, pos_segments_input,
                          neg_tokens_input, neg_segments_input], outputs=[q_pooled_vec, pos_pooled_vec, neg_pooled_vec])

    model.add_loss(margin_loss(model.outputs))
    model.compile(optimizer=Adam(5e-5), loss=None)
    model.add_metric(partial_accuracy(model.outputs), "partial_acc")  ###
    model.summary()`

**Comment by bojone** [comment]
这是keras的使用问题，跟bert4keras没有实质联系，请参考：https://kexue.fm/archives/4493

**Comment by KunWangR** [comment]
找到原因了，错误在这个地方。在调用bert模型作为encoder的时候，需要使用bert_model的call函数，否则，就会生成一个新的模型model_1，优化器在优化model_1参数的时候就会出错。
`q_pooled_vec = bert_model.model([q_tokens_input, q_segments_input])`
改为
`q_pooled_vec = bert_model.call([q_tokens_input, q_segments_input])`

**Comment by YoungXu06** [comment]
你好，我的代码报这个错误`ValueError: Tensor("a_tokens_input:0", shape=(None, None), dtype=int32) must be from the same graph as Tensor("Embedding-Token/embeddings/Read/ReadVariableOp:0", shape=(21128, 768), dtype=float32).`
是什么原因呢？
`
def build_model(bert_model, LR=1e-5, DR=0.2, a_max_len=200, b_max_len=500):

    input_a_ids = Input(shape=[None,], dtype='int32', name='a_tokens_input')
    segment_a_ids = Input(shape=[None,], dtype='int32', name='a_segments_input')
    
    input_b_ids = Input(shape=[None,], dtype='int32', name='b_tokens_input')
    segment_b_ids = Input(shape=[None,], dtype='int32', name='b_segments_input')
    
    a_bert_output = bert_model.call([input_a_ids, segment_a_ids])
    b_bert_output = bert_model.call([input_b_ids, segment_b_ids])
    
    merged = concatenatea([a_bert_output, b_bert_output])
    
    output = Dropout(rate=DR)(merged)
    output = Dense(units=2, activation='softmax', kernel_initializer=bert.initializer)(output)
    
    model = Model(inputs=[input_a_ids, segment_a_ids, input_b_ids, segment_b_ids], outputs=[output])
    
    model.compile(
        loss='sparse_categorical_crossentropy',
        optimizer=Adam(LR),
        metrics=['accuracy'],
    )
    return model

config_path = model_path+'bert_config.json'
checkpoint_path = model_path+'bert_model.ckpt'
dict_path = model_path+'vocab.txt'

tokenizer = Tokenizer(dict_path, do_lower_case=True)

bert = build_transformer_model(
    config_path = config_path,
    checkpoint_path = checkpoint_path,
    with_pool=True,
    model='bert',
    return_keras_model=False,
    )

K.clear_session()
model = build_model(bert)
early_stopping = EarlyStopping(monitor='val_loss', patience=1, verbose=1)
`

**Comment by YoungXu06** [comment]
你用call不会报`ttributeError: 'NoneType' object has no attribute '_inbound_nodes'`的错误吗？

**Comment by KunWangR** [comment]
我这没有遇到这样的错误，感觉`ValueError: Tensor("a_tokens_input:0", shape=(None, None), dtype=int32) must be from the same graph as Tensor("Embedding-Token/embeddings/Read/ReadVariableOp:0", shape=(21128, 768), dtype=float32).`可能与`K.clear_session()`有关，这是计算图的问题。至于你说的`ttributeError: 'NoneType' object has no attribute '_inbound_nodes'`这个问题感觉像是你自己代码里边变量的问题。

**Comment by earlzz** [comment]
可以放出你写的pairwise的代码码
