### ISSUE TITLE
疑似bug

### ISSUE THREAD

**Issue by FankLi** [bojone/bert4keras#125]
task_sequence_labeling_ner_crf.py

`from bert4keras.layers import *`
加载模型时，两种方式`load_model('ner.model', custom_objects={'sparse_loss':CRF. sparse_loss, 'sparse_accuracy':CRF. sparse_accuracy})`
`load_weights()`
都报错，错误如下：
`AttributeError: 'ConditionalRandomField' objects has no attribute 'trans'`

期待并感谢你的回复！！！

**Comment by bojone** [comment]
用`model.save_weights`保存权重，用同样的代码建立模型，然后用`model.load_weights`加载权重。

**Comment by FankLi** [comment]
> 用`model.save_weights`保存权重，用同样的代码建立模型，然后用`model.load_weights`加载权重。

这个方法也试了，同样报错呢
`AttributeError: 'ConditionalRandomField' objects has no attribute 'trans'`

**Comment by bojone** [comment]
> > 用`model.save_weights`保存权重，用同样的代码建立模型，然后用`model.load_weights`加载权重。
> 
> 这个方法也试了，同样报错呢
> `AttributeError: 'ConditionalRandomField' objects has no attribute 'trans'`

这样的方式不会报错，要错的话只可能是你自己用错。

**Comment by bojone** [comment]
> > > 用`model.save_weights`保存权重，用同样的代码建立模型，然后用`model.load_weights`加载权重。
> > 
> > 
> > 这个方法也试了，同样报错呢
> > `AttributeError: 'ConditionalRandomField' objects has no attribute 'trans'`
> 
> 这样的方式不会报错，要错的话只可能是你自己用错。

你可以`from task_sequence_labeling_ner_crf import *`试试，不报错说明没错。

**Comment by FankLi** [comment]
> > > > 用`model.save_weights`保存权重，用同样的代码建立模型，然后用`model.load_weights`加载权重。
> > > 
> > > 
> > > 这个方法也试了，同样报错呢
> > > `AttributeError: 'ConditionalRandomField' objects has no attribute 'trans'`
> > 
> > 
> > 这样的方式不会报错，要错的话只可能是你自己用错。
> 
> 你可以`from task_sequence_labeling_ner_crf import *`试试，不报错说明没错。

刚试了这个没有问题，所以我想就有个偷懒的方法来完成加载模型和predict：
`from task_sequence_labeling_ner_crf import *`
`named_entity_recognize(text)`

我再学习一下代码结构，再次感谢回复

**Comment by web199195** [comment]
https://blog.csdn.net/qq_43412423/article/details/106148648

**Comment by web199195** [comment]
> > > > 用`model.save_weights`保存权重，用同样的代码建立模型，然后用`model.load_weights`加载权重。
> > > 
> > > 
> > > 这个方法也试了，同样报错呢
> > > `AttributeError: 'ConditionalRandomField' objects has no attribute 'trans'`
> > 
> > 
> > 这样的方式不会报错，要错的话只可能是你自己用错。
> 
> 你可以`from task_sequence_labeling_ner_crf import *`试试，不报错说明没错。

https://blog.csdn.net/qq_43412423/article/details/106148648  这种貌似也行
