### ISSUE TITLE
NotFoundError: Key bert/encoder/embedding_hidden_mapping_in/kernel not found in checkpoint

### ISSUE THREAD

**Issue by sataliulan** [bojone/bert4keras#127]
NotFoundError: Key bert/encoder/embedding_hidden_mapping_in/kernel not found in checkpoint；
如题，使用bert4keras加载albert tiny报错，加载albert base正常

**Comment by bojone** [comment]
能不能高抬贵手贴上你的加载代码？我这边加载不会有错。

**Comment by sataliulan** [comment]
# bert配置
model_path=r'E:\hcl\ALBERT_NER_KERAS-master\albert_zh-master\albert_tiny_489k'
# config_path = model_path+'/albert_config_tiny_google.json'
config_path = os.path.join(model_path,'albert_config_tinyjson')
# checkpoint_path = model_path+'albert_model.ckpt'
checkpoint_path = os.path.join(model_path,'albert_model.ckpt')
# dict_path = model_path+'/vocab.txt'
dict_path = model_path+'/vocab.txt'
...
model = build_transformer_model(
    config_path,
    checkpoint_path,
    model='albert'
)

# output_layer = 'Transformer-%s-FeedForward-Norm' % (bert_layers - 1)
# output = model.get_layer(output_layer).output
output_layer = 'Transformer-FeedForward-Norm'
output = model.get_layer(output_layer).get_output_at(bert_layers - 1)
output = Dense(num_labels)(output)
CRF = ConditionalRandomField(lr_multiplier=crf_lr_multiplier)
output = CRF(output)

model = Model(model.input, output)
model.summary()

**Comment by bojone** [comment]
目测你不是用带google字眼的albert。

你可以用这里转换过的：https://github.com/bojone/albert_zh

**Comment by sataliulan** [comment]
我目前使用的是你百度网盘分享的名为albert_tiny_google_zh_489k.zip 的文件，错误变成了：ValueError: Asked to get output at node 11, but the layer has only 4 inbound nodes.求教。。。

**Comment by luzhongqiu** [comment]
这个是albert v1还是v2??

**Comment by YANYANYAN78** [comment]
我也遇到这个问题ValueError: Asked to get output at node 11, but the layer has only 4 inbound nodes
