### ISSUE TITLE
TypeError: Unexpected keyword argument passed to optimizer: learning_rate

### ISSUE THREAD

**Issue by a461925358** [bojone/bert4keras#128]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Tensorflow**版本: 
- 你使用的**Keras**版本: 
- 你使用的**bert4keras**版本: 
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by hwaking** [comment]
# keras=2.2.4 写法 
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(  lr  =lr_schedule(0)),
              metrics=['accuracy'])

# keras=2.3.0 写法 
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(  learning_rate  =lr_schedule(0)),
              metrics=['accuracy'])


由于在新版本的keras中(指大于等于2.3.0版本)，将原来的 lr 这一参数重命名为 leraning_rate，因此将 leraning_rate 重新改为 lr 即可解决报错问题
