### ISSUE TITLE
关系抽取模型运行报错

### ISSUE THREAD

**Issue by dengxuanxiang** [bojone/bert4keras#129]
### 基本信息
- windows操作系统**: 
- Python3.6版本: 
- Tensorflow2.2版本: 
- bert4keras最新版本: 

### 核心代码
if __name__ == '__main__':

    train_generator = data_generator(train_data, batch_size)
    evaluator = Evaluator()

    train_model.fit_generator(
        train_generator.forfit(),
        steps_per_epoch=len(train_generator),
        epochs=20,
        callbacks=[evaluator]
    )

else:

    train_model.load_weights('best_model.weights')

### 输出信息
InvalidArgumentError: Node 'training/AdamEMA/gradients/Transformer-11-FeedForward-Dropout/cond_grad/StatelessIf': Connecting to invalid output 1 of source node Transformer-11-FeedForward-Dropout/cond which has 1 outputs. Try using tf.compat.v1.experimental.output_all_intermediates(True).

代码与example中示例完全一样

**Comment by bojone** [comment]
暂未测试到tf 2.2，你可以根据提示在脚本开头设置`tf.compat.v1.experimental.output_all_intermediates(True)`试试。

另外，提一个私人建议：珍惜生命，远离tf2。
