### ISSUE TITLE
bert4keras和keras_bert不一致问题

### ISSUE THREAD

**Issue by qiuhuiGithub** [bojone/bert4keras#13]
在运行以下代码时，发现bert4keras会报错，keras_bert正常。以下是代码：
print('build bert model...')
bert_model = load_pretrained_model(config_path, checkpoint_path)
#替换成以下两行代码好使
#from keras_bert import load_trained_model_from_checkpoint
#bert_model = load_trained_model_from_checkpoint(config_path,checkpoint_path)
x1_input = Input(shape=(maxlen,), dtype='int32')
x2_input = Input(shape=(maxlen,), dtype='int32')
bert_output_layer = bert_model([x1_input, x2_input])
cls_output = Lambda(lambda x: x[:, 0])(bert_output_layer)
output = Dense(1, activation='sigmoid')(cls_output)
model = Model([x1_input, x2_input], output)
model.summary()

adam = Adam(lr=1e-4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
model.fit([word_index, sent_index], y_train, shuffle=True, batch_size=128, epochs=epochs, validation_split=0.1)

以下是错误：
InvalidArgumentError: You must feed a value for placeholder tensor 'Input-Token_3' with dtype float and shape [?,?]
	 [[{{node Input-Token_3}} = Placeholder[dtype=DT_FLOAT, shape=[?,?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
想问一下是什么原因呢？

**Comment by bojone** [comment]
已经定位到问题，正在想办法修复

**Comment by bojone** [comment]
已经修复～请重新测试

**Comment by tiandiweizun** [comment]
我测试是没有问题的

**Comment by qiuhuiGithub** [comment]
> 已经修复～请重新测试

测试没问题了，谢谢苏老师。
