### ISSUE TITLE
如何将bert当成一个普通的共享层来使用？

### ISSUE THREAD

**Issue by YoungXu06** [bojone/bert4keras#130]
接提问：https://github.com/bojone/bert4keras/issues/96

请问，怎么在一个自定义的模型里把bert当成一个共享层使用， 比如 `A = bert(A), B = bert(B)`这样的操作。下面的代码会报错：

```python
def build_model(model_path, mode='bert', LR=1e-5, DR=0.2, a_max_len=200, b_max_len=500):
    config_path = model_path+'bert_config.json'
    checkpoint_path = model_path+'bert_model.ckpt'
    
    bert = build_transformer_model(
        config_path = config_path,
        checkpoint_path = checkpoint_path
        )

    input_a_ids = Input(shape=[a_max_len,], dtype='int32', name='a_tokens_input')
    segment_a_ids = Input(shape=[a_max_len,], dtype='int32', name='a_segments_input')
    
    input_b_ids = Input(shape=[b_max_len,], dtype='int32', name='b_tokens_input')
    segment_b_ids = Input(shape=[b_max_len,], dtype='int32', name='b_segments_input')
    
    a_bert_output = bert([input_a_ids, segment_a_ids])
    b_bert_output = bert([input_b_ids, segment_b_ids])
    
    a_pool = GlobalAveragePooling1D()(a_bert_output)
    b_pool = GlobalAveragePooling1D()(b_bert_output)
    
    merged = concatenate([a_pool, b_pool])   
    output = Dropout(rate=DR)(merged)
    output = Dense(units=2, activation='softmax')(output)
    model = Model(inputs=[input_a_ids, segment_a_ids, input_b_ids, segment_b_ids], outputs=[output])
    
    model.compile(
        loss='sparse_categorical_crossentropy',
        optimizer=Adam(LR),
        metrics=['accuracy'],
    )
    print(model.summary())
    return model
```

**Comment by YoungXu06** [comment]
win10+tf2.1.0+keras2.2.4

**Comment by bojone** [comment]
keras自带的`GlobalAveragePooling1D`确实不够科学，最好自己重写一下，使得它支持变长shape

**Comment by xuyingjie521** [comment]
tf.keras自带的GlobalAveragePooling1D 我加了这个层，在py3.6下训练我也遇到过这个问题：
```
![企业微信截图_c568d29d-e55d-4110-9555-c3199cb6f0d3](https://user-images.githubusercontent.com/26736518/81250298-2d01cf00-9053-11ea-8b73-7b16c1907a57.png)

TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [-1, None, 1]. Consider casting elements to a supported type.
```

**Comment by YoungXu06** [comment]
> tf.keras自带的GlobalAveragePooling1D 我加了这个层，在py3.6下训练我也遇到过这个问题：
> 
> ```
> /data1/xuyingjie/project/zhihu_project2020Q1/user_feedback_algorithm_v2_py3/bert_train/roberta12_GRU_AvePooling_model.py in roberta_dense_model(config_path, checkpoint_path, label_num)
>     210                     name='GRU-Dense'
>     211                     )(bert_12_layer)
> --> 212     ave_pooing = GlobalAveragePooling1D(name='GlobalAveragePooling1D')(gru_dense)
>     213 
>     214     x_out = Dense(label_num,
> 
> ===============
> TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [-1, None, 1]. Consider casting elements to a supported type.
> ```

可以自己写一个全局最大(平均)池化层替代，比如最大池化：
`
max_pooling = Lambda(lambda x: K.max(x, axis=1, keepdims=False))
a_pool = max_pooling(a_bert_output)
b_pool =max_pooling(a_bert_output)
`

**Comment by YoungXu06** [comment]
> keras自带的`GlobalAveragePooling1D`确实不够科学，最好自己重写一下，使得它支持变长shape

暂时这么解决是可以的，如果bert能支持变长就很香了。

**Comment by xuyingjie521** [comment]
> > tf.keras自带的GlobalAveragePooling1D 我加了这个层，在py3.6下训练我也遇到过这个问题：
> > ```
> > /data1/xuyingjie/project/zhihu_project2020Q1/user_feedback_algorithm_v2_py3/bert_train/roberta12_GRU_AvePooling_model.py in roberta_dense_model(config_path, checkpoint_path, label_num)
> >     210                     name='GRU-Dense'
> >     211                     )(bert_12_layer)
> > --> 212     ave_pooing = GlobalAveragePooling1D(name='GlobalAveragePooling1D')(gru_dense)
> >     213 
> >     214     x_out = Dense(label_num,
> > 
> > ===============
> > TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [-1, None, 1]. Consider casting elements to a supported type.
> > ```
> 
> 可以自己写一个全局最大(平均)池化层替代，比如最大池化：
> `
> max_pooling = Lambda(lambda x: K.max(x, axis=1, keepdims=False))
> 
> a_pool = max_pooling(a_bert_output)
> 
> b_pool =max_pooling(a_bert_output)
> `

你这个实现很好，不过昨天我尝试了之前苏神的bert4keras==0.5.1版本，我构造的模型结构没变也含GlobalAveragePooling1D，训练保存和加载模型都是成功的；而用最新版本的bert4keras==0.7以后的就失败，我目前没来得及仔细分析这两个版本的变化。

**Comment by RingoTC** [comment]
可以分享一下你的模型文件吗？
我使用你的方法对bert进行共享，但在训练时却遇到如下错误：
`ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 4 array(s), but instead got the following list of 2 arrays: [array([[ 101, 6628,  677, ...,    0,    0,    0],
       [ 101,  741, 7027, ..., 3614,  677,  102],
       [ 101, 1920, 1914, ...,    0,    0,    0],
       ...,
       [ 101,  976, 2339, ...,    0, ...`

**Comment by RingoTC** [comment]
我也是使用的这种办法做共享层，但在模型训练的时候遇到这个错误：
`ValueError: Error when checking target: expected dense_73 to have shape (1,) but got array with shape (2,)`
不知道你遇到过吗？
