### ISSUE TITLE
0.7.3对tf1.12报错

### ISSUE THREAD

**Issue by BoostMom** [bojone/bert4keras#131]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**linux**: 
- 你使用的**Python**3.6: 
- 你使用的**Tensorflow**1.12: 
- 你使用的**Keras**版本:2.0.8 
- 你使用的**bert4keras**版本:0.7.3 
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:www_ext

### 核心代码
example/autotitle
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```
Traceback (most recent call last):
  File "sj_task_seq2seq_tag_gen.py", line 10, in <module>
    from bert4keras.backend import keras, K
  File "/root/anaconda3/lib/python3.6/site-packages/bert4keras/backend.py", line 18, in <module>
    ops.disable_eager_execution()
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'disable_eager_execution'
### 自我尝试
回退到0.7.0没有问题,因为新代码需要用Loss层，tensorflow1.14版本可用

**Comment by bojone** [comment]
权宜之计：你可以手动删掉`backend.py`里边报错的那几行（跟`disable_eager_execution`相关的）。
