### ISSUE TITLE
测试样例代码，显卡没有使用

### ISSUE THREAD

**Issue by xudai** [bojone/bert4keras#134]
运行task_sentiment_albert.py , 发现显卡没有被使用
系统配置“
python3.6
tensorflow-gpu==1.14.0

**Comment by bojone** [comment]
bert4keras不控制你的GPU使用...

**Comment by xudai** [comment]
果然是环境的问题，谢谢。

**Comment by WatsonWangZh** [comment]
> 运行task_sentiment_albert.py , 发现显卡没有被使用
> 系统配置“
> python3.6
> tensorflow-gpu==1.14.0



> 果然是环境的问题，谢谢。

请问是怎么排查的啊？
