### ISSUE TITLE
请问 `keep_words` 这个列表的值的顺序会对model有影响吗

### ISSUE THREAD

**Issue by realize-qzq** [bojone/bert4keras#136]
keep_words是和实际词典大小一致的列表，keep_words的word id的顺序会影响model的实际效果吗，直接从实际的词典dict里遍历append得到keep_words可以吗
### 
```
model = get_model(config_path, checkpoint_path, keep_words, args.albert, args.lr)
```

**Comment by bojone** [comment]
现在已经改名为`keep_tokens`了，里边的每个id，对应着旧词表里边的token_id

**Comment by realize-qzq** [comment]
> 现在已经改名为`keep_tokens`了，里边的每个id，对应着旧词表里边的token_id
意思是`keep_tokens`里面id的可以是旧词表里边的token_id的乱序或者顺序都ok吗

**Comment by bojone** [comment]
> > 现在已经改名为`keep_tokens`了，里边的每个id，对应着旧词表里边的token_id
> > 意思是`keep_tokens`里面id的可以是旧词表里边的token_id的乱序或者顺序都ok吗

可以的
