### ISSUE TITLE
models.load_model无法加载models.save_model保存的模型，提升ValueError: Unknown layer: FactorizedEmbedding

### ISSUE THREAD

**Issue by tiandiweizun** [bojone/bert4keras#14]
models.load_model无法加载models.save_model保存的模型，提升ValueError: Unknown layer: FactorizedEmbedding，我看示例里面是 save_weights，但是我希望模型结构也保存起来

**Comment by bojone** [comment]
最新版本已经支持了

**Comment by tiandiweizun** [comment]
测试没有问题，谢谢了。
