### ISSUE TITLE
使用ELECTRA模型，delete_arguments函数删不掉相关参数，TypeError错误！！

### ISSUE THREAD

**Issue by luckper** [bojone/bert4keras#143]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Linux
- 你使用的**Python**版本: 3.6
- 你使用的**Tensorflow**版本: 1.14
- 你使用的**Keras**版本: 2.2.4
- 你使用的**bert4keras**版本: 0.7.4
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:ELECTRA

### 核心代码
snippets.py的delete_arguments函数

ELECTRA模型的类
class ELECTRA(BertModel):
    """Google推出的ELECTRA模型
        链接：https://arxiv.org/abs/2003.10555
        """
    @delete_arguments('with_pool','with_mlm')
    def __init__(
            self,
            max_position_embeddings,
            **kwargs
    ):
        if 'keep_words' in kwargs:
            del kwargs['keep_words']

        super(ELECTRA, self).__init__(max_position_embeddings, **kwargs)
    
    def variable_mapping(self, variable_names):
        mapping = super(ELECTRA, self).variable_mapping(variable_names)
        mapping['Embedding_Mapping'] = [
            'electra/embeddings_project/kernel',
            'electra/embeddings_project/bias',
        ]
        mapping = {
            k: [i.replace('bert/', 'electra/') for i in v]
            for k, v in mapping.items()
        }
        return mapping

### 输出信息
```shell
# 请在此处贴上你的调试输出
输出提示TypeError！！！！
Traceback (most recent call last):
  File "self_train.py", line 76, in <module>
    ner_train_module.train()
  File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/ner_train_module.py", line 71, in train
    model, loss = model.build_model()
  File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/model/ner_model.py", line 62, in build_model
    albert=is_albert, inputs=inputs)
  File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/utils/bert4keras/bert.py", line 448, in build_bert_model
    inputs=inputs)
  File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/utils/bert4keras/snippets.py", line 185, in new_func
    (self.__class__.__name__, k)
TypeError: ELECTRA got an unexpected keyword argument 'with_pool'

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
修改了基类BertModule传入参数以及更新bert4keras版本，都是不太行

**Comment by luckper** [comment]
> 提问时请尽可能提供如下信息：
> 
> ### 基本信息
> * 你使用的**操作系统**: Linux
> * 你使用的**Python**版本: 3.6
> * 你使用的**Tensorflow**版本: 1.14
> * 你使用的**Keras**版本: 2.2.4
> * 你使用的**bert4keras**版本: 0.7.4
> * 你使用纯**keras**还是**tf.keras**:
> * 你加载的**预训练模型**:ELECTRA
> 
> ### 核心代码
> snippets.py的delete_arguments函数
> 
> ELECTRA模型的类
> class ELECTRA(BertModel):
    """Google推出的ELECTRA模型
        链接：https://arxiv.org/abs/2003.10555
        """
    @delete_arguments('with_pool', 'with_mlm')
    def __init__(
            self,
            max_position_embeddings,
            **kwargs
    ):
        if 'keep_words' in kwargs:
            del kwargs['keep_words']

        super(ELECTRA, self).__init__(max_position_embeddings, **kwargs)

    def variable_mapping(self, variable_names):
        mapping = super(ELECTRA, self).variable_mapping(variable_names)
        mapping['Embedding_Mapping'] = [
            'electra/embeddings_project/kernel',
            'electra/embeddings_project/bias',
        ]
        mapping = {
            k: [i.replace('bert/', 'electra/') for i in v]
            for k, v in mapping.items()
        }
        return mapping
> ```
> 
> ### 输出信息
> ```shell
> # 请在此处贴上你的调试输出
> 输出提示TypeError！！！！
> Traceback (most recent call last):
>   File "self_train.py", line 76, in <module>
>     ner_train_module.train()
>   File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/ner_train_module.py", line 71, in train
>     model, loss = model.build_model()
>   File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/model/ner_model.py", line 62, in build_model
>     albert=is_albert, inputs=inputs)
>   File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/utils/bert4keras/bert.py", line 448, in build_bert_model
>     inputs=inputs)
>   File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/utils/bert4keras/snippets.py", line 185, in new_func
>     (self.__class__.__name__, k)
> TypeError: ELECTRA got an unexpected keyword argument 'with_pool'
> 
> ### 自我尝试
> 不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
> 修改了基类BertModule传入参数以及更新bert4keras版本，都是不太行
> ```

**Comment by luckper** [comment]
> 提问时请尽可能提供如下信息：
> 
> ### 基本信息
> * 你使用的**操作系统**: Linux
> * 你使用的**Python**版本: 3.6
> * 你使用的**Tensorflow**版本: 1.14
> * 你使用的**Keras**版本: 2.2.4
> * 你使用的**bert4keras**版本: 0.7.4
> * 你使用纯**keras**还是**tf.keras**:
> * 你加载的**预训练模型**:ELECTRA
> 
> ### 核心代码
> snippets.py的delete_arguments函数
> 
> ELECTRA模型的类
> class ELECTRA(BertModel):
    @delete_arguments('with_pool', 'with_mlm')
    def __init__(
            self,
            max_position_embeddings,
            **kwargs
    ):
        if 'keep_words' in kwargs:
            del kwargs['keep_words']

        super(ELECTRA, self).__init__(max_position_embeddings, **kwargs)

    def variable_mapping(self, variable_names):
        mapping = super(ELECTRA, self).variable_mapping(variable_names)
        mapping['Embedding_Mapping'] = [
            'electra/embeddings_project/kernel',
            'electra/embeddings_project/bias',
        ]
        mapping = {
            k: [i.replace('bert/', 'electra/') for i in v]
            for k, v in mapping.items()
        }
        return mapping
> ```
> 
> ### 输出信息
> ```shell
> # 请在此处贴上你的调试输出
> 输出提示TypeError！！！！
> Traceback (most recent call last):
>   File "self_train.py", line 76, in <module>
>     ner_train_module.train()
>   File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/ner_train_module.py", line 71, in train
>     model, loss = model.build_model()
>   File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/model/ner_model.py", line 62, in build_model
>     albert=is_albert, inputs=inputs)
>   File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/utils/bert4keras/bert.py", line 448, in build_bert_model
>     inputs=inputs)
>   File "/home/neobp/local_disk/chenwei/keras_ner/ner_keras/utils/bert4keras/snippets.py", line 185, in new_func
>     (self.__class__.__name__, k)
> TypeError: ELECTRA got an unexpected keyword argument 'with_pool'
> 
> ### 自我尝试
> 不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
> 修改了基类BertModule传入参数以及更新bert4keras版本，都是不太行
> ```

**Comment by bojone** [comment]
这不是说得很清楚了吗，ELECTRA不支持with_pool参数啊，你非要传入with_pool参数，还非要说是程序的错。。。。

**Comment by luckper** [comment]
@bojone  class ELECTRA里，有@delete_arguments('with_pool','with_mlm')，进行类方法参数删除处理，但是不知道怎么还是提示传入了。
看咱们bert4keras代码里面，class ELECTRA里也是这么删除处理的，BERT类里，也是有with_pool和with_mlm参数的
