### ISSUE TITLE
NER crf_lr_multiplier无效

### ISSUE THREAD

**Issue by majialin** [bojone/bert4keras#144]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Ubuntu 18.04
- 你使用的**Python**版本:  python3.6
- 你使用的**Tensorflow**版本:  1.15.0
- 你使用的**Keras**版本: tf.keras
- 你使用的**bert4keras**版本: git clone 2020/05/09
- 你使用纯**keras**还是**tf.keras**:  tf.keras
- 你加载的**预训练模型**: ablert_base

#### example/task_sequence_labeling_ner_crf.py

如原样运行 `crf_lr_multiplier = 1000` , 则
```shell
conditional_random_field (Condi (None, None, 7)      0           dense_6[0][0]
```
CRF层参数量为0，且NER.trans或CRF.trans 保持初始值，不受训练影响。

如修改 `crf_lr_multiplier = 1`, 则
```shell
conditional_random_field (Condi (None, None, 7)      49          dense_6[0][0]
```
CRF层参数量正确，但NER.trans变化小（训练速率低）

原因：
layers.py中
```
if self.lr_multiplier != 1:
            K.set_value(self.trans, K.eval(self.trans) / self.lr_multiplier)
            self.trans = self.lr_multiplier * self.trans
```
会改变trans的类型。
如修改为
```
if self.lr_multiplier != 1:
            K.set_value(self.trans, K.eval(self.trans) / self.lr_multiplier)
            K.set_value(self.trans, K.eval(self.trans) * self.lr_multiplier)
```
则这种方法也起不到学习速率倍率变化的作用。

**Comment by bojone** [comment]
谢谢反馈，确实有这个问题，目前已经修复：https://github.com/bojone/bert4keras/commit/3cf7a7a968b1c18fb3b9be3350d3a5e8a4925dd9

**Comment by majialin** [comment]
@bojone 
问题确已修复
还想请教两个问题：
1. 因为CRF学习速率可能会不合适（偏小），随机初始化因此会起到反作用。`initializer='zeros'`应该会更好些？
2. CRF学习速率调高 是否 总是不会带来坏处呢？
  2.1 CRF学习速率过高 导致 BERT层拟合能力被掩盖一些？

**Comment by bojone** [comment]
> @bojone
> 问题确已修复
> 还想请教两个问题：
> 
> 1. 因为CRF学习速率可能会不合适（偏小），随机初始化因此会起到反作用。`initializer='zeros'`应该会更好些？
> 2. CRF学习速率调高 是否 总是不会带来坏处呢？
>    2.1 CRF学习速率过高 导致 BERT层拟合能力被掩盖一些？

直觉上初始化问题不大。

个人观察到的结论是：CRF学习率太高可能会导致不收敛，而适当增加CRF学习率有助于提高收敛速度，有时候能提升效果。
