### ISSUE TITLE
tf.keras兼容问题

### ISSUE THREAD

**Issue by flydsc** [bojone/bert4keras#15]
您好，感谢您提供的工具！

我遇到一个问题，不清楚是不是bug，想请您帮忙看一下。

在测试引用的时候，仅仅只是做import如下代码
```python
import os
os.environ['TF_KERAS'] = '1'
from bert4keras.bert import load_pretrained_model, set_gelu
from bert4keras.utils import SimpleTokenizer, load_vocab
from bert4keras.train import PiecewiseLinearLearningRate
set_gelu('tanh')
```

会得到错误
···
 File "/home/flydsc/anaconda3/envs/main_work/lib/python3.7/site-packages/bert4keras/bert.py", line 4, in <module>
    from .layers import *
  File "/home/flydsc/anaconda3/envs/main_work/lib/python3.7/site-packages/bert4keras/layers.py", line 60, in <module>
    class OurLayer(Layer):
NameError: name 'Layer' is not defined
···

但是当我去掉前两行关于环境变量的设定，即：
```python
from bert4keras.bert import load_pretrained_model, set_gelu
from bert4keras.utils import SimpleTokenizer, load_vocab
from bert4keras.train import PiecewiseLinearLearningRate
set_gelu('tanh')
```

import成功

猜测是TensorFlow.keras 在 ·globals().update(keras.layers.__dict__)· 的兼容性有一点问题？

我的环境是
python 3.7
TensorFlow 1.14.0

再次感谢您的无私。

**Comment by bojone** [comment]
这就有点奇怪了，我测过tf 1.13和tf 2.0都没问题。不知道是python3的问题还是tf 1.14的问题

**Comment by flydsc** [comment]
> 这就有点奇怪了，我测过tf 1.13和tf 2.0都没问题。不知道是python3的问题还是tf 1.14的问题

您好，中午大概测试了一下，用conda的环境测试3.7和2.7，在tf 1.13.1下均无问题，看来应该是tf 1.14的问题了。

**Comment by bojone** [comment]
更新了一个版本，测试了一下已经没有问题了，烦请再试用一下。

**Comment by flydsc** [comment]
感谢更新，import问题在1.14.0没问题了。谢谢！
