### ISSUE TITLE
是否可以写几个利用多GPU的example呢

### ISSUE THREAD

**Issue by xujunrt** [bojone/bert4keras#154]
### 自我尝试
测试发现现有模型多GPU，只有一块GPU负载高，其他的很低

**Comment by bojone** [comment]
我平时基本没有多gpu需求。我尽量吧～

**Comment by qiuhuiGithub** [comment]
多GPU的话，一个做法是使用keras自带的`keras.utils.multi_gpu_model`，但好像训练精度有影响，而且不太能多机多卡。还有就是用`horovod`，但可能不太好改。

**Comment by cyjj** [comment]
@qiuhuiGithub 请问多GPU你有没有试过？能不能分享一下经验，我这边按照doc中用multi_gpu_model包住model训练看见还是只有一个gpu有负载，如果用tf strategy会报NotImplementedError. 测试在tf2.0.0下进行。

**Comment by xujunrt** [comment]
我这边也是，一直用不了多gpu




| |
xujunrt
|
|
邮箱：xujunrt@163.com
|

Signature is customized by Netease Mail Master

在2020年06月08日 21:03，Matthew 写道：

@qiuhuiGithub 请问多GPU你有没有试过？能不能分享一下经验，我这边按照doc中用multi_gpu_model包住model训练看见还是只有一个gpu有负载，如果用tf strategy会报NotImplementedError. 测试在tf2.0.0下进行。

**Comment by mahao01** [comment]
> @qiuhuiGithub 请问多GPU你有没有试过？能不能分享一下经验，我这边按照doc中用multi_gpu_model包住model训练看见还是只有一个gpu有负载，如果用tf strategy会报NotImplementedError. 测试在tf2.0.0下进行。

简单测试了一下，`multi_gpu_model`依然没用上多GPU，前面苏神提到的 [tf MirroredStrategy](https://tf.wiki/zh_hans/appendix/distributed.html) 是可以的，使用方法也超级简单，把`model.compile`之前的代码放到 `strategy.scope()` 就可以，例如[语义相似度例子](https://github.com/bojone/bert4keras/blob/master/examples/task_sentence_similarity_lcqmc.py) 就改成（应该是这样，自测两个gpu显存都用上了，要是不对还请指出）：
```python
# 多GPU，加两行代码一个缩进
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
	# 加载预训练模型
	bert = build_transformer_model(
	    config_path=config_path,
	    checkpoint_path=checkpoint_path,
	    with_pool=True,
	    return_keras_model=False,
	)

	output = Dropout(rate=0.1)(bert.model.output)
	output = Dense(
	    units=2, activation='softmax', kernel_initializer=bert.initializer
	)(output)

	model = keras.models.Model(bert.model.input, output)
	model.summary()

	model.compile(
	    loss='sparse_categorical_crossentropy',
	    optimizer=Adam(2e-5),  # 用足够小的学习率
	    # optimizer=PiecewiseLinearLearningRate(Adam(5e-5), {10000: 1, 30000: 0.1}),
	    metrics=['accuracy'],
	)
```

**Comment by cyjj** [comment]
@mahao01 我之前又折腾了一段还是不成功，我的做法和你类似我用的是情感分类的例子，想知道你用的是哪个版本的tf。我用的是2.0.0，试验下来有两个点，一个是需要用tf-keras，一个是生成batch的函数需要一定修改，直接用确实两块显存都被占用了，但是training直接hang住了接着会oom看了一下好像可能大约是直接沿用苏神的generator框架接收到的是整个数据集形成的单一batch。所以想问一下你有改苏神的generator吗，感谢~~

ps：我觉得keras单卡的体验比tf strategy要好，一定是我太菜了 T_T

**Comment by mahao01** [comment]
没有哎，我tf是2.2.0，其它我没有做任何修改，就只加了这两行，然后就可以正常run起来了，你oom的话确定batch大小可以吗

**Comment by cyjj** [comment]
@mahao01 我的oom看见batch size就是全部数据集，就感觉在generator哪里设定的size没有生效。。。。我觉得可能是2.0.0的问题。。。

**Comment by AnddyWang** [comment]
@mahao01 @cyjj 求教下，GPU多卡解决了么，我tf1.4.0，用tf strategy 还是只用起来一张卡；multi_gpu_model的话会直接报错呢

**Comment by cyjj** [comment]
@AnddyWang 1.4的话没试过诶，我是2.0.0然后还是有点问题，如我上面所说我倾向于升级可以解决这个问题。。。我个人猜想

**Comment by cyjj** [comment]
> @cyjj 我用了2.2.0 tf stategy能占满所有卡的显存，但只有一个卡在计算，感觉还是不太对呢，有没有大神有个demo 哈哈

嗯能有一个卡再跑还行，我用2.0尝试只有占满没有跑。。。

**Comment by bojone** [comment]
https://github.com/bojone/bert4keras/blob/master/examples/task_seq2seq_autotitle_multigpu.py

**Comment by Chouyuhin** [comment]
> tf stategy

你好，我也是这个问题，请问你解决了吗？是不是dataset的方式也要改成多卡呀
