### ISSUE TITLE
task_relation_extraction.py在tensorflow-gpu 2.2.0下跑loss根本都不下降

### ISSUE THREAD

**Issue by gekie** [bojone/bert4keras#161]
task_relation_extraction.py在tensorflow-gpu 2.2.0下跑loss根本都不下降
在tensorflow-gpu 1.14.0下跑能正常收敛得到正常的F1

**Comment by WatsonWangZh** [comment]
> task_relation_extraction.py在tensorflow-gpu 2.2.0下跑loss根本都不下降
> 在tensorflow-gpu 1.14.0下跑能正常收敛得到正常的F1

Did you find the solution?

**Comment by a461925358** [comment]
请问这个问题解决了么？
