### ISSUE TITLE
tf.keras 比 纯keras 在GPU上训练速度下降一半

### ISSUE THREAD

**Issue by bowenliang123** [bojone/bert4keras#162]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Win 10
- 你使用的**Python**版本: Python 3.7
- 你使用的**Tensorflow**版本: Tensorflow 2.1.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.7.8 
- 你加载的**预训练模型**: electra-tiny
- 使用的显卡：NVIDIA GeForce 2070 SUPER
- CUDA 版本： 10.1

设置环境变量TF_KERAS=1启用 tf.keras 后，fit模型训练速度下降一半
（fit已启用multi_processing=True, workers=4）

使用纯keras：CUDA 负载保持97%-98%，显卡总体利用率22%
使用tf.keras：CUDA 负载保持40-45%，显卡总体利用率10%

逻辑参照的是examples/task_sentiment_albert.py用于文本情感分类

**Comment by bojone** [comment]
不要意外，tf就是越新越垃圾。

速度上：keras > tf.keras，tf 1.x > tf 2.x
结论：keras + tf 1.x >> tf.keras + tf 2.x

**Comment by bowenliang123** [comment]
@bojone 你误解这个issue了，无论tf.keras 比 纯keras，用的tensorflow版本都是2.1

严格上是一样tf版本的后端，运行效率应该一致的。

建议你做一下实验也对比一次。

tf.keras取代纯keras是大势所趋，连keras官网的文档已经全是tf.keras了

**Comment by bojone** [comment]
我没误解啊，“速度上：keras > tf.keras，tf 1.x > tf 2.x”，不是说得很清楚了么？

所以我说你要单卡获得最高效率，最佳组合就是“keras + tf 1.x”。

“严格上是一样tf版本的后端，运行效率应该一致的。”这个逻辑完全不成立。keras走的是静态图路线，tf.keras走的是垃圾eager动态图，既然是垃圾，慢一点正常。

你在tf 2.x里边，直接把eager给disable掉，其他什么都不变，都可以有一定的速度提升。（再次，垃圾eager）

“tf.keras取代纯keras是大势所趋”，这就算了吧，我1.x用得好好的，干嘛要作死，至于“keras官网的文档已经全是tf.keras”，这就是keras走向没落的开端了，keras作者亲自把keras糟蹋了。

**Comment by bowenliang123** [comment]
作者无法提供任何有效的建议，也没有进行合理的回复。

建议遇到类似问题的进行实验后补充。瓶颈可能出在封装和IO上。

**Comment by bojone** [comment]
> 作者无法提供任何有效的建议，也没有进行合理的回复。
> 
> 建议遇到类似问题的进行实验后补充。瓶颈可能出在封装和IO上。

一样的代码，只要keras/tf.keras都能跑通，基本上tf.keras都会慢一些，不管具体原因出在哪里，反正都是tf.keras的问题。

什么叫做“也没有进行合理的回复”？我前面的回复哪里不合理了？我告诉你keras比tf.keras是普适现象，我还多告诉你tf 1.x比tf 2.x更快，哪里不合理了？我还告诉你在tf 2.x里边把eager给关掉也能提速，哪里不合理了？

**Comment by bowenliang123** [comment]
Good luck.
