### ISSUE TITLE
ViterbiDecoder类代码请教：M = scores + self.trans + nodes[l].reshape((1, -1))

### ISSUE THREAD

**Issue by xuyingjie521** [bojone/bert4keras#168]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Tensorflow**版本: 
- 你使用的**Keras**版本: 
- 你使用的**bert4keras**版本: 
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

###请教苏神
苏神你好，请教一下 你的snippets.py文件的Viterbi算法在查找最大概率的时候为什么要引入CRF层的self.trans参数？可以只用M = scores + nodes[l].reshape((1, -1))吗？
因为我这边python是基于你的bert4keras训练好的实体模型，但是上线用的Java，所以在Java写你的ViterbiDecoder类的时候被 
self._trans = self.add_weight(
            name='trans',
            shape=(output_dim, output_dim),
            initializer='glorot_uniform',
            trainable=True
        )
所困扰了😂， 还希望苏神能抽出点宝贵时间帮小弟解答一下，谢谢啦！

**Comment by bojone** [comment]
1、你先去补习一下什么叫CRF...没有trans的还叫CRF吗？
2、训练完成后，trans的值就是固定的了，你可以直接写死它，不一定要跟原模型产生关联。

**Comment by xuyingjie521** [comment]
谢谢苏神！（哈哈 我知道CRF是应该有trans的，可能我问的方式不对吧😄  ）

**Comment by xuyingjie521** [comment]
> 1、你先去补习一下什么叫CRF...没有trans的还叫CRF吗？
> 2、训练完成后，trans的值就是固定的了，你可以直接写死它，不一定要跟原模型产生关联。

谢谢苏神！（哈哈 我知道CRF是应该有trans的，可能是我问的方式不对吧😄 ）
