### ISSUE TITLE
build_transformer_model() 代码有问题

### ISSUE THREAD

**Issue by houlk** [bojone/bert4keras#169]
下面这段代码，如果我build的模型是electra或t5，会直接跳到 raise ValueError。如果只是为了避免Electra或者t5用于语言模型，应该采用其他写法。

if model not in ['electra', 't5']:
        if application == 'lm':
            MODEL = extend_with_language_model(MODEL)
        elif application == 'unilm':
            MODEL = extend_with_unified_language_model(MODEL)
        elif application == 'punilm':
            MODEL = extend_with_parallel_unified_language_model(MODEL)
 else:
       raise ValueError(
            '"%s" model can not be used as "%s" application.\n' %
            (model, application)
        )

**Comment by bojone** [comment]
理解了，是我的疏忽，感谢反馈。

**Comment by bojone** [comment]
已经修复：https://github.com/bojone/bert4keras/commit/c8467c989a27a0fc4bf2a9b114b1a910aee3474f

**Comment by houlk** [comment]
收到，多谢~

**Comment by bestpredicts** [comment]
unilm是不是也不支持gpt2_ml 将模型换成gpt2_ml 调用build_transformer_model()  报错。

AttributeError: 'UnifiedLanguageModel' object has no attribute 'with_mlm'

**Comment by bojone** [comment]
> unilm是不是也不支持gpt2_ml 将模型换成gpt2_ml 调用build_transformer_model() 报错。
> 
> AttributeError: 'UnifiedLanguageModel' object has no attribute 'with_mlm'

不支持，gpt2_ml本身就是语言模型，不能加其他mask了。
