### ISSUE TITLE
load_model后每次预测结果不一致

### ISSUE THREAD

**Issue by Fan9** [bojone/bert4keras#17]
load_model后用同一批测试集每次测试结果都不一样。苏神能否在example中给出load_model/load_weights的例子。

**Comment by bojone** [comment]
我这里并没有出现这个问题，测试脚本见：
https://github.com/bojone/bert4keras/blob/master/examples/basic_extract_features.py

**Comment by Fan9** [comment]
我自己的问题， 每次预测初始化tokener不一致导致。感谢苏神
