### ISSUE TITLE
'Model' object has no attribute '_make_train_function'

### ISSUE THREAD

**Issue by apple55bc** [bojone/bert4keras#174]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: windows和linux都有
- 你使用的**Python**版本: 3.7
- 你使用的**Tensorflow**版本: 2.2
- 你使用的**Keras**版本: 无
- 你使用的**bert4keras**版本:0.7.5 
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**:roberta

### 核心代码
```python
self.strategy = tf.distribute.MirroredStrategy()
            with self.strategy.scope():
                self.model = get_model()
adversarial_training(self.model, embedding_name='Embedding-Token', epsilon=0.4)
```

### 输出信息
```shell
'Model' object has no attribute '_make_train_function'
```

### 自我尝试
去掉MirroredStrategy() 也是一样的报错
切换到1.x就不报错了（1.x也是同样适用内置keras）

**Comment by bojone** [comment]
2.x中可能这个函数改名了，我尝试修复下。

**Comment by bojone** [comment]
我看了一下，tf 2.x下的tf.keras我也不知道怎么写了～动态图的逻辑我理解不了啊。

**Comment by luoda888** [comment]
苏老板，这个bug修复好了吗

**Comment by ZhuiyiTechnology** [comment]
> 苏老板，这个bug修复好了吗

这不是bug，这就是在tf 2.x下的tf.keras不能用，我也不打算研究怎么用。

**Comment by bojone** [comment]
> 苏老板，这个bug修复好了吗

这不是bug，这就是在tf 2.x下的tf.keras不能用，我也不打算研究怎么用。

**Comment by axelning** [comment]
这个问题我提到google去了，动态图底下是make_train_function，加前缀的是v1的api
