### ISSUE TITLE
关于bert输入样本长度的问题

### ISSUE THREAD

**Issue by sanexodus** [bojone/bert4keras#177]
苏神你好，
在学习bert4keras的代码过程中关于样本长度的问题困扰我好久，以task_relation_extraction为例，我观察到在生成数据的时候您并没有把样本pad到maxlen,而是pad到一个batch内最大的长度（该长度<=maxlen），这就会导致同一个batch内的样本有着同样的长度，而不同batch之间的样本长度是不同的。
              `if len(batch_token_ids) == self.batch_size or is_end:
                    batch_token_ids = sequence_padding(batch_token_ids)
                    batch_segment_ids = sequence_padding(batch_segment_ids)
                    batch_subject_labels = sequence_padding(
                        batch_subject_labels
                    )
                    batch_subject_ids = np.array(batch_subject_ids)
                    batch_object_labels = sequence_padding(batch_object_labels)`,
但是我理解的bert应该是需要固定的长度的吧？（如果理解错误请指正。）看了一些其他的例子（如下），一般的做法都会把样本pad到maxlen，
`    input_ids = tokenizer.convert_tokens_to_ids(tokens)
      # The mask has 1 for real tokens and 0 for padding tokens. Only real
      # tokens are attended to.
      input_mask = [1] * len(input_ids)

      # Zero-pad up to the sequence length.
      while len(input_ids) < max_seq_length:
        input_ids.append(0)
        input_mask.append(0)
        segment_ids.append(0)`
所以我猜想是不是bert4keras的内部封装实现了pad到maxlen的操作，所以按照这个想法我就继续看代码，跟进到了bert4keras的models.py模块里面的get_inputs函数，
`x_in = Input(shape=(self.sequence_length,), name='Input-Token')
  s_in = Input(shape=(self.sequence_length,), name='Input-Segment')`，这里的self.sequence_length传进来的是None,也没法证实我的猜想。但是我看到如下代码中有mask_zero=True的传值
`def apply_embeddings(self, inputs):
        """BERT的embedding是token、position、segment三者embedding之和
        """
        x, s = inputs[:2]
        z = self.layer_norm_conds[0]
        if self.custom_position_ids:
            p = inputs[2]
        else:
            p = None

        x = self.apply(
            inputs=x,
            layer=Embedding,
            input_dim=self.vocab_size,
            output_dim=self.embedding_size,
            embeddings_initializer=self.initializer,
            mask_zero=True,
            name='Embedding-Token'
        )`，根据文档说明mask_zero只是会把0当作padding去处理。

篇幅有点长，总结一下，对于bert4keras中padding的长度问题，请问我理解的bert需要固定的输入长度是否正确？如果正确的话请问bert4keras中为何只是padding到batch的最大长度，是否在bert4keras内部进行了处理，如果是的话 能否告知大概的代码位置（keras新手，请见谅），感谢您能够抽时间对本问题进行回复，谢谢。

**Comment by bojone** [comment]
“bert需要固定的输入长度”不正确，任何合理的计算框架都不会有这个限制，最多是要求每个batch内的每个样本长度一致。

**Comment by sanexodus** [comment]
> “bert需要固定的输入长度”不正确，任何合理的计算框架都不会有这个限制，最多是要求每个batch内的每个样本长度一致。

感谢苏神，我能够理解了。
