### ISSUE TITLE
修改了版本号，最好能界面上写一下-。-

### ISSUE THREAD

**Issue by luzhongqiu** [bojone/bert4keras#178]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Tensorflow**版本: 
- 你使用的**Keras**版本: 
- 你使用的**bert4keras**版本: 
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by bojone** [comment]
你是说记录每一次的版本号变更么？
看这里（ https://github.com/bojone/bert4keras/commits/master/setup.py ）就行了呀

**Comment by luzhongqiu** [comment]
情况是这样子的，我原来引用了版本号是bert4keras==0.1.9  突然发现没了。然后对比了最新的代码，决定用bert4keras==0.7.9 作为替代。。

**Comment by bojone** [comment]
> 情况是这样子的，我原来引用了版本号是bert4keras==0.1.9 突然发现没了。然后对比了最新的代码，决定用bert4keras==0.7.9 作为替代。。

0.1.9，那还没提交到pip上面去吧～～
