### ISSUE TITLE
预测时怎么设置CPU的使用率？

### ISSUE THREAD

**Issue by jangqh** [bojone/bert4keras#189]
求教，想使用CPU做预测，发现会占用所有的CPU核，怎么设置一下呢？
tf1.x的时候还可以这样设置，你用的keras怎么设置呢
cpu_num = int(os.environ.get('CPU_NUM',1))
config = tf.ConfigProto(device_count={"CPU": cpu_num},
                inter_op_parallelism_threads = cpu_num,
                intra_op_parallelism_threads = cpu_num,
                log_device_placement=True)
with tf.Session(config = config) as sess:

**Comment by bojone** [comment]
```python
import keras.backend as K
set_session(tf.Session(config=config))
```

**Comment by jangqh** [comment]
感谢
