### ISSUE TITLE
加载模型报错

### ISSUE THREAD

**Issue by anjubaoGDUT** [bojone/bert4keras#19]
![image](https://user-images.githubusercontent.com/25845940/67557767-4511a100-f748-11e9-8933-8b306c655094.png)

ValueError: You called `set_weights(weights)` on layer "Encoder-1-MultiHeadSelfAttention" with a  weight list of length 8, but the layer was expecting 0 weights. Provided weights: [array([[ 0.03122838,  0.04661432,  0.00716374, .....

我试过了https://github.com/brightmart/albert_zh 的两个预训练模型：
albert_base_zh(额外训练了1.5亿个实例即 36k steps * batch_size 4096);
albert_base_zh(小模型体验版)

但是都报类似的错误，请问作者知道是什么原因吗？

**Comment by bojone** [comment]
请瞪大眼睛看准所要求的keras版本
