### ISSUE TITLE
预训练中可以只保留 bert的权重吗 ，而不是train_model 模型的权重

### ISSUE THREAD

**Issue by comingboy0701** [bojone/bert4keras#191]
1. 预训练中可以只保留 bert的权重吗 ，而不是train_model 模型的权重，主要是为了更方便在微调中直接加载预训练的模型

2. 还是只能在微调中获取bert最后一层的cls向量

3. 或者还有其它的方法，求赐教，谢谢

**Comment by comingboy0701** [comment]
我在预训练的模型的中已经只保留了 bert 模型：
class ModelCheckpoint(keras.callbacks.Callback):
    """自动保存最新模型
    """
    def on_epoch_end(self, epoch, logs=None):
#         self.model.save_weights(model_saved_path, save_format = "tf",overwrite=True)
        bert_model = Model(inputs=self.model.input[:2],outputs=train_model.get_layer('MLM-Norm').output)
        bert_model.save_weights(model_saved_path, save_format = "tf",overwrite=True)

微调的时候报错(和保留train_model一样的错误)

# 加载预训练模型
bert = build_transformer_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
#     return_keras_model=True,
#     mode = model_mode
)

NotFoundError: Key bert/embeddings/word_embeddings not found in checkpoint

在以下两个环境中都尝试了：

环境1：
keras:2.3.1
tensorflow:1.14
python:3.6

环境2：
keras:2.3.1
tensorflow:2.2
python:3.6

**Comment by bojone** [comment]
用`Transformer`类自带的`save_weights_as_checkpoint`转换
