### ISSUE TITLE
让bert4keras使用Tensorflow serving调用模型

### ISSUE THREAD

**Issue by liprais** [bojone/bert4keras#194]
用bert4keras玩了玩gpt2-ml,觉得每次生成都要重载模型太麻烦，于是试了试用tf serving给bert4keras 提供模型
https://gist.github.com/liprais/78ef34ac0779fb6b604eae044d789f90

## 1. 把已有的模型导出成pb格式
保存的时候的INFO:tensorflow:Unsupported signature for serialization貌似不用管
```python
import os
os.environ['TF_KERAS'] = '1'
import numpy as np
from bert4keras.backend import K as K
from bert4keras.models import build_transformer_model
from bert4keras.tokenizers import Tokenizer
from bert4keras.snippets import AutoRegressiveDecoder
from keras.models import load_model
import tensorflow as tf
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()
model = 'gptml.h5'
base = '/Volumes/Untitled/pb'
keras_model = load_model(model,compile=False)
keras_model.save(base + '/150k/1',save_format='tf') # <====注意model path里面的1是代表版本号，必须有这个不然tf serving 会报找不到可以serve的model
```

## 2. 用docker启动server
```shell
docker run -p 8501:8501 --mount type=bind,source=/Volumes/Untitled/pb/150k/,target=/models/my_model -e MODEL_NAME=my_model -t tensorflow/serving
```
在这个页面查看模型的元数据:
http://localhost:8501/v1/models/my_model/metadata
inputs后面的就是api要求的参数
```
"inputs": { "Input-Token": { "dtype": "DT_FLOAT","tensor_shape": {"dim": [{"size": "-1","name": ""},{"size": "-1","name": ""}],"unknown_rank": false},"name": "serving_default_Input-Token:0"}}
```
或者不用docker的话，在ubuntu上可以这样：先安装tensorflow_model_server，然后执行命令:
```
tensorflow_model_server --model_base_path="/Volumes/Untitled/pb/150k" --rest_api_port=8501 --model_name="my_model"
````

## 3.用requests调用
```python
import requests
import json
payload = [[1921,7471,5682,5023,4170,7433]] # <=== 这是tokenizer编码过的中文：天青色等烟雨
d = {"signature_name": "serving_default",
     "inputs": {"Input-Token":[[1921,7471,5682,5023,4170,7433]]}} <=== payload
r = requests.post('http://127.0.0.1:8501/v1/models/my_model:predict',json=d)
print(r.json())
```

## 4.把类修改一下，加上远程调用的方法

以 https://github.com/bojone/bert4keras/blob/master/examples/basic_language_model_gpt2_ml.py 为例子
先依赖requests 和 numpy 

```python
import requests 
import numpy
class ArticleCompletion(AutoRegressiveDecoder):
    """基于随机采样的文章续写
    """
    @AutoRegressiveDecoder.wraps(default_rtype='probas')
    def predict(self, inputs, output_ids, states):
        token_ids = np.concatenate([inputs[0], output_ids], 1)
        return model.predict(token_ids)[:, -1]

    def generate(self, text, n=1, topk=5):
        token_ids, _ = tokenizer.encode(text)
        results = self.random_sample([token_ids], n, topk)  # 基于随机采样
        return [text + tokenizer.decode(ids) for ids in results]
       
    def remote_call(self,token_ids):
        payload = token_ids.tolist()
        d = {"signature_name": "serving_default","inputs": {"Input-Token":payload}}
        r = requests.post('http://127.0.0.1:8501/v1/models/my_model:predict',json=d)
        return numpy.array(r.json()['outputs'])
```

然后就可以跑了
班门弄斧，献丑了

**Comment by bojone** [comment]
感谢提供。

我重新编辑了一下格式，麻烦你检查一下有没有编辑错误？

**Comment by liprais** [comment]
> 感谢提供。
> 
> 我重新编辑了一下格式，麻烦你检查一下有没有编辑错误？

看起来是没有的,LGTM

**Comment by wulikai1993** [comment]
> ```python
> model = 'gptml.h5'
> ```

这个模型是用tf.keras保存好的吗？所以是先保存了h5，又保存了savedmodel？
请问能不能提供savedmodel文件，我的机器加载不出来这个模型，但是现在需要使用tf serving 做推理服务。
十分感谢！

**Comment by GregoryZeng** [comment]
步骤4 我有点不明白：请问新加入的 remote_call 是怎么被调用的呢？现在调用 generate 还是继续使用 keras 的 predict 吧？

**Comment by liprais** [comment]
@GregoryZeng 
步骤四应该是把predict的方法改成这样:
    def predict(self, inputs, output_ids, states):
        token_ids = np.concatenate([inputs[0], output_ids], 1)
        model_output = self.remote_call(token_ids)
        return model_output[:, -1]

**Comment by GregoryZeng** [comment]
> @GregoryZeng
> 步骤四应该是把predict的方法改成这样:
> def predict(self, inputs, output_ids, states):
> token_ids = np.concatenate([inputs[0], output_ids], 1)
> model_output = self.remote_call(token_ids)
> return model_output[:, -1]

多谢回答~

**Comment by lonngxiang** [comment]
tf 1.X好像操作不支持

**Comment by Vanpesy** [comment]
> tf 1.X好像操作不支持

基于tf2.0

**Comment by lonngxiang** [comment]
@liprais 第4步下predict函数的model应该也是用的tf serving吧，那这里的model应该也是调用remote_call函数获取吧

**Comment by liprais** [comment]
是的，我已经改过来了

dragon10 ***@***.***> 于2021年6月24日周四 下午3:00写道：

**Comment by zhangAlwin** [comment]
有没有用人试过T5的model做tf-serving的，报error：ValueError: Unknown layer: CrossEntropy
