### ISSUE TITLE
请问下之后会兼容外语版BERT相关模型吗

### ISSUE THREAD

**Issue by renxingkai** [bojone/bert4keras#196]
比如huggingface后面发布的很多模型的词表不再是vocab.txt格式，例如英文版的robert词表包含merges.txt、vocab.json等，想问下苏神之后会兼容更多的模型吗？
感觉目前只支持含有vocab.txt的BERT模型

**Comment by bojone** [comment]
你这问题提得就不对，难道vocab.txt格式的没有英文版的吗？

实现的时候并没有专门区分中文还是英文版，examples以中文为主，如果有对应的英文模型也可以加载。只不过pytorch训练出来的模型，没时间去一一支持～

**Comment by renxingkai** [comment]
嗯嗯，明白了，感谢苏神
