### ISSUE TITLE
load_model 时候 ValueError: Unknown optimizer: AdamLR

### ISSUE THREAD

**Issue by liuchenbaidu** [bojone/bert4keras#204]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: ubuntu
- 你使用的**Python**版本: 3.6
- 你使用的**Tensorflow**版本: 1.15.3
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.8.1
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:albert

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```
python 3.6
bert4keras 0.8.1
model.save("test.h5", overwrite=True, include_optimizer=True)
然后load_model时候出现
ValueError: Unknown optimizer: AdamLR
### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
AdamLR = extend_with_piecewise_linear_lr(Adam, name='AdamLR')
优化器这样声明了。

**Comment by liprais** [comment]
load_model(h5,compile=False) ?

**Comment by liuchenbaidu** [comment]
> load_model(h5,compile=False) ?

https://github.com/bojone/bert4keras/issues/48
load_model("test.h5"）

**Comment by bojone** [comment]
那你通过custom_objects把它传进去试试。

**Comment by liuchenbaidu** [comment]
> 那你通过custom_objects把它传进去试试。

model.save("test.h5", overwrite=True, include_optimizer=False)这样保存了
然后
load_model("test.h5"）
这样就可以成功load，但是不知道这样是不是有隐患？
