### ISSUE TITLE
中文NER如何去除CRF层？

### ISSUE THREAD

**Issue by foreverxujiahuan** [bojone/bert4keras#205]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Tensorflow**版本: 
- 你使用的**Keras**版本: 
- 你使用的**bert4keras**版本: 
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by bojone** [comment]
不加上crf层就去除了crf层。

**Comment by foreverxujiahuan** [comment]
是不是还需要修改损失函数啊------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;苏剑林(Jianlin&amp;nbsp;Su)&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月31日(星期一) 下午3:42
收件人:&nbsp;&quot;bojone/bert4keras&quot;<bert4keras@noreply.github.com&gt;;
抄送:&nbsp;&quot;zzulixjh&quot;<894463634@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bojone/bert4keras] 中文NER如何去除CRF层？ (#205)

**Comment by bojone** [comment]
> 是不是还需要修改损失函数啊

难道这不是显然成立的？
