### ISSUE TITLE
对keras版本的限定将会导致与其他中间库的冲突(bert4keras与bert_xlnet)

### ISSUE THREAD

**Issue by 1148330040** [bojone/bert4keras#210]
1: 在上周我是用bert_keras用于建立一个xlnet模型, 成功训练
2: 在本周我用bert4keras建立albert模型, 成功训练
3: 当我重新调试xlnet模型的时候出错了, 此时的xlnet出错的原因是bert_xlnet的Extract()层没有将数据从三维变为二维
4: 模型最后的层对数据的处理是以句子的单词为维度编码即(None, 30, 768)而并不是(None, 768), 30是我先定的句子编码填充长度
albert和xlnet两者之间一直有一个会出错, 直到我发现了:
"ERROR: bert4keras 0.8.7 has requirement keras<=2.3.1, but you'll have keras 2.4.3 which is incompatible."
"ERROR: keras-bert 0.86.0 has requirement Keras>=2.4.3, but you'll have keras 2.3.1 which is incompatible."
信息提示bert4keras要求keras<=2.3.1 但是keras_bert要求keras>=2.4.3
我卸载了keras_bert重新安装了一遍bert_xlnet此时 keras==2.4.3, 理所当然的xlnet正确运行了.
当我以为albert将失败的时候(因为bert4keras要求keras版本<=2.3.1, 且albert是以此为基础设计的)
但是! 它并没有! 反而在keras==2.4.3的时候正确运行了代码, 并没有想象中的错误与失败.

也就是说bert4keras对keras版本的限制在这种情况下, 是多余的.

因此我觉得尊敬的作者大佬将keras的版本限制在2.3.1的选择并不是要一个好的选择.

虽然同是使用xlnet和albert的情况并不多, 但是我相信, 当前一些调度bert类型的模型的时候, 对keras版本于有要求的应该不在少数(诸如keras_xlnet,keras_bert等)
当然我不确定我的发现是不是只是限于我自己的这种情况.

不过, 在经历了一天的debug之后, 我觉得还是有必要在这里提醒下,
说不定我就对这个优秀的中间库做出了一丢丢的小贡献呢, 哈哈

python版本是 3.7
TensorFlow版本是 2.3.0
(正是因为我重新下载了TensorFlow以及keras_xlnet和bert4keras才发现的这个问题)

**Comment by bojone** [comment]
keras-bert居然限制2.4.3了，真无语。

情况是这样的：真正的keras的版本其实不超过2.3.1，而keras 2.4.3基本上完全等价于tf.keras，而keras跟tf.keras有质的区别，所以按照我的观点，如果你用keras，那么请用不超过2.3.1的版本，如果你用keras 2.4.3版本，倒不如直接用tf.keras，bert4keras本身也可以用tf.keras模式运行。

此外，事实上bert4keras应该也能在keras 2.4.3运行的，还是那句话，显式声明不超过2.3.1，只是为了让bert4keras能识别“真正的keras”、“tf.keras”以及“披着keras的皮实际上是tf.keras的keras”。

最后，鉴于这个需求，后期作者可能会考虑把xlnet也适配到bert4keras里边，这样也许就不存在这个需求了。

**Comment by 1148330040** [comment]
> keras-bert居然限制2.4.3了，真无语。
> 
> 情况是这样的：真正的keras的版本其实不超过2.3.1，而keras 2.4.3基本上完全等价于tf.keras，而keras跟tf.keras有质的区别，所以按照我的观点，如果你用keras，那么请用不超过2.3.1的版本，如果你用keras 2.4.3版本，倒不如直接用tf.keras，bert4keras本身也可以用tf.keras模式运行。
> 
> 此外，事实上bert4keras应该也能在keras 2.4.3运行的，还是那句话，显式声明不超过2.3.1，只是为了让bert4keras能识别“真正的keras”、“tf.keras”以及“披着keras的皮实际上是tf.keras的keras”。
> 
> 最后，鉴于这个需求，后期作者可能会考虑把xlnet也适配到bert4keras里边，这样也许就不存在这个需求了。

哇!, 作者大佬竟然回复我了, 而且貌似我的建议还是有点用!! 嘿嘿,.
首先 bert4keras 可以在keras 2.4.3上面使用.
至于使用tf.keras设计, 抱歉, 我水平不够, 尝试的都失败了, 层与层之间的衔接以及使用tf调模型, 我办不到, 所以说就没办法测试了.

我之前有尝试过将模型通过transformer在tf和torch下面使用梯度计算的形式进行微调, 但是由于本人技术太差,
在keras/torch/tf.keras下面作的梯度计算, 要么效果不好, 要么层与层之间的衔接出现问题. 
之前对bert, xlnet, albert作的梯度计算除了bert在tf下的微调比较成功之外, xlnet在torch下面的微调以及albert在tf下的微调, 同一批数据, 训练到最后和开始没有区别, 就感觉优化器是个摆设没有作用.
我本人技术员又不够, 所以很依赖transformer的调度, transformer又大多基于torch.
所以说如果有个新的基于tf的能将多数bert模型适配的调度库(bert4keras), 那么对于大多数像我这样的菜鸟就太好了.
最后对这个项目报以最大的敬意和谢意!
