### ISSUE TITLE
请教一下，关于recompute_grad的实现问题

### ISSUE THREAD

**Issue by pandaczm** [bojone/bert4keras#213]
大神，你好。关于recompute_grad, 你在定义前向计算的时候：

```
 if is_tf_keras:
    with tape.stop_recording():
            outputs = kernel_call()
            outputs = tf.identity(outputs)
 else:
    outputs = kernel_call()
```
这一步如果是tf.keras, 是不是只能在tf2.0才能有效果啊，tf1.x版本为啥没法使用呢？
如果是keras的话，它是默认stop_record中间输出吗？

**Comment by bojone** [comment]
https://kexue.fm/archives/7367

这里已经说明了支持/不支持的组合了。

**Comment by pandaczm** [comment]
求问一下，为什么单独用tf1.x版本，没法使用啊？

**Comment by bojone** [comment]
它就是不能用啊，我有什么办法......

这recompute的代码也不是完全我自己开发的，我也不能特别很好理解它的原理。

**Comment by pandaczm** [comment]
多谢大神了！
