### ISSUE TITLE
gpt2 的生成结果很差

### ISSUE THREAD

**Issue by wulikai1993** [bojone/bert4keras#215]
- 你使用的**操作系统**: linux
- 你使用的**Python**版本: 3.7
- 你使用的**Tensorflow**版本: 2.3.0-gpu
- 你使用的**bert4keras**版本: 0.8.7
- 你使用纯**keras**还是**tf.keras**: tf.keras

生成结果如下，有非常多的重复句子。使用的https://github.com/bojone/bert4keras/blob/master/examples/basic_language_model_gpt2_ml.py
模型下载使用的这篇文章中的百度网盘地址 https://kexue.fm/archives/7292/comment-page-1#comments  已经校验过模型的sha256值是对的。
```bash
['双十一是淘宝的狂欢节，各大电商也都在这一天做大动作。双十一，你想要的，我都有。双十一，你想要的，我都有。这个日子，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。双十一是淘宝的狂欢节，你想要的，我都有。双十一这天，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。这个日子，我们都是淘宝的狂欢节，你想要的，我都有。这个日子，我们都是淘宝的粉。双十一这天，我们都是淘宝的狂欢节，你想要的，我都有。这个日子，我们都是淘宝的狂欢节，你想']
['今天天气不错，我们出去玩吧，我想去看看你。我想和你一起看日落。我想和你一起看星星。我想和你一起看海。我想和你一起去听音乐会。我想和你一起看电影。我想和你一起去吃好吃的。我想和你一起去爬山。我想和你一起散步。我想和你一起散步。我想和你一起去看海。我想和你一起去看日落。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我们去哪里玩吧。我想和你一起散步，我想和你一起散步。我们去哪里玩呢？我想和你一']
['双十一买了个电子琴，然后发现这个东西是骗人的，不能用。然后我发现我们这里有个琴行，我就去问了问，老板说，他们这里卖的是电吉他，不能用。我问他这是什么，他说是电子音响。我说，那他们卖的电子琴是什么？他说，这个是电子琴，电子琴不能用。我说，那他们卖的是什么？他说，电子琴，电子琴不能用。我说，那他们卖的电子琴不是电子琴吗？他说，不是的，是电子琴。我问，那他们卖的电子琴是什么？他说，是电子琴，电子琴不能用。我说，那他们卖的电子琴是电子琴，电子琴不能用。然后我去问了他，他说，这个电子琴是电子琴，电子琴不能用。我问，那他们卖']
```

**Comment by bojone** [comment]
文本生成中出现重复解码现象是很常见的事情，gpt2也不例外，重复跑会得到不同的输出结果，其中应该也有一些好的case吧。

你这个输出结果表明你已经成功跑起了这个例子，剩下的只能是模型本身或者解码算法的问题了，已经不是bert4keras的问题了～

**Comment by wulikai1993** [comment]
是的，多试几次会有比较好的结果。

**Comment by xhw205** [comment]
想问一下,既然是加载的GPT-2的预训练模型。为什么每次生成的文本还不一样呢

**Comment by luyifanlu** [comment]
为了多样性，会在排名靠前随机选取的。

**Comment by luyifanlu** [comment]
> * 你使用的**操作系统**: linux
> * 你使用的**Python**版本: 3.7
> * 你使用的**Tensorflow**版本: 2.3.0-gpu
> * 你使用的**bert4keras**版本: 0.8.7
> * 你使用纯**keras**还是**tf.keras**: tf.keras
> 
> 生成结果如下，有非常多的重复句子。使用的https://github.com/bojone/bert4keras/blob/master/examples/basic_language_model_gpt2_ml.py
> 模型下载使用的这篇文章中的百度网盘地址 https://kexue.fm/archives/7292/comment-page-1#comments 已经校验过模型的sha256值是对的。
> 
> ```shell
> ['双十一是淘宝的狂欢节，各大电商也都在这一天做大动作。双十一，你想要的，我都有。双十一，你想要的，我都有。这个日子，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。双十一是淘宝的狂欢节，你想要的，我都有。双十一这天，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。双十一这天，我们都是淘宝的粉。这个日子，我们都是淘宝的狂欢节，你想要的，我都有。这个日子，我们都是淘宝的粉。双十一这天，我们都是淘宝的狂欢节，你想要的，我都有。这个日子，我们都是淘宝的狂欢节，你想']
> ['今天天气不错，我们出去玩吧，我想去看看你。我想和你一起看日落。我想和你一起看星星。我想和你一起看海。我想和你一起去听音乐会。我想和你一起看电影。我想和你一起去吃好吃的。我想和你一起去爬山。我想和你一起散步。我想和你一起散步。我想和你一起去看海。我想和你一起去看日落。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我想和你一起散步。我们去哪里玩吧。我想和你一起散步，我想和你一起散步。我们去哪里玩呢？我想和你一']
> ['双十一买了个电子琴，然后发现这个东西是骗人的，不能用。然后我发现我们这里有个琴行，我就去问了问，老板说，他们这里卖的是电吉他，不能用。我问他这是什么，他说是电子音响。我说，那他们卖的电子琴是什么？他说，这个是电子琴，电子琴不能用。我说，那他们卖的是什么？他说，电子琴，电子琴不能用。我说，那他们卖的电子琴不是电子琴吗？他说，不是的，是电子琴。我问，那他们卖的电子琴是什么？他说，是电子琴，电子琴不能用。我说，那他们卖的电子琴是电子琴，电子琴不能用。然后我去问了他，他说，这个电子琴是电子琴，电子琴不能用。我问，那他们卖']
> ```

可以用gpu吗，我使用和你相同 版本库出现 AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'
