### ISSUE TITLE
bert4keras支持载入自定义的【unused*】token吗？

### ISSUE THREAD

**Issue by yulightnight** [bojone/bert4keras#216]
苏神您好：
因为在encode和Tokenizer初始化时都没有发现可以载入自定义的token，因此想请教一下可以怎样实现，感谢

**Comment by bojone** [comment]
不知道你想表达什么意思，什么叫做“载入自定义的token”？

**Comment by yulightnight** [comment]
> 不知道你想表达什么意思，什么叫做“载入自定义的token”？

就是把vocab文件里面的第1-100个共100个unused*的token用起来，改成自己自定义的词，
我试过
1.直接改vocab文件没有用，
2.先引入load_dict再用load_dict初始化tokenizer也没有用

不知道是否可以改

**Comment by bojone** [comment]
> > 不知道你想表达什么意思，什么叫做“载入自定义的token”？
> 
> 就是把vocab文件里面的第1-100个共100个unused*的token用起来，改成自己自定义的词，
> 我试过
> 1.直接改vocab文件没有用，
> 2.先引入load_dict再用load_dict初始化tokenizer也没有用
> 
> 不知道是否可以改

参考这篇文章：https://kexue.fm/archives/7758

把中文词加入到词典里边也是不能分出来的，你需要用`pre_tokenize`

**Comment by yulightnight** [comment]
> > > 不知道你想表达什么意思，什么叫做“载入自定义的token”？
> > 
> > 
> > 就是把vocab文件里面的第1-100个共100个unused*的token用起来，改成自己自定义的词，
> > 我试过
> > 1.直接改vocab文件没有用，
> > 2.先引入load_dict再用load_dict初始化tokenizer也没有用
> > 不知道是否可以改
> 
> 参考这篇文章：https://kexue.fm/archives/7758
> 
> 把中文词加入到词典里边也是不能分出来的，你需要用`pre_tokenize`

感谢，升级尝试一下~
