### ISSUE TITLE
请问如果使用AutoRegressiveDecoder，是不支持batch形式的beam search吗?

### ISSUE THREAD

**Issue by moon290** [bojone/bert4keras#217]
你好，我想请教一下bert4keras的AutoRegressiveDecoder类是不支持batch形式的beam serach是吗？

**Comment by bojone** [comment]
暂时不支持。

我自己线下也是过实现batch版本的，发现并没有提速，所以就没更新上去。要实现能提速的batch版本的beam search，需要引入cache机制，整个流程全用gpu实现才行。这已经在计划中，但是还没动手（捂脸）。

**Comment by moon290** [comment]
好的，感谢你的回复~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bojone/bert4keras"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 中午11:11
收件人:&nbsp;"bojone/bert4keras"<bert4keras@noreply.github.com&gt;;
抄送:&nbsp;"luna"<865790933@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bojone/bert4keras] 请问如果使用AutoRegressiveDecoder，是不支持batch形式的beam search吗? (#217)





 
暂时不支持。
 
我自己线下也是过实现batch版本的，发现并没有提速，所以就没更新上去。要实现能提速的batch版本的beam search，需要引入cache机制，整个流程全用gpu实现才行。这已经在计划中，但是还没动手（捂脸）。

**Comment by HQH981118** [comment]
@bojone batch形式的beam search，每一个batch的推理时间会受限于最长的那一句，因此没有提速，反而会更慢是吗？（之前想动手实现后来考虑到这个问题，就没有去做）

**Comment by bojone** [comment]
> @bojone batch形式的beam search，每一个batch的推理时间会受限于最长的那一句，因此没有提速，反而会更慢是吗？（之前想动手实现后来考虑到这个问题，就没有去做）

cache才能带来提速，batch其实不能带来提速。
