### ISSUE TITLE
例子-SQuAD

### ISSUE THREAD

**Issue by xiaoqinghuang** [bojone/bert4keras#22]
后续会有关于在SQuAD上做阅读理解的例子代码吗？

**Comment by SunYanCN** [comment]
可以参考 https://github.com/tensorflow/models/tree/master/official/nlp/bert，也可以提Pull Requests。 @xiaoqinghuang

**Comment by xiaoqinghuang** [comment]
看了你的"玩转Keras之Seq2Seq自动生成标题"（UNILM思想），是不是可以直接将数据集改成SQuAD,测试下EM,F1是多少？

**Comment by bojone** [comment]
至少很长一段时间内不会有。因为我这里的demo以中文任务优先。
