### ISSUE TITLE
tokenizer分词器无法将special token切开

### ISSUE THREAD

**Issue by bestpredicts** [bojone/bert4keras#223]
![image](https://user-images.githubusercontent.com/12403152/94444490-f3d02400-01d8-11eb-903c-2f2f5241fead.png)

上面是bert4keras的tokenizer他将句子里面的[SEP] 切出来是[ S E P ] 四个字符了 我理解应该是直接把  [SEP]  当作一个单词切开来才是合理的 

我看了一下transformers里面的方法是可以将句子里面的special token切开

’‘’
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True, additional_special_tokens = ["[UNK]", "[SEP]", "[PAD]", "[CLS]", "[MASK]", "[ANS]", "[QBODY]"])

text = "[CLS] Who was Jim Henson ? [QBODY] [ANS] Jim Henson was a puppeteer [SEP]"
tokenized_text = tokenizer.tokenize(text)
#outputs
print(tokenized_text)
#['[CLS]', 'who', 'was', 'jim', 'henson', '?', '[ANS]', '[QBODY]', 'jim', 'henson', 'was', 'a', 'puppet', '##eer', '[SEP]']
‘’‘

**Comment by bojone** [comment]
按照官方BERT的Tokenizer实现，本就不会特殊处理special token。

而且像transformers那样强行添加规则去切分也是不科学的，因为你没法区分它究竟真的是special token还是普通的文本。

所以special token应该人为地插入，而不是当作文本来处理。
