### ISSUE TITLE
如何实现将载入预训练权重的bert模型作为一个层，循环处理多个输入

### ISSUE THREAD

**Issue by zh-mars** [bojone/bert4keras#226]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本:3.7 
- 你使用的**Tensorflow**版本:1.14.0 
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本:0.8.8
- 你使用纯**keras**还是**tf.keras**:纯keras 
- 你加载的**预训练模型**:albert_tiny_google_zh_489k

### 核心代码
bert = build_transformer_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
    model='albert',
    return_keras_model=False,
)
t_in1 = Input(shape=(128,))
s_in1 = Input(shape=(128,))
t_in2 = Input(shape=(128,))
s_in2 = Input(shape=(128,))
out1 = bert([t_in1,s_in1])
out2 = bert([t_in2,s_in2])
out1 = Lambda(lambda x: x[:, 0], name='CLS-token')(out1)
out2 = Lambda(lambda x: x[:, 0], name='CLS-token')(out2)
out = Concatenate()([out1, out2])
out = Dense(
        unts=2,
        activation='sigmoid',
        kernel_initializer=bert.initializer)
model = Model([t_in1,s_in1,t_in2,s_in2],out)
print(model.summary())

### 输出信息
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-305e88f72c44> in <module>
     38 t_in2 = Input(shape=(128,))
     39 s_in2 = Input(shape=(128,))
---> 40 out1 = bert([t_in1,s_in1])
     41 out2 = bert([t_in2,s_in2])
     42 out1 = Lambda(lambda x: x[:, 0], name='CLS-token')(out1)

TypeError: 'ALBERT' object is not callable

### 自我尝试
希望用albert处理长文本（最长超过512个字），尝试按maxlen=512把长文本分为若干段，每段用相同的bert模型处理提取特征，在融合。尝试把载入预训练权重的albert作为一个中间层去处理数据，类似Lambda(x;albert)(input)，不成功

**Comment by zh-mars** [comment]
载入权重后模型类型是bert4keras.models.ALBERT，不是keras模型，将载入部分“return_keras_model”设为True后可实现ALBERT模型复用从而实现长文本分段循环处理，模型复用写法参考了这篇文章 https://kexue.fm/archives/6985

**Comment by ExpressGit** [comment]
```
bert = build_transformer_model(
    config_path=albert_config_path,
    checkpoint_path=albert_checkpoint_path,
    model='albert',
    return_keras_model=True
)

```
sentence_1_bert_output = bert([sequence_1_token_ids, sequence_1_segment_ids])

错误提示：
AttributeError: 'Node' object has no attribute 'output_masks'
