### ISSUE TITLE
up主，在pretraining,py为什么会用到mlm_acc_loss和mlm_loss_loss两个loss

### ISSUE THREAD

**Issue by pikaqqqqqq** [bojone/bert4keras#227]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Tensorflow**版本: 
- 你使用的**Keras**版本: 
- 你使用的**bert4keras**版本: 
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by pikaqqqqqq** [comment]
![image](https://user-images.githubusercontent.com/20340136/96117545-37d75e80-0f25-11eb-8695-729afc00068f.png)
mlm_acc_loss在变高然后保持在0.9左右
mlm_loss_loss在一直变低
深度学习的模型我不太会debug所以 所以没太看明白 可以解释一下吗？ 或者可以告诉我去哪里可以查到相关知识，谢谢

**Comment by HQH981118** [comment]
很显然，第一个是mlm_acc，第二个是mlm_loss。

**Comment by pikaqqqqqq** [comment]
> 很显然，第一个是mlm_acc，第二个是mlm_loss。

确实是mlm_acc和mlm_loss 但是我不太明白为啥要一起用来计算总的loss 然后用来更新神经网络

**Comment by bojone** [comment]
> > 很显然，第一个是mlm_acc，第二个是mlm_loss。
> 
> 确实是mlm_acc和mlm_loss 但是我不太明白为啥要一起用来计算总的loss 然后用来更新神经网络

这只是一种实现方式，目的是在训练过程中显示一下mlm_acc，mlm_acc并没有用来更新神经网络（参考stop_gradient操作），它的梯度为0。

**Comment by pikaqqqqqq** [comment]
> > > 很显然，第一个是mlm_acc，第二个是mlm_loss。
> > 
> > 
> > 确实是mlm_acc和mlm_loss 但是我不太明白为啥要一起用来计算总的loss 然后用来更新神经网络
> 
> 这只是一种实现方式，目的是在训练过程中显示一下mlm_acc，mlm_acc并没有用来更新神经网络（参考stop_gradient操作），它的梯度为0。

了解了了解了 谢谢 苏神 我去学习一下stop_gradient
