### ISSUE TITLE
NER的例子是不是有bug

### ISSUE THREAD

**Issue by bigtaor** [bojone/bert4keras#230]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: ubuntu18
- 你使用的**Python**版本: 3.6
- 你使用的**Tensorflow**版本: 1.14
- 你使用的**Keras**版本: 2.2.4
- 你使用的**bert4keras**版本: 2020.10.14号从github clone的版本
- 你使用纯**keras**还是**tf.keras**: 纯keras
- 你加载的**预训练模型**:google bert（chinese_L-12_H-768_A-12）

### **
人民日报的数据，同样的数据，同一个模型，一个是在训练的时候evaluate正常，在训练结束加载模型之后预测evaluate有问题，f1值差了好多。按理f1值是一样才对。有截图：
![1](https://user-images.githubusercontent.com/3970600/96335621-98dd6e80-10ac-11eb-86a0-89dfa6984410.png)
![2](https://user-images.githubusercontent.com/3970600/96335623-9b3fc880-10ac-11eb-97ac-f2cf39f5e9ef.png)

**Comment by bigtaor** [comment]
请大佬忽略，是我在预测的时候解码器没有加载crf层的trans

**Comment by bojone** [comment]
好的～
