### ISSUE TITLE
epochs设置10000的原因？

### ISSUE THREAD

**Issue by FankLi** [bojone/bert4keras#232]
请问，这个例子中task_seq2seq_autotitle.py，epochs为什么要设置这么大呢？

**Comment by bojone** [comment]
原因很简单，你永远不知道下一个epoch会不会更好，所以设置足够多的epoch，然后`Evaluator`会自动保存最优模型，你要是看起来觉得差不多了，自己ctrl+c就行了

**Comment by FankLi** [comment]
好的，get
