### ISSUE TITLE
task_seq2seq_autotitle.py例子执行报错

### ISSUE THREAD

**Issue by jiayalu123** [bojone/bert4keras#233]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: linux
- 你使用的**Python**版本: 3.7.6
- 你使用的**Tensorflow**版本: 1.15
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 最新
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:chinese_wwm_L-12_H-768_A-12

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```
 def __iter__(self, random=False):
        batch_token_ids, batch_segment_ids = [], []
        for is_end, txt in self.sample(random):
            text = open(txt, encoding='utf-8').read()
            text = text.split('\n')
            if len(text) > 1:
                title = text[0]
                content = '\n'.join(text[1:])
                token_ids, segment_ids = tokenizer.encode(
                    content, title, maxlen=maxlen
                )
                batch_token_ids.append(token_ids)
                batch_segment_ids.append(segment_ids)

### 输出信息
```shell
# 请在此处贴上你的调试输出
```
C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\utils\data_utils.py:718: UserWarning: An input could not be retrieved. It could be because a worker has died.We do not have any information on the lost sample.
### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
看源码，感觉生成数据有问题，应该是一个text一个文本，而一次性读取到了所有50000条数据

**Comment by jiayalu123** [comment]
已解决，输入数据得问题

**Comment by YueHenry** [comment]
您好，能请问一下您具体是怎么解决的吗，我现在也遇到了相同的问题，看了您的解决方案依旧有些困惑，不知您能否分享一下解决方案？
