### ISSUE TITLE
梯度累积的优化器的问题

### ISSUE THREAD

**Issue by jjjjohnson** [bojone/bert4keras#234]
你好， 请教一下：
根据[这里](https://github.com/bojone/bert4keras/blob/d8b8bcc0d248da091e24dcb0d8106744a0772364/bert4keras/optimizers.py#L611) 每次`get_updates `时`self.accum_grads`都会全0初始化，请问时怎么累积梯度的？
我看了一下`return accum_updates`后也没有用到这个list。
谢谢！

**Comment by jjjjohnson** [comment]
个人觉得 `self.accum_grads` 只有在`cond == 1` 时才应该0初始化，`cond == 0`时应该保留上一次计算的值。

**Comment by bojone** [comment]
请去入门一下tf，学习一下静态图、计算图这些概念，不要胡乱将python的动态编程思想套进来。`get_updates`这个函数根本不会重复执行，何来每次都全0初始化？

**Comment by jjjjohnson** [comment]
好哒 谢谢解惑！
