### ISSUE TITLE
权重滑动平均的问题

### ISSUE THREAD

**Issue by jjjjohnson** [bojone/bert4keras#236]
你好 请教一下：
为啥每次 都要初始化全0的[ema_weights](https://github.com/bojone/bert4keras/blob/d8b8bcc0d248da091e24dcb0d8106744a0772364/bert4keras/optimizers.py#L915)? 这样的话w1在update前一直是0啊。（感觉这样是不对的）

![image](https://user-images.githubusercontent.com/20569095/96719898-a1031a00-13dc-11eb-90ab-9bc381e849b4.png)
[这篇文章](https://kexue.fm/archives/6575#%E6%9D%83%E9%87%8D%E6%BB%91%E5%8A%A8%E5%B9%B3%E5%9D%87)里是init的时候才初始化全0，后续会不断更新的.

谢谢！

**Comment by bojone** [comment]
请去学习什么叫做静态图。

**Comment by jjjjohnson** [comment]
请问有什么学习 静态图 的资料吗？ 谢谢！

**Comment by bojone** [comment]
> 请问有什么学习 静态图 的资料吗？ 谢谢！

系统学习一下tf

**Comment by jjjjohnson** [comment]
谢谢解惑！
