### ISSUE TITLE
关于auto_titile的一些问题

### ISSUE THREAD

**Issue by brealisty** [bojone/bert4keras#239]
不知道为什么，苏神博客评论不了，来这里提问了😄。
一般而言，bert最大长度512，THUCnNews的数据集，文章部分基本都超过了这个限制；但是因为都是一些新闻类的文章，都会在前面部分就做一个总述，即使截断也不影响文章大致意思，因此生成的结果也会比较贴合文本意思。但是对于其他领域的文本，重心内容可能会出现在后面部分，直接做截断的话，生成的标题就容易流失关键信息。
所以，有没有行之有效的方式来处理长文本，存在的这种问题？

**Comment by bojone** [comment]
你可以用NEZHA来做，只要你显存够，不限长度。

**Comment by chenjun0210** [comment]
@bojone  苏神，请问一下可以支持多GPU跑吗？这样就可以放在多卡上跑，也能适当加大输入的长度。

**Comment by bojone** [comment]
> @bojone 苏神，请问一下可以支持多GPU跑吗？这样就可以放在多卡上跑，也能适当加大输入的长度。

目前已经支持 https://github.com/bojone/bert4keras/blob/master/examples/task_seq2seq_autotitle_multigpu.py
