### ISSUE TITLE
meet error when loading `albert_small_google_zh` weights.

### ISSUE THREAD

**Issue by enningxie** [bojone/bert4keras#24]
> tensorflow.python.framework.errors_impl.NotFoundError: Key bert/embeddings/word_embeddings_2 not found in checkpoint

**Comment by bojone** [comment]
indeed, albert_zh is not compatible with the google version of albert. The google version of albert will be supported in few time.

**Comment by bojone** [comment]
by the way, where can download albert_small_google_zh? I can not find it.

**Comment by enningxie** [comment]
https://github.com/brightmart/albert_zh

**Comment by bojone** [comment]
已经支持了，保留google版albert支持～
