### ISSUE TITLE
多输入多输出问题

### ISSUE THREAD

**Issue by wanghao0225** [bojone/bert4keras#244]
如何通过bert4keras，实现一个多输入多输出的网络架构？

**Comment by bojone** [comment]
bert4keras不能搭建其他模型，bert4keras只提供固定的keras模型。
你的问题应该通过学习keras来解决。

**Comment by wanghao0225** [comment]
SiameseBert不能通过修改您写的bert4keras实现吗？我试过一些办法，但是没调通，不知道这个思路是否正确，还请苏老师指导？

**Comment by bojone** [comment]
我不知道SiameseBert是什么，但可以基于bert4keras衍生出一些新的模型，但这不属于bert4keras范畴，这是keras问题。

> 我试过一些办法，但是没调通，不知道这个思路是否正确，还请苏老师指导？

我的意思就是你没调通缺的不是对bert4keras的了解，缺的是对keras的了解。

**Comment by wanghao0225** [comment]
可能我对keras理解的还不够透彻，以您写的句子对为例，我怎样才能修改为两个输入（每个句子分别输入模型），来分别提取每一个句子的Embedding呢？

**Comment by bojone** [comment]
https://kexue.fm/archives/4493

我不是说得很清楚了吗？你缺的是对keras的了解，所以你只需要去好好学一个月的keras不就可以达到你的目的了吗？这里问也帮不了你啊。

**Comment by chuanfanyoudong** [comment]
> 可能我对keras理解的还不够透彻，以您写的句子对为例，我怎样才能修改为两个输入（每个句子分别输入模型），来分别提取每一个句子的Embedding呢？

麻烦问一下，你这边有实现方案了吗？我也遇到类似的问题，主要是怎么把 Input作为bert的输入的问题，网上有一些参考的没有接bert，所以很容易理解了，加上bert后，不知道Input层怎么接到bert里去

**Comment by chuanfanyoudong** [comment]
> https://kexue.fm/archives/4493
> 
> 我不是说得很清楚了吗？你缺的是对keras的了解，所以你只需要去好好学一个月的keras不就可以达到你的目的了吗？这里问也帮不了你啊。

大佬，冒昧打扰您了，我也遇到这个问题了，就是bert4keras的输入和Input层对不上，折腾了好久，也没折腾明白，主要想实现类似ranknet的结构，下面两个bert模型抽取参数，然后上层利用交叉熵算相关性排序

**Comment by wanghao0225** [comment]
> 
> 
> > 可能我对keras理解的还不够透彻，以您写的句子对为例，我怎样才能修改为两个输入（每个句子分别输入模型），来分别提取每一个句子的Embedding呢？
> 
> 麻烦问一下，你这边有实现方案了吗？我也遇到类似的问题，主要是怎么把 Input作为bert的输入的问题，网上有一些参考的没有接bert，所以很容易理解了，加上bert后，不知道Input层怎么接到bert里去

我目前将Input层中的name参数去掉了，例 Input(shape=(None,), dtype=tf.dtypes.float32)，这样编译能通过，测试准确性时也没有问题，等找到更好的办法在分享；
