### ISSUE TITLE
关于pre-training的一个问题

### ISSUE THREAD

**Issue by ZRH0308** [bojone/bert4keras#247]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本:  3.7.6
- 你使用的**Tensorflow**版本:  1.15.0
- 你使用的**Keras**版本:  2.2.5
- 你使用的**bert4keras**版本: 0.9.1
- 你使用纯**keras**还是**tf.keras**:  tf-keras
- 你加载的**预训练模型**:   自研语言模型RoBERTa+ Small : https://github.com/ZhuiyiTechnology/pretrained-models，

    
    用data_utils.py和pretraining.py ，加载预训练模型，并放入自己的新语料后训练并保存为了**bert_model.ckpt**。后续在别处建立模型加载权重**model = build_transformer_model(config_path, checkpoint_path)** 的时候，
发生**NotFoundError: Key bert/embeddings/word_embeddings not found in checkpoint**错误

我用**pywrap_tensorflow.NewCheckpointReader()** 检查新的**bert_model.ckpt** ，发现它长这样。。。。请问苏老师这正常吗？

![image](https://user-images.githubusercontent.com/73865759/98217648-bbfd8e80-1f85-11eb-9fad-2b0a89f55fad.png)

**Comment by bojone** [comment]
需要通过`save_weights_as_checkpoint`方法对权重做转换。

https://github.com/bojone/bert4keras/blob/ad73f4b64f594fe017ecf4e3211cf8713d3916f7/bert4keras/models.py#L270

**Comment by ZRH0308** [comment]
> 需要通过`save_weights_as_checkpoint`方法对权重做转换。
> 
> https://github.com/bojone/bert4keras/blob/ad73f4b64f594fe017ecf4e3211cf8713d3916f7/bert4keras/models.py#L270

谢谢苏老师回复！ 请问这个映射转换应该在预训练全部完成后进行对吗？ 

那么在bert4keras/bert4keras/pretraining.py中， 我如果在`train_model.fit()`完成后运行

`bert.save_weights_as_checkpoint(model_saved_path)`    

那么我疑惑的是...我存下来的.ckpt等文件是训练后的还是训练前的？我的做法是否正确？

多有打扰 还望赐教

**Comment by bojone** [comment]
> > 需要通过`save_weights_as_checkpoint`方法对权重做转换。
> > https://github.com/bojone/bert4keras/blob/ad73f4b64f594fe017ecf4e3211cf8713d3916f7/bert4keras/models.py#L270
> 
> 谢谢苏老师回复！ 请问这个映射转换应该在预训练全部完成后进行对吗？
> 
> 那么在bert4keras/bert4keras/pretraining.py中， 我如果在`train_model.fit()`完成后运行
> 
> `bert.save_weights_as_checkpoint(model_saved_path)`
> 
> 那么我疑惑的是...我存下来的.ckpt等文件是训练后的还是训练前的？我的做法是否正确？
> 
> 多有打扰 还望赐教

自然是训练后的，要不然不就白费力气了吗～

**Comment by ZRH0308** [comment]
> > > 需要通过`save_weights_as_checkpoint`方法对权重做转换。
> > > https://github.com/bojone/bert4keras/blob/ad73f4b64f594fe017ecf4e3211cf8713d3916f7/bert4keras/models.py#L270
> > 
> > 
> > 谢谢苏老师回复！ 请问这个映射转换应该在预训练全部完成后进行对吗？
> > 那么在bert4keras/bert4keras/pretraining.py中， 我如果在`train_model.fit()`完成后运行
> > `bert.save_weights_as_checkpoint(model_saved_path)`
> > 那么我疑惑的是...我存下来的.ckpt等文件是训练后的还是训练前的？我的做法是否正确？
> > 多有打扰 还望赐教
> 
> 自然是训练后的，要不然不就白费力气了吗～

好的！我了解了，太谢谢苏老师了！！
