### ISSUE TITLE
autotitle GPU训练问题

### ISSUE THREAD

**Issue by Phoeby2618** [bojone/bert4keras#249]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的linux操作系统: 
- 你使用的Python=3.6.8版本
- 你使用的Tensorflow-gpu=1.15版本
- 你使用的Keras=2.3.1版本:
- 你使用的bert4keras=0.9.1版本:
- 你使用纯keras: 
- 你加载的预训练模型：chinese_wwn_L-12模型

### 核心代码
跑seq2seq_autotitle任务，有5张显卡，指定在第4张运行，但总是报错第2张卡溢出，2因为有别的在运行任务
os.environ['CUDA_VISIBLE_DEVICES'] = '4'

### 输出信息

unable to create StreamExecutor for CUDA:2: failed initializing StreamExecutor for CUDA device ordinal 2: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 34089730048
...
line 86, in <module>
    keep_tokens=keep_tokens,
  File "/usr/local/lib/python3.6/dist-packages/bert4keras/models.py", line 2133, in build_transformer_model
    transformer.load_weights_from_checkpoint(checkpoint_path)
  File "/usr/local/lib/python3.6/dist-packages/bert4keras/models.py", line 268, in load_weights_from_checkpoint
    K.batch_set_value(weight_value_pairs)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2960, in batch_set_value
    tf_keras_backend.batch_set_value(tuples)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3259, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 483, in get_session
    session = _get_session(op_input_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 455, in _get_session
    config=get_default_session_config())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1585, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 699, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InvalidArgumentError: device CUDA:2 not supported by XLA service
        while setting up XLA_GPU_JIT device number 2

### 自我尝试
  卸载tensorflow-gpu可在cpu运行，但gpu不行
  解决不了了，希望苏神回复，谢谢。

**Comment by bojone** [comment]
你`os.environ['CUDA_VISIBLE_DEVICES'] = '4'`这句放在哪里

**Comment by Phoeby2618** [comment]
> 你`os.environ['CUDA_VISIBLE_DEVICES'] = '4'`这句放在哪里

文件开头和__main__里面都尝试过

**Comment by bojone** [comment]
> > 你`os.environ['CUDA_VISIBLE_DEVICES'] = '4'`这句放在哪里
> 
> 文件开头和__main__里面都尝试过

确定是最顶部了？确定是在bert4keras了？

**Comment by Phoeby2618** [comment]
> > > 你`os.environ['CUDA_VISIBLE_DEVICES'] = '4'`这句放在哪里
> > 
> > 
> > 文件开头和__main__里面都尝试过
> 
> 确定是最顶部了？确定是在bert4keras之前了？
> 
> 最好的方法是`CUDA_VISIBLE_DEVICES=4 python xxxx.py`这样跑

刚尝试放到开头，可以了
之前可能在处理版本问题和修改代码的时候换了位置，但是没有考虑到这个因素
感谢感谢！！
另外，请问为什么会出现这种情况呢？因为之前有些放到main里面也是可以运行的

**Comment by bojone** [comment]
> > > > 你`os.environ['CUDA_VISIBLE_DEVICES'] = '4'`这句放在哪里
> > > 
> > > 
> > > 文件开头和__main__里面都尝试过
> > 
> > 
> > 确定是最顶部了？确定是在bert4keras之前了？
> > 最好的方法是`CUDA_VISIBLE_DEVICES=4 python xxxx.py`这样跑
> 
> 刚尝试放到开头，可以了
> 之前可能在处理版本问题和修改代码的时候换了位置，但是没有考虑到这个因素
> 感谢感谢！！
> 另外，请问为什么会出现这种情况呢？因为之前有些放到main里面也是可以运行的

tf和bert4keras要读取你这个环境变量，然后进行相应的适配，你放到后面，人家都处理完了，你给谁看呀～～

**Comment by Phoeby2618** [comment]
> > > > > 你`os.environ['CUDA_VISIBLE_DEVICES'] = '4'`这句放在哪里
> > > > 
> > > > 
> > > > 文件开头和__main__里面都尝试过
> > > 
> > > 
> > > 确定是最顶部了？确定是在bert4keras之前了？
> > > 最好的方法是`CUDA_VISIBLE_DEVICES=4 python xxxx.py`这样跑
> > 
> > 
> > 刚尝试放到开头，可以了
> > 之前可能在处理版本问题和修改代码的时候换了位置，但是没有考虑到这个因素
> > 感谢感谢！！
> > 另外，请问为什么会出现这种情况呢？因为之前有些放到main里面也是可以运行的
> 
> tf和bert4keras要读取你这个环境变量，然后进行相应的适配，你放到后面，人家都处理完了，你给谁看呀～～

突然知道了，这个例子中build_transformer_model没有放到类和函数里面，所以顺序读取的时候先执行了，是吧
太谢谢了~耽误苏神时间了，希望大佬越来越强！
