### ISSUE TITLE
triggered tf.function retracing警告导致预测速度变慢

### ISSUE THREAD

**Issue by yishuihan132** [bojone/bert4keras#250]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Windows/Linux都用过
- 你使用的**Python**版本: python=3.7
- 你使用的**Tensorflow**版本: tensorflow=2.2
- 你使用的**Keras**版本: keras=2.3.1
- 你使用的**bert4keras**版本: 最新版
- 你使用纯**keras**还是**tf.keras**: 纯keras和tf.keras都用过
- 你加载的**预训练模型**:chinese_L-12_H-768_A-12

### 核心代码
```python
bert4keras中的example中的task_sequence_labeling_ner_crf.py
```

### 输出信息
```
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000208245AE438> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

```

### 自我尝试
基于bert4keras加载bert模型，该bert模型最后一层输出形状是(None,None,768)，其中序列长度是None，本意是可以让我们动态传入序列长度，只要不超过预训练模型中的最大序列长度，但在实际预测的过程中，发现如果bert模型不一开始指定序列长度，后面在模型预测阶段会导致传入不同的序列长度时，触发triggered tf.function retracing，这个机制会严重拖慢预测速度。恳请苏老师能看一下这个问题。

**Comment by bojone** [comment]
这个问题只有在tf 2.x + tf.keras才会出现吧？按照我的测试，纯keras是不会出现的。

至于解决办法，我没找到。你可以想办法问问Google大爷为什么要引入动态图把tf 2.x搞得这么垃圾，我是爱莫能助了。

**Comment by yishuihan132** [comment]
好吧，目前通过model = build_transformer_model( config_path, checkpoint_path,sequence_length=maxlen)固定序列长度加载bert模型，在预测的时候不会触发triggered tf.function retracing警告。反正模型对padding的位置用mask进行了屏蔽，问题不大。
