### ISSUE TITLE
ner加载训练好的权重再预测时发现比训练时预测差太多，这是啥原因？

### ISSUE THREAD

**Issue by Du-XiaoJing** [bojone/bert4keras#252]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**windows**: 
- 你使用的**Python3版本: 
- 你使用的**Tensorflow2.1**版本: 
- 你使用的**Keras2.3.1**版本: 
- 你使用的**bert4keras0.8.3**版本: 
- 你使用纯**keras**: 
- 你加载的**哈工大Roberta large**:

### 核心代码
```python
model = Model(model.input, output)
model.summary()

model.compile(
    loss=CRF.sparse_loss,
    optimizer=Adam(learing_rate),
    metrics=[CRF.sparse_accuracy]
)


model.load_weights('./fold1best_model_epoch_10.weights')
```

### 输出信息
``‘
模型能正常加载进来，就是预测时有问题
训练时：
![V@ )@JAC73QVOK`FH`IRZ38](https://user-images.githubusercontent.com/67457827/99783178-0de10f80-2b55-11eb-9d2e-1d700925398b.png)
加载模型后预测：
![~5(TLRLY6JV`4(B8LH3F)}0](https://user-images.githubusercontent.com/67457827/99783271-2d783800-2b55-11eb-8b6b-800a79ed97bd.png)

```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by Du-XiaoJing** [comment]
希望苏老师能指出问题所在

**Comment by bojone** [comment]
目测转移矩阵trans没搞对吧？

**Comment by ZeKunZhang1998** [comment]
> 目测转移矩阵trans没搞对吧？

请问是不是需要在加载的时候单独加载crf的权重

**Comment by bojone** [comment]
你确认一下加载前后的trans有无变化。
我不知道你改了什么，因为按照我的原始脚本是不存在这个问题的。

**Comment by Du-XiaoJing** [comment]
> 你确认一下加载前后的trans有无变化。 我不知道你改了什么，因为按照我的原始脚本是不存在这个问题的。

好的，谢谢苏老师
