### ISSUE TITLE
模型加载出现位未知层

### ISSUE THREAD

**Issue by TuringEmmy** [bojone/bert4keras#253]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: ubuntu18.04
- 你使用的**Python**版本: 3.6
- 你使用的**Tensorflow**版本: 1.14
- 你使用的**Keras**版本: 2.3
- 你使用的**bert4keras**版本: 0.7
- 你使用纯**keras**还是**tf.keras**: Keats
- 你加载的**预训练模型**:bert

### 核心代码
```python
Load_model(“model.h5”)
```

### 输出信息
```shell
position_embedding不存在，batch_gather函数不存在
```

### 自我尝试
在调用batch_gather函数之前又导入函数，依然报错，并且存在位置自定义层

**Comment by bojone** [comment]
原因很简单：因为没认真读readme.md，也没有认真学好keras。

```python
from bert4keras.layers import *
```
