### ISSUE TITLE
BERT预训练时，GPU占用仅287M，CPU用了40个，怎么切换到使用GPU训练呢?

### ISSUE THREAD

**Issue by fengxin619** [bojone/bert4keras#254]
import os, re
os.environ['TF_KERAS'] = '1'  # 必须使用tf.keras
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
#os.environ["CUDA_VISIBLE_DEVICES"] = '1'

........

单机多卡模式
strategy = tf.contrib.distribute.MirroredStrategy()
with strategy.scope():
    train_model = build_transformer_model_for_pretraining()
    train_model.summary()

**Comment by bojone** [comment]
bert4keras只是基于keras的代码封装，keras只是基于tf的代码封装，GPU的控制不是bert4keras的事情，也不是keras的事情，而是tf的事情。

**Comment by fengxin619** [comment]
已经解决，cuda版本和tf不匹配

**Comment by MEwlj** [comment]
> 已经解决，cuda版本和tf不匹配

请问能详细说一说bert4keras用gpu加速的过程吗，之前一直用的cpu
