### ISSUE TITLE
使用pretraining保存的模型格式无法直接加载

### ISSUE THREAD

**Issue by fengxin619** [bojone/bert4keras#255]
环境配置：
tensorflow-gpu: 1.14.0
keras:2.2.4

没有使用多gpu，仅仅使用单gpu做预训练的，
```
# 单机多卡
# strategy = tf.distribute.MirroredStrategy()
# with strategy.scope():
train_model = build_transformer_model_for_pretraining()
#train_model.summary()
```

生成的checkpoint格式：
bert_model.data-00000-of-00002  
bert_model.data-00001-of-00002  
bert_model.index  
checkpoint

模型加载方式
`bert_model = build_transformer_model(config_path=Config.bert_config_path,checkpoint_path=Config.bert_ckpt_path,model='roberta') 
`

加载报错
tensorflow.python.framework.errors_impl.NotFoundError: Key bert/embeddings/word_embeddings not found in checkpoint

经过大佬鞭策和指导后有了解决方案：
```
train_model, bert = build_transformer_model_for_pretraining()
# 模型训练
train_model.fit(
    dataset,
    steps_per_epoch=steps_per_epoch,
    epochs=epochs,
    callbacks=[checkpoint, csv_logger],
)

train_model.load_weights(model_saved_path)
bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
```

**Comment by bojone** [comment]
你用save_weights保存的，自然只能用load_weights来加载。

你想用build_transformer_model加载，那就要用save_weights_as_checkpoint转换。

**Comment by fengxin619** [comment]
> 你用save_weights保存的，自然只能用load_weights来加载。
> 
> 你想用build_transformer_model加载，那就要用save_weights_as_checkpoint转换。

大佬，有demo么？

**Comment by bojone** [comment]
> > 你用save_weights保存的，自然只能用load_weights来加载。
> > 你想用build_transformer_model加载，那就要用save_weights_as_checkpoint转换。
> 
> 大佬，有demo么？

bert.save_weights_as_checkpoint()

**Comment by fengxin619** [comment]
> > > 你用save_weights保存的，自然只能用load_weights来加载。
> > > 你想用build_transformer_model加载，那就要用save_weights_as_checkpoint转换。
> > 
> > 
> > 大佬，有demo么？
> 
> bert.save_weights_as_checkpoint()


```
class ModelCheckpoint(Callback):
    def on_epoch_end(self, epoch, logs=None):
        self.model.save_weights(model_saved_path, overwrite=True, save_format='tf')

# 保存模型
checkpoint = ModelCheckpoint()

# 模型训练
train_model.fit(
    dataset,
    steps_per_epoch=steps_per_epoch,
    epochs=epochs,
    callbacks=[checkpoint, csv_logger],
)
train_model.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
```

这样好像不对？ 应该需要先加载Bert模型，load_weights，然后再用save_weights_as_checkpoint转。但是...好像只有build_transformer_model这个可以加载？

**Comment by bojone** [comment]
是bert.save_weights_as_checkpoint，不是train_model.save_weights_as_checkpoint，save_weights_as_checkpoint是bert4keras的Transformer类的方法，不是keras的Model类的方法。

你要转你已经保存好的权重，自然是要把保存好的权重加载进来呀，这还要说么～

**Comment by fengxin619** [comment]
> 是bert.save_weights_as_checkpoint，不是train_model.save_weights_as_checkpoint，save_weights_as_checkpoint是bert4keras的Transformer类的方法，不是keras的Model类的方法。
> 
> 你要转你已经保存好的权重，自然是要把保存好的权重加载进来呀，这还要说么～


```
train_model.fit(
    dataset,
    steps_per_epoch=steps_per_epoch,
    epochs=epochs,
    callbacks=[checkpoint, csv_logger],
)
config = json.load(file)
bert = BERT(vocab_size = config['vocab_size'],
        hidden_size = config['hidden_size'] 
)
bert.load_weights_from_checkpoint(model_saved_path)
bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
```

大佬，咋加载bert的权重呢？ 貌似不能直接load_weight哎，上面这样并不行...

**Comment by bojone** [comment]
> > 是bert.save_weights_as_checkpoint，不是train_model.save_weights_as_checkpoint，save_weights_as_checkpoint是bert4keras的Transformer类的方法，不是keras的Model类的方法。
> > 你要转你已经保存好的权重，自然是要把保存好的权重加载进来呀，这还要说么～
> 
> ```
> train_model.fit(
>     dataset,
>     steps_per_epoch=steps_per_epoch,
>     epochs=epochs,
>     callbacks=[checkpoint, csv_logger],
> )
> config = json.load(file)
> bert = BERT(vocab_size = config['vocab_size'],
>         hidden_size = config['hidden_size'] 
> )
> bert.load_weights_from_checkpoint(model_saved_path)
> bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
> ```
> 
> 大佬，咋加载bert的权重呢？ 貌似不能直接load_weight哎，上面这样并不行...

我说了用load_weights加载权重啊，你搞个load_weights_from_checkpoint干嘛呢？你用train_model.save_weights保存的权重，那就用train_model.load_weights加载啊，这不是keras的常识吗～

**Comment by fengxin619** [comment]
> 
> 我说了用load_weights加载权重啊，你搞个load_weights_from_checkpoint干嘛呢？你用train_model.save_weights保存的权重，那就用train_model.load_weights加载啊，这不是keras的常识吗～
> 
> ```python
> train_model.load_weights(model_saved_path)  # keras常识
> bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
> ```

train_model和bert在这段代码中分别是两个模型，用train_model.load_weights之后，再用bert.save_weights_as_checkpoint应该不能保存...我就比较疑惑这个该怎么做，bert又不能直接load_weights..

**Comment by bojone** [comment]
> > 我说了用load_weights加载权重啊，你搞个load_weights_from_checkpoint干嘛呢？你用train_model.save_weights保存的权重，那就用train_model.load_weights加载啊，这不是keras的常识吗～
> > ```python
> > train_model.load_weights(model_saved_path)  # keras常识
> > bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
> > ```
> 
> train_model和bert在这段代码中分别是两个模型，用train_model.load_weights之后，再用bert.save_weights_as_checkpoint应该不能保存...我就比较疑惑这个该怎么做，bert又不能直接load_weights.. (让大佬见笑了😆)

train_model和bert怎么就“分别是两个模型”了？bert只不过是对train_model做了包装一下。bert的任何操作实际上都是对train_model进行的。

都搞预训练了，这些疑问是不是应该通过阅读源码来解决比较好呢？

**Comment by fengxin619** [comment]
> train_model和bert怎么就“分别是两个模型”了？bert只不过是对train_model做了包装一下。bert的任何操作实际上都是对train_model进行的。
> 
> 都搞预训练了，这些疑问是不是应该通过阅读源码来解决比较好呢？

bert和train_model是两个实例/图，bert也是我new出来的，源码里面也木有save_weights_as_checkpoint的用法😿
```
train_model = build_transformer_model_for_pretraining()

bert = BERT(vocab_size = config['vocab_size'],
        hidden_size = config['hidden_size'] 
)
```

**Comment by bojone** [comment]
爷，[pretraining.py](https://github.com/bojone/bert4keras/blob/master/pretraining/pretraining.py)好好的，你干嘛要自己搞一个对象啊.................

直接在`train_model.fit`之前把下面两句代码插进去不就行了吗...为什么这么简单的事情能想得这么复杂...
```python
train_model.load_weights(model_saved_path)
bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
```

**Comment by fengxin619** [comment]
> 爷，[pretraining.py](https://github.com/bojone/bert4keras/blob/master/pretraining/pretraining.py)好好的，你干嘛要自己搞一个对象啊.................
> 
> 直接在`train_model.fit`之前把下面两句代码插进去不就行了吗...为什么这么简单的事情能想得这么复杂...
> 
> ```python
> train_model.load_weights(model_saved_path)
> bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
> ```

but...并没有bert啊，bert哪来呢？

**Comment by bojone** [comment]
> > 爷，[pretraining.py](https://github.com/bojone/bert4keras/blob/master/pretraining/pretraining.py)好好的，你干嘛要自己搞一个对象啊.................
> > 直接在`train_model.fit`之前把下面两句代码插进去不就行了吗...为什么这么简单的事情能想得这么复杂...
> > ```python
> > train_model.load_weights(model_saved_path)
> > bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
> > ```
> 
> but...并没有bert啊，bert哪来呢？ 这个名字在pretraining中木有..所以我只能new一个

你在网页command+f查找一下是不是真的没有bert这个东西再说吧。

**Comment by fengxin619** [comment]
> > > 爷，[pretraining.py](https://github.com/bojone/bert4keras/blob/master/pretraining/pretraining.py)好好的，你干嘛要自己搞一个对象啊.................
> > > 直接在`train_model.fit`之前把下面两句代码插进去不就行了吗...为什么这么简单的事情能想得这么复杂...
> > > ```python
> > > train_model.load_weights(model_saved_path)
> > > bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
> > > ```
> > 
> > 
> > but...并没有bert啊，bert哪来呢？ 这个名字在pretraining中木有..所以我只能new一个
> 
> 你在网页command+f查找一下是不是真的没有bert这个东西再说吧。

大佬我错了，我不该乱改代码...我找到了... (汗颜😸)

**Comment by lonngxiang** [comment]
> 爷，[pretraining.py](https://github.com/bojone/bert4keras/blob/master/pretraining/pretraining.py)好好的，你干嘛要自己搞一个对象啊.................
> 
> 直接在[pretraining.py](https://github.com/bojone/bert4keras/blob/master/pretraining/pretraining.py)里边在`train_model.fit`之前把下面两句代码插进去不就行了吗...为什么这么简单的事情能想得这么复杂...
> 
> ```python
> train_model.load_weights(model_saved_path)
> bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt')
> ```

麻烦问下这里好像说的是  https://github.com/bojone/bert4keras/issues/247   bert.save_weights_as_checkpoint(filename='bert_model/bert_model.ckpt') 放在`train_model.fit`之后

**Comment by DJofOUC** [comment]
学习到了
