### ISSUE TITLE
大于两个segment在tokenize时, segment_id的生成问题

### ISSUE THREAD

**Issue by garnetow** [bojone/bert4keras#266]
苏神好, 最近在做的一个task, 需要输入三个segment, 在tokenize的获得segment_id的时候, 有些疑惑.
使用的模型是roberta, 对应的是标准的Tokenizer. 我设想了几种方案:

1. segment对应标注为0, 1, 2. 但预训练参数里segment embedding的大小为2, 这样就不能使用对应的这部分预训练权重了, 只能初始化重新训练
2. 按0, 1, 0, 1, ...  交替标注, 只需要改写下Tokenizer就好. 不知道有没有一些负作用.
3. 将其中的两个相邻的segment合并成一个segment, 中间使用[SEP]或自定义token(例如[SPLIT])来分隔. 直觉上感觉会损失信息.

搜索到有人也遇到过这种情况, 但没有看到相关的方案. 请问苏神有遇到过这种情况吗, 能不能给些建议~, 感谢.
我个人偏向使用第二种方案, 也会先按这种方案实践下

**Comment by bojone** [comment]
其实我没看懂你两种方案在说啥...

至于第一种方案，如果你的segment总数大于2，那么你可以不加载segment embedding的权重，只加载剩下部分的，这只需要稍微修改一下bert4keras的源码。

**Comment by garnetow** [comment]
使用第三种方案解决, 效果还不错
