### ISSUE TITLE
0.2.4 fine tune 问题

### ISSUE THREAD

**Issue by erichen510** [bojone/bert4keras#27]
bert4keras 0.2.4 
Kears 2.3.1
模型代码：
```
albert_model = build_bert_model(config_path, checkpoint_path, albert=True)
out = Lambda(lambda x: x[: 0])(albert_model.output)
output = Dense(units=class_num, activation = 'softmax')(out)

model = Model(albert_model.input, output)
mdel.compile(loss = model_loss, optimizer = optimizer, metrics=["categorical_accuracy"]
```
模型使用keras的 model.save保存 使用 load_model加载

```
from bert4keras.layers import *
model = load_model(os.path.join(model_dir, "albert.m"))
```
报错
```
ValueError: Unkown layer : PositionEmbedding
```
如果 from bert4keras.layers import  custom_object
之后
```
model = load_model(os.path.join(model_dir, "albert.m"), custom_object=custom_object)
```
报错
```
AttributeError: 'tuple' object has no attribute 'layer'
```

**Comment by erichen510** [comment]
使用模型
![image](https://user-images.githubusercontent.com/16681583/68263388-dd7d1f00-0080-11ea-9545-d42aebc9419c.png)

**Comment by erichen510** [comment]
我看了 别的项目的issue 

https://github.com/BrikerMan/Kashgari/issues/152#issuecomment-511799207

我有一段配置代码是 os.environ["TF_KERAS"] = "1"

**Comment by erichen510** [comment]
albert模型 loss是  categorical_crossentropy 然后用的keras是2.3.1 没有用tensorflow.keras

**Comment by bojone** [comment]
不用tf.keras请不要配置os.environ["TF_KERAS"] = "1"

**Comment by CoSeCant-csc** [comment]
> 不用tf.keras请不要配置os.environ["TF_KERAS"] = "1"

请问下 bert4keras 是可以用 tf.keras 的么还是只能原生keras

**Comment by bojone** [comment]
@CoSeCant-csc 都可以，用tf.keras则配置环境变量TF_KERAS=1，否则不用配置

**Comment by erichen510** [comment]
这个问题已得到解决。

> 不用tf.keras请不要配置os.environ["TF_KERAS"] = "1"
如果没有训练和预测使用的keras不同 会出现 AttributeError
