### ISSUE TITLE
加载gpt2_ml运行报错IndexError: Read less bytes than requested

### ISSUE THREAD

**Issue by hurun** [bojone/bert4keras#270]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: linux
- 你使用的**Python**版本: 3.6
- 你使用的**Tensorflow**版本: 2.3.1
- 你使用的**Keras**版本: 2.4.3
- 你使用的**bert4keras**版本: 0.9.1
- 你使用纯**keras**还是**tf.keras**: keras
- 你加载的**预训练模型**:gpt2_ml

### 核心代码
```python

model = build_transformer_model(
    config_path=config_path, checkpoint_path=checkpoint_path, model='gpt2_ml'
)  # 建立模型，加载权重
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```
IndexError                                Traceback (most recent call last)
<ipython-input-10-79f0601d3e87> in <module>()
      1 model = build_transformer_model(
----> 2     config_path=config_path, checkpoint_path=checkpoint_path, model='gpt2_ml'
      3 )  # 建立模型，加载权重

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/py_checkpoint_reader.py in get_tensor(self, tensor_str)
     68   try:
     69     return CheckpointReader.CheckpointReader_GetTensor(
---> 70         self, compat.as_bytes(tensor_str))
     71   # TODO(b/143319754): Remove the RuntimeError casting logic once we resolve the
     72   # issue with throwing python exceptions from C++.

IndexError: Read less bytes than requested
### 输出信息
```shell
尝试了gpu、tpu、cpu运行环境，均报以上错误
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

使用的环境是colab，尝试了gpu、tpu、cpu运行环境，均报以上错误
好奇的询问，是显存/内存问题导致的报错，还是其他问题，谷歌搜索的结果暂时没有匹配的

**Comment by bojone** [comment]
看上去是你权重文件损坏的原因，可能下载的时候没下载全。
