### ISSUE TITLE
The data generators in the code examples only supports keras>=2.2.5

### ISSUE THREAD

**Issue by redreamality** [bojone/bert4keras#272]
So better remove the `supports below keras 2.2.5` in readme that might cause potential error

From keras 2.2.5, 
> Allow Python generators (or Keras Sequence objects) to be passed in fit, evaluate, and predict, instead of having to use *_generator methods.

**Comment by bojone** [comment]
the next version will support keras<2.2.5 again (By combining `model.fit` and `model.fit_generator` automatically in the lower version of keras)

**Comment by bojone** [comment]
fixed. https://github.com/bojone/bert4keras/commit/3b57b5778ec935463bffab831609519574dde35b#diff-fbe4e655d7da485d9313ca966df4bf963c294e0716fb6693e2a3af51a3afb7d7
