### ISSUE TITLE
相对位置编码

### ISSUE THREAD

**Issue by Ben1-cloud** [bojone/bert4keras#273]
请问BERT模型能否直接加载相对位置编码层

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by bojone** [comment]
不能，换一个位置编码意味着是一个新的模型，需要重新训练的。

其实，“BERT的主要结构+相对位置编码”就是华为的NAZHA模型，你可以直接用训练好的NEZHA模型。
