### ISSUE TITLE
parameter "random" is always True for __iter__ function of DataGenerator

### ISSUE THREAD

**Issue by JuntaoLiu01** [bojone/bert4keras#278]
### 基本信息
- 你使用的**操作系统**:  Mac OS
- 你使用的**Python**版本: 3.7
- 你使用的**Tensorflow**版本: 1.14.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.8.8
- 你使用纯**keras**还是**tf.keras**: keras
- 你加载的**预训练模型**: roberta

### 核心代码
```python
# snnipets.py 中，DataGenerator类中forfit函数，原始定义如下：
    def forfit(self):
        while True:
            for d in self.__iter__(True):
                yield d
# 上面这样写导致数据在加载时总会被打乱，这在一些情况下是有点不太方便，例如书写predict函数时。
```

### 输出信息
```python
# 一个简单的修改
    def forfit(self, random=True):
        while True:
            for d in self.__iter__(random):
                yield d
```

**Comment by bojone** [comment]
问题是，如果你不想shuffle，直接用`self.__iter__()`不就行了么，为啥要用`self.forfit()`呢？`forfit`就是for fit，自然是应该打乱并且无限循环的，如果是predict，直接用`self.forfit()`就好。

**Comment by JuntaoLiu01** [comment]
> 问题是，如果你不想shuffle，直接用`self.__iter__()`不就行了么，为啥要用`self.forfit()`呢？`forfit`就是for fit，自然是应该打乱并且无限循环的，如果是predict，直接用`self.__iter__()`就好。

理解了，多谢大佬！
