### ISSUE TITLE
load_weights 报错了

### ISSUE THREAD

**Issue by hackerxiaobai** [bojone/bert4keras#282]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**:  ubuntu18.04
- 你使用的**Python**版本:  3.7.0
- 你使用的**Tensorflow**版本: 1.14.0
- 你使用的**Keras**版本:  2.3.1
- 你使用的**bert4keras**版本: 0.9.5
- 你使用纯**keras**还是**tf.keras**:  keras
- 你加载的**预训练模型**: bert

### 核心代码
```python
model.load_weights('model.weights')
```

### 输出信息
![image](https://user-images.githubusercontent.com/22817243/104086301-a2343c80-5291-11eb-9de1-95acbf9b1562.png)

**Comment by chenrulongmaster** [comment]
要这样搞 pip install 'h5py<3.0.0'
