### ISSUE TITLE
pretrain问题

### ISSUE THREAD

**Issue by SuMeng123** [bojone/bert4keras#283]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: linux
- 你使用的**Python**版本: 3.6.4
- 你使用的**Tensorflow**版本: 1.14.0
- 你使用的**Keras**版本: 2.2.4
- 你使用的**bert4keras**版本: 0.6.1
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**:google/bert

### 核心代码
```python
# 这是我修改的data_utils.py中some_texts()部分
    def some_texts():
        filenames = glob.glob('XXX.txt')
        np.random.shuffle(filenames)
        count, texts = 0, []
        for filename in filenames:
            with open(filename) as f:
                for l in f:
                    l = l.strip()
                    texts.append(l)
                    yield texts
                    texts = []
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

苏老师好，最近在使用bert4keras针对自己任务语料做预训练，把自己的问题总结成一句话就是“**不清楚如何修改data_utils.py和pretraining.py相应的配置和参数，以适配自己的语料**”。以下是我的具体问题以及实验，请苏老师指导一下。

一、任务背景：
1、对评论做二分类，评论属于短文本，长度一般集中在10-30之间。使用bert，f1=66%，我认为还是有较大提升空间，所以用更大的相关的评论语料对bert预训练。
2、语料规模是1千5百万条长度大于10的评论文本,按照data_utils.py逻辑，会重复10遍，就是1亿5千万
3、采用roberta的方式预训练

二、data_utils.py数据生成逻辑的修改:
原代码从10篇文章中提取文本，组成长度尽可能接近sequence_length=512的complete_instance。由于我的语料都是短文本，也并不像文章一样每句话都有联系。所以改为了sequence_length=40，complete_instance只由一条短文本组成。这样做有什么负面影响吗？

三、pretraining.py参数:
仔细查了每个配置参数的意思，但是还是不知道如何根据自己的语料来设置具体参数。还请苏老师讲解一下。
1、num_train_steps参数
google/bert的run_pretraining.py中这个参数是直接写死了，也没说为什么。
2、num_warmup_steps参数
google/bert的run_pretraining.py中设置的是num_train_steps的10%，我们的代码中设置num_warmup_steps = 3125的原因是什么呢？
3、lr_schedule的设置
google/bert中，学习率先从0提升到lr，然后是保持不变，我们为什么就降低到0呢。当然可能跟我们lr=0.00176比较大有关，但为什么要这样呢？

四、实验
1、模型初始参数采用google/bert的参数
2、设置batch_size = 2048，其余采用pretraining.py中默认的参数，从training.log来看，准确率最高只接近37%。我看您在[issue84](https://github.com/bojone/bert4keras/issues/84)中提到acc一般是50%-60%。苏老师觉得我的问题可能出在哪里呢？
```
epoch,loss,mlm_acc_loss,mlm_loss_loss
0,4.1459182634592056,0.34518507,3.8007286
1,3.9495830785989763,0.3676725,3.5819125
2,3.9327449764490128,0.3699239,3.562816
3,3.951032319355011,0.3666434,3.584382
4,3.9811926936149598,0.36270177,3.6184883
5,3.997273787522316,0.36036325,3.6369083
```
3、设置batch_size = 2048，steps_per_epoch = 100000，其余采用pretraining.py中默认的参数。结果大致不变。
```
epoch,loss,mlm_acc_loss,mlm_loss_loss
0,3.986297978975773,0.36288327,3.623436
1,3.9343528621816635,0.37045658,3.5639102
```
4、预训练之后，再在下游任务微调，指标没有明显变化，f1提升1个点吧，考虑到base f1=66%，我觉得应该提升更多才对

期待苏老师的回复，谢谢

**Comment by SuMeng123** [comment]
这是我修改后的data_utils.py的some_texts()方法：
```
    def some_texts():
        filenames = glob.glob('XXX.txt')
        np.random.shuffle(filenames)
        count, texts = 0, []
        for filename in filenames:
            with open(filename) as f:
                for l in f:
                    l = l.strip()
                    texts.append(l)
                    yield texts
                    texts = []
```

**Comment by bojone** [comment]
1、缩小sequence_length不至于有太大的负面影响；
2、num_train_steps越大越好，默认似乎是100万步，但你可以看情况人工中断；
3、num_warmup_steps，这个随意吧，没什么太大关系；
4、lr_schedule降不降低到零，其实在num_train_steps足够大的事情，差别不大。
5、其实Google原版代码用的是AdamW优化器，而这里用的是LAMB优化器，两者默认参数都不一样的。
6、我不确定你训练了多少步，不同任务的mlm acc可能不一样，此外要训练足够多的步数，acc才会慢慢上去，这个过程是很缓慢的；
7、预训练带来的上升幅度也是也不会“巨大”，如果你说f1提升一个点，那已经不能说“没有明显变化”了，如果发paper，1%已经算得上明显变化了。

**Comment by SuMeng123** [comment]
> 1、缩小sequence_length不至于有太大的负面影响；
> 2、num_train_steps越大越好，默认似乎是100万步，但你可以看情况人工中断；
> 3、num_warmup_steps，这个随意吧，没什么太大关系；
> 4、lr_schedule降不降低到零，其实在num_train_steps足够大的事情，差别不大。
> 5、其实Google原版代码用的是AdamW优化器，而这里用的是LAMB优化器，两者默认参数都不一样的。
> 6、我不确定你训练了多少步，不同任务的mlm acc可能不一样，此外要训练足够多的步数，acc才会慢慢上去，这个过程是很缓慢的；
> 7、预训练带来的上升幅度也是也不会“巨大”，如果你说f1提升一个点，那已经不能说“没有明显变化”了，如果发paper，1%已经算得上明显变化了。

就像您说的苏老师您讲的预训练是一个漫长的过程，我又重新预训练比较久的时间，acc确实有了提升，以前太心急。我现在还在继续实验，比如对语料做些修改，降低mlm任务的难度，后续我会继续在这个更新同步进展

**Comment by bojone** [comment]
好的，欢迎记录分享。

**Comment by SimZhou** [comment]
> > 1、缩小sequence_length不至于有太大的负面影响；
> > 2、num_train_steps越大越好，默认似乎是100万步，但你可以看情况人工中断；
> > 3、num_warmup_steps，这个随意吧，没什么太大关系；
> > 4、lr_schedule降不降低到零，其实在num_train_steps足够大的事情，差别不大。
> > 5、其实Google原版代码用的是AdamW优化器，而这里用的是LAMB优化器，两者默认参数都不一样的。
> > 6、我不确定你训练了多少步，不同任务的mlm acc可能不一样，此外要训练足够多的步数，acc才会慢慢上去，这个过程是很缓慢的；
> > 7、预训练带来的上升幅度也是也不会“巨大”，如果你说f1提升一个点，那已经不能说“没有明显变化”了，如果发paper，1%已经算得上明显变化了。
> 
> 就像您说的苏老师您讲的预训练是一个漫长的过程，我又重新预训练比较久的时间，acc确实有了提升，以前太心急。我现在还在继续实验，比如对语料做些修改，降低mlm任务的难度，后续我会继续在这个更新同步进展

您好，请问您重新预训练比较久的时间后，accuracy具体提升了多少呢？好奇。

**Comment by rxc205** [comment]
> > 1、缩小sequence_length不至于有太大的负面影响；
> > 2、num_train_steps越大越好，默认似乎是100万步，但你可以看情况人工中断；
> > 3、num_warmup_steps，这个随意吧，没什么太大关系；
> > 4、lr_schedule降不降低到零，其实在num_train_steps足够大的事情，差别不大。
> > 5、其实Google原版代码用的是AdamW优化器，而这里用的是LAMB优化器，两者默认参数都不一样的。
> > 6、我不确定你训练了多少步，不同任务的mlm acc可能不一样，此外要训练足够多的步数，acc才会慢慢上去，这个过程是很缓慢的；
> > 7、预训练带来的上升幅度也是也不会“巨大”，如果你说f1提升一个点，那已经不能说“没有明显变化”了，如果发paper，1%已经算得上明显变化了。
> 
> 就像您说的苏老师您讲的预训练是一个漫长的过程，我又重新预训练比较久的时间，acc确实有了提升，以前太心急。我现在还在继续实验，比如对语料做些修改，降低mlm任务的难度，后续我会继续在这个更新同步进展

你好，方便给一下你最终使用的参数配置和数据量等信息吗？我想做一下参考，感谢！

**Comment by SuMeng123** [comment]
我当时使用bert4keras预训练提升感觉不明显，可能是自己哪里出了问题吧，结果不是很满意。后来改用了UER进行预训练，预训练后的模型按照UER提供的脚本改为TF格式，然后再用bert4keras加载tf格式的模型进行使用。 @rxc205 @SimZhou 。比如我最近的一个分类任务使用UER预训练比base相比，f1提升5个点。

**Comment by rxc205** [comment]
> 我当时使用bert4keras预训练提升感觉不明显，可能是自己哪里出了问题吧，结果不是很满意。后来改用了UER进行预训练，预训练后的模型按照UER提供的脚本改为TF格式，然后再用bert4keras加载tf格式的模型进行使用。 @rxc205 @SimZhou 。比如我最近的一个分类任务使用UER预训练比base相比，f1提升5个点。

F1取得5%的提升，是非常非常非常高的了。

**Comment by SimZhou** [comment]
> 我当时使用bert4keras预训练提升感觉不明显，可能是自己哪里出了问题吧，结果不是很满意。后来改用了UER进行预训练，预训练后的模型按照UER提供的脚本改为TF格式，然后再用bert4keras加载tf格式的模型进行使用。 @rxc205 @SimZhou 。比如我最近的一个分类任务使用UER预训练比base相比，f1提升5个点。

谢谢分享，5%很多了，不过看你描述的步骤，似乎没有继续进行微调，预训练完直接加载模型进行使用了？

**Comment by SuMeng123** [comment]
> > 我当时使用bert4keras预训练提升感觉不明显，可能是自己哪里出了问题吧，结果不是很满意。后来改用了UER进行预训练，预训练后的模型按照UER提供的脚本改为TF格式，然后再用bert4keras加载tf格式的模型进行使用。 @rxc205 @SimZhou 。比如我最近的一个分类任务使用UER预训练比base相比，f1提升5个点。
> 
> 谢谢分享，5%很多了，不过看你描述的步骤，似乎没有继续进行微调，预训练完直接加载模型进行使用了？

使用UER提前预训练好的mixed_corpus_bert_base_model作为初始模型，然后在此基础上使用自己的语料进行预训练，然后在预训练模型的基础上使用自己标注数据进行微调。微调后模型的f1比使用google-bert-base直接微调高5%。
