### ISSUE TITLE
添加Beam Search 时的并行运算功能

### ISSUE THREAD

**Issue by wdbob** [bojone/bert4keras#298]
苏大， 能不能添加Beam Search 时的并行运算功能。 比如说，我一个batch并行做beam search。

**Comment by bojone** [comment]
不能。batch beam search不会明显提高解码速度。

提高解码速度需要引入cache机制，并且实现gpu版的beam search，短期内没有计划。

**Comment by wdbob** [comment]
我在做一个版本的batch beam search，主要是通过提高源码中predict方法的并行性来提高beam search的解码速度，它的解码时长取决于batch中个样本中最长的时长。 问：这种方法是否合理？如果不改动源码的话，会不会更高效？

**Comment by bojone** [comment]
1、不会更高效；

2、你要改的话，是要改beam_search方法而不是predict方法，predict方法本身就是batch进行的，不用改。

**Comment by wdbob** [comment]
beam_search当然也改了。所以我问下你有没有要改beam_search。如果你改的话，我也可以参照一下。谢答了。

**Comment by SunYanCN** [comment]
@wdbob batch版本的beam_search可以发一下吗 参考一下
