### ISSUE TITLE
目前不支持自定义的model

### ISSUE THREAD

**Issue by sangcheng0615** [bojone/bert4keras#302]
if is_string(model):
        model = model.lower()
        MODEL = models[model]
else:
    MODEL = model

    application = application.lower()
    if application in ['lm', 'unilm'] and model in ['electra', 't5']:
        raise ValueError(
            '"%s" model can not be used as "%s" application.\n' %
            (model, application)
        )

    if application == 'lm':
        MODEL = extend_with_language_model(MODEL)
    elif application == 'unilm':
        MODEL = extend_with_unified_language_model(MODEL)

    if model.startswith('t5.1.1'):
        configs['version'] = 't5.1.1'

苏神，在你的model文件中本来是可以支持直接传入model的，有is_string(model)；但是我想自定义一个model继承Transformer；因为if model.startswith('t5.1.1')会报错；建议将其改成 if is_string(model) and model.startswith('t5.1.1');否则MODEL = model就失去意义了

**Comment by bojone** [comment]
确实有这个问题，感谢反馈，已经修复 https://github.com/bojone/bert4keras/commit/5086197bf965d7a5b11be57a3838d21d36c5a342
