### ISSUE TITLE
预训练数据处理问题

### ISSUE THREAD

**Issue by stevewyl** [bojone/bert4keras#304]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: ubuntu 20.04
- 你使用的**Python**版本: 3.7
- 你使用的**Tensorflow**版本: 1.15.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.10.0
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**:

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

有个疑问请教下苏神，最近阅读预训练相关的代码，发现被mask掉的token的id会加1，不是很明白这里的+1的逻辑
https://github.com/bojone/bert4keras/blob/5086197bf965d7a5b11be57a3838d21d36c5a342/pretraining/data_utils.py#L190
随后我去查看了google/bert和brightmart/roberta_zh中关于构建mask的代码，均未发现加1的操作。

**Comment by Jhangsy** [comment]
@stevewyl ste 你好，这么写是为什么有解决吗？
我注意到在 ```load_function``` 的方法中有
```masked_token_ids = K.switch(is_masked, mask_ids - 1, token_ids)```, 
这样就抵消了 +1 的影响，但是不清楚为什么要做这样的处理。
