### ISSUE TITLE
data_utils.py输入的数据格式

### ISSUE THREAD

**Issue by liuzqiao** [bojone/bert4keras#306]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: windows10
- 你使用的**Python**版本: 3.7.9
- 你使用的**Tensorflow**版本: 1.15.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 直接下载的data_utils.py文件
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**:chinese_roberta_wwm_ext_L-12_H-768_A-12

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```
苏神好，想请问一下下面这段代码里的texts最终得到的格式是不是['句子1','句子2','句子3']格式的list呢

```
count, texts = 0, []
  for filename in filenames:
    with open(filename) as f:
      for l in f:
        l = json.loads(l)['text'].strip()
        texts.extend(re.findall(u'.*?[\n。]+', l))
        count += 1
        if count == 10:  # 10篇文章合在一起再处理
          yield texts
          count, texts = 0, []
```
如果得到['句子1','句子2','句子3']这种格式，下面这段代码是什么意思呢？主要由两点疑惑：
1. sentence_process主要实现的是什么功能呢，我这里源码看到的是直接返回了一个异常。
2. for text in texts这个for循环里，理解没错的话text拿到的是一个句子，但是[i[:self.sequence_length - 2] for i in sub_instance]这条代码里又对text进行了遍历，所以我理解i拿到的是句子里的一个字，可是对i做i[:self.sequence_length - 2]这个操作是什么意思，是我哪里理解除了问题吗？
3. 一直卡在这段代码里，希望苏神能解答一下，谢谢！

```
def sentence_process(self, text):
  """单个文本的处理函数，返回处理后的instance
  """
  raise NotImplementedError

instances, instance = [], [[start] for start in starts]
for text in texts:
  # 处理单个句子
  sub_instance = self.sentence_process(text)
  sub_instance = [i[:self.sequence_length - 2] for i in sub_instance]
  new_length = len(instance[0]) + len(sub_instance[0])
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by stevewyl** [comment]
@liuzqiao 最近在看预训练代码，可以替苏神解答下:P
问题1：主要实现的是对文本进行id编码，异常的话应该是你传入的数据可能有误
问题2：看self.sentence_process的返回结果，返回的是token_ids和mask_ids，所以这里的i是指这两个序列，并不是指每一个token。其次，sub_instance-2的操作是确保能在句子末尾加上[SEP]以及下一句句子的[CLS]标记。因为这里是不断塞句子的操作，需要保证有[CLS]和[SEP]标记表示句子的开始和结束。
问题3：具体卡在哪里没有说明呀，贴上报错信息吧

**Comment by liuzqiao** [comment]
> @liuzqiao 最近在看预训练代码，可以替苏神解答下:P
> 问题1：主要实现的是对文本进行id编码以及生成mask的新id，异常的话应该是你传入的数据可能有误
> 问题2：看self.sentence_process的返回结果，返回的是token_ids和mask_ids，所以这里的i是指这两个序列，并不是指每一个token。其次，sub_instance-2的操作是确保能在句子末尾加上[SEP]以及下一句句子的[CLS]标记。因为这里是不断塞句子的操作，需要保证有[CLS]和[SEP]标记表示句子的开始和结束。
> 问题3：具体卡在哪里没有说明呀，贴上报错信息吧

感谢大佬的解答。这里的异常指的是源码里自带的raise NotImplementedError，不是我运行的异常，我看源码里没有实现self.sentence_process这个函数，请问是需要自己实现吗?

**Comment by stevewyl** [comment]
@liuzqiao 一般来说苏神实现的版本（如TrainingDatasetRoBERTa类）已经可以用了，也根据自己的需求进行实现

**Comment by liuzqiao** [comment]
> @liuzqiao 一般来说苏神实现的版本（如TrainingDatasetRoBERTa类）已经可以用了，也根据自己的需求进行实现

抱歉，是我大意了，之前看的是TrainingDataset这个类，看的一头雾水，刚刚才发现你说的TrainingDatasetRoBERTa，感谢！
