### ISSUE TITLE
Mac M1芯片上加载bert报错

### ISSUE THREAD

**Issue by beyondguo** [bojone/bert4keras#307]
### 基本信息
- 你使用的**操作系统**:  MacOS M1
- 你使用的**Python**版本: Python3.8
- 你使用的**Tensorflow**版本: Tf2.4 
- 你使用的**Keras**版本:  TF自带
- 你使用的**bert4keras**版本:  0.10.1
- 你使用纯**keras**还是**tf.keras**:  tf.keras
- 你加载的**预训练模型**: bert-tiny

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```

### 输出信息
```shell
import os
os.environ['TF_KERAS'] = '1'  # 必须使用tf.keras

import glob
import numpy as np
from bert4keras.backend import keras, K
from bert4keras.layers import Loss
from bert4keras.models import build_transformer_model
from bert4keras.tokenizers import Tokenizer, load_vocab
from bert4keras.optimizers import Adam
from bert4keras.snippets import sequence_padding, open
from bert4keras.snippets import DataGenerator, AutoRegressiveDecoder
from keras.models import Model
import tensorflow as tf  # 导入tf，备用

config_path = 'uncased_L-2_H-128_A-2/bert_config.json'
checkpoint_path = 'uncased_L-2_H-128_A-2/bert_model.ckpt'
dict_path = 'uncased_L-2_H-128_A-2/vocab.txt'

# 加载并精简词表，建立分词器
token_dict, keep_tokens = load_vocab(
    dict_path=dict_path,
    simplified=True,
    startswith=['[PAD]', '[UNK]', '[CLS]', '[SEP]'],
)
tokenizer = Tokenizer(token_dict, do_lower_case=True)

bert = build_transformer_model(
        config_path,
        checkpoint_path=None,  # 此时可以不加载预训练权重
        application='unilm',
        keep_tokens=keep_tokens,  # 只保留keep_tokens中的字，精简原字表
        return_keras_model=False,  # 返回bert4keras类，而不是keras模型
    )
bert.load_weights_from_checkpoint(checkpoint_path)  # 必须最后才加载预训练权重
```

### 报错：
```
ValueError                                Traceback (most recent call last)
<ipython-input-4-5113346dd4da> in <module>
      6         return_keras_model=False,  # 返回bert4keras类，而不是keras模型
      7     )
----> 8 bert.load_weights_from_checkpoint(checkpoint_path)  # 必须最后才加载预训练权重

~/miniforge3/envs/tf4mac/lib/python3.8/site-packages/bert4keras/models.py in load_weights_from_checkpoint(self, checkpoint, mapping)
    311                     W = W * key_size**0.25 / head_size**0.25
    312                 for w in layer.trainable_weights[:count]:
--> 313                     if w in weights:
    314                         v = values[weights.index(w)]
    315                         w_shape, v_shape = K.int_shape(w), v.shape

~/miniforge3/envs/tf4mac/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in __bool__(self)
    990 
    991   def __bool__(self):
--> 992     return bool(self._numpy())
    993 
    994   __nonzero__ = __bool__

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by bojone** [comment]
0.10.1和0.10.2出了点问题，在tf2下会报错，已经撤回了。请用0.10.0或0.10.3



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月15日(周一) 凌晨0:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [bojone/bert4keras] Mac M1芯片上加载bert报错 (#307)




 
基本信息
  
你使用的操作系统:  MacOS M1 

你使用的Python版本: Python3.8 

你使用的Tensorflow版本: Tf2.4 

你使用的Keras版本:  TF自带 

你使用的bert4keras版本:  0.10.1 

你使用纯keras还是tf.keras:  tf.keras 

你加载的预训练模型: bert-tiny 
 
核心代码
 # 请在此处贴上你的核心代码。 # 请尽量只保留关键部分，不要无脑贴全部代码。
 
输出信息
 import os os.environ['TF_KERAS'] = '1'  # 必须使用tf.keras import glob import numpy as np from bert4keras.backend import keras, K from bert4keras.layers import Loss from bert4keras.models import build_transformer_model from bert4keras.tokenizers import Tokenizer, load_vocab from bert4keras.optimizers import Adam from bert4keras.snippets import sequence_padding, open from bert4keras.snippets import DataGenerator, AutoRegressiveDecoder from keras.models import Model import tensorflow as tf  # 导入tf，备用 config_path = 'uncased_L-2_H-128_A-2/bert_config.json' checkpoint_path = 'uncased_L-2_H-128_A-2/bert_model.ckpt' dict_path = 'uncased_L-2_H-128_A-2/vocab.txt' # 加载并精简词表，建立分词器 token_dict, keep_tokens = load_vocab(     dict_path=dict_path,     simplified=True,     startswith=['[PAD]', '[UNK]', '[CLS]', '[SEP]'], ) tokenizer = Tokenizer(token_dict, do_lower_case=True) bert = build_transformer_model(         config_path,         checkpoint_path=None,  # 此时可以不加载预训练权重         application='unilm',         keep_tokens=keep_tokens,  # 只保留keep_tokens中的字，精简原字表         return_keras_model=False,  # 返回bert4keras类，而不是keras模型     ) bert.load_weights_from_checkpoint(checkpoint_path)  # 必须最后才加载预训练权重
 
报错：
 ValueError                                Traceback (most recent call last) <ipython-input-4-5113346dd4da&gt; in <module&gt;       6         return_keras_model=False,  # 返回bert4keras类，而不是keras模型       7     ) ----&gt; 8 bert.load_weights_from_checkpoint(checkpoint_path)  # 必须最后才加载预训练权重 ~/miniforge3/envs/tf4mac/lib/python3.8/site-packages/bert4keras/models.py in load_weights_from_checkpoint(self, checkpoint, mapping)     311                     W = W * key_size**0.25 / head_size**0.25     312                 for w in layer.trainable_weights[:count]: --&gt; 313                     if w in weights:     314                         v = values[weights.index(w)]     315                         w_shape, v_shape = K.int_shape(w), v.shape ~/miniforge3/envs/tf4mac/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in __bool__(self)     990      991   def __bool__(self): --&gt; 992     return bool(self._numpy())     993      994   __nonzero__ = __bool__ ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by beyondguo** [comment]
解决了！感谢！

**Comment by ouyxy** [comment]
> 解决了！感谢！

您好，我也遇到这个，请问怎么解决的？

**Comment by diorw** [comment]
> 0.10.0

请问M1芯片 mini-forge 安装的tf2.5 能使用bert4keras吗 提示
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

**Comment by wangszoo** [comment]
@diorw 您好，请问问题解决了么，我也碰到了
AttributeError: module 'keras.utils' has no attribute 'get_custom_objects'
