### ISSUE TITLE
t5-pegasus里的finetune.py使用梯度累加，报错：显存不足，batch_size=1时报同样的error

### ISSUE THREAD

**Issue by Sieg-Arash** [bojone/bert4keras#309]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Centos 7.4
- 你使用的**Python**版本: 3.7.10
- 你使用的**Tensorflow**版本: 1.14
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.10.0
- 你使用纯**keras**还是**tf.keras**: 纯keras
- 你加载的**预训练模型**:T5-pegasus

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```
AdamG = extend_with_gradient_accumulation(Adam, name='AdamG')
optimizer = AdamG(learning_rate=2e-4, grad_accum_steps=2)
model.compile(optimizer=optimizer)

### 输出信息
```shell
# 请在此处贴上你的调试输出
```
2021-03-15 17:51:24.723012: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at cwise_ops_common.cc:82 : Resource exhausted: OOM when allocating tensor with shape[2048,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[1]    28197 segmentation fault  python finetune.py

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

同环境下，T5_in_bert4keras里使用mt5的task_autotitle_csl.py加上如上代码可以运行
t5-pegasus里的finetune.py，加上如上代码报错，batch_size=1仍报错，不加可以运行

**Comment by bojone** [comment]
oom不是bug，就是显存不够，就意味着你batch_size=1都跑不起来咯。你是多少显存的卡？梯度累积是比不累积要更多显存的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月16日(周二) 上午9:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [bojone/bert4keras] t5-pegasus里的finetune.py使用梯度累加，报错：显存不足，batch_size=1时报同样的error (#309)




 
提问时请尽可能提供如下信息：
 
基本信息
  
你使用的操作系统: Centos 7.4 

你使用的Python版本: 3.7.10 

你使用的Tensorflow版本: 1.14 

你使用的Keras版本: 2.3.1 

你使用的bert4keras版本: 0.10.0 

你使用纯keras还是tf.keras: 纯keras 

你加载的预训练模型:T5-pegasus 
 
核心代码
 # 请在此处贴上你的核心代码。 # 请尽量只保留关键部分，不要无脑贴全部代码。
 
AdamG = extend_with_gradient_accumulation(Adam, name='AdamG')
 optimizer = AdamG(learning_rate=2e-4, grad_accum_steps=2)
 model.compile(optimizer=optimizer)
 
输出信息
 # 请在此处贴上你的调试输出
 
2021-03-15 17:51:24.723012: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at cwise_ops_common.cc:82 : Resource exhausted: OOM when allocating tensor with shape[2048,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
 [1]    28197 segmentation fault  python finetune.py
 
自我尝试
 
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
 
同环境下，T5_in_bert4keras里使用mt5的task_autotitle_csl.py加上如上代码可以运行
 t5-pegasus里的finetune.py，加上如上代码报错，batch_size=1仍报错，不加可以运行

**Comment by Sieg-Arash** [comment]
> oom不是bug，就是显存不够，就意味着你batch_size=1都跑不起来咯。你是多少显存的卡？梯度累积是比不累积要更多显存的。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月16日(周二) 上午9:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [bojone/bert4keras] t5-pegasus里的finetune.py使用梯度累加，报错：显存不足，batch_size=1时报同样的error (#309) 提问时请尽可能提供如下信息： 基本信息 你使用的操作系统: Centos 7.4 你使用的Python版本: 3.7.10 你使用的Tensorflow版本: 1.14 你使用的Keras版本: 2.3.1 你使用的bert4keras版本: 0.10.0 你使用纯keras还是tf.keras: 纯keras 你加载的预训练模型:T5-pegasus 核心代码 # 请在此处贴上你的核心代码。 # 请尽量只保留关键部分，不要无脑贴全部代码。 AdamG = extend_with_gradient_accumulation(Adam, name='AdamG') optimizer = AdamG(learning_rate=2e-4, grad_accum_steps=2) model.compile(optimizer=optimizer) 输出信息 # 请在此处贴上你的调试输出 2021-03-15 17:51:24.723012: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at cwise_ops_common.cc:82 : Resource exhausted: OOM when allocating tensor with shape[2048,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [1] 28197 segmentation fault python finetune.py 自我尝试 不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。 同环境下，T5_in_bert4keras里使用mt5的task_autotitle_csl.py加上如上代码可以运行 t5-pegasus里的finetune.py，加上如上代码报错，batch_size=1仍报错，不加可以运行 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我不加这几行代码，是可以跑batch_size=15的。。

**Comment by bojone** [comment]
还是那句话，OOM不是bug，所以没有什么修正的说法。

几点参考排查：
- 梯度累积是比不累积要更多显存的
- keras可能比tf.keras需要更多显存
- 你可以尝试将maxlen设置得很小试试

**Comment by Sieg-Arash** [comment]
> 还是那句话，OOM不是bug，所以我也无法修正啥。
> 
> 几点参考排查：
> 
> * 梯度累积是比不累积要更多显存的
> * keras可能比tf.keras需要更多显存
> * 你可以尝试将maxlen设置得很小试试

好的，谢谢苏神，主要是之前别的模型，梯度累加都没有问题，我试试重计算

**Comment by Sieg-Arash** [comment]
> 还是那句话，OOM不是bug，所以我也无法修正啥。
> 
> 几点参考排查：
> 
> * 梯度累积是比不累积要更多显存的
> * keras可能比tf.keras需要更多显存
> * 你可以尝试将maxlen设置得很小试试

好的，谢谢苏神，主要是之前别的模型，梯度累加都没有问题，我试试重计算
