### ISSUE TITLE
tensorflow版本和cuda版本

### ISSUE THREAD

**Issue by chuanfanyoudong** [bojone/bert4keras#32]
大佬，打扰了，我想问一下因为我的cuda版本是9.x的，但是如果tensorflow版本是1.13+的话，要求cuda版本10的，可以问一下之前能支持低版本tensorflow的包还在吗？

**Comment by bojone** [comment]
应该没有了，我记得打包出来最早的版本好像都放弃了1.13了。

不过你也可以去翻2019.10.21之前的历史版本。。。

**Comment by chuanfanyoudong** [comment]
> 应该没有了，我记得打包出来最早的版本好像都放弃了1.13了。
> 
> 不过你也可以去翻2019.10.21之前的历史版本。。。

谢谢大佬，我去找一找2019.10.21之前的版本；
还有一个与这个issue无关的问题想请教一下大佬哈，就是在做具体任务的时候，一般是固定bert的参数还是让bert的参数tranable哈？

**Comment by bojone** [comment]
多数是trainable

**Comment by chuanfanyoudong** [comment]
> 多数是trainable

谢谢大佬
