### ISSUE TITLE
bert as service和bert4keras生成的向量不一样

### ISSUE THREAD

**Issue by lxy417** [bojone/bert4keras#326]
bert as service和bert4keras用同一个预训练模型，生成出来的向量值不一样，这是为什么？
### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Tensorflow**版本: 
- 你使用的**Keras**版本: 
- 你使用的**bert4keras**版本: 
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:chinese_L-12_H-768_A-12

### 核心代码
```python
# bert-as-service
bc = BertClient()
a = bc.encode([u'语言模型'],show_tokens=True)

tokenizer = Tokenizer(dict_path, do_lower_case=True)  # 建立分词器
model = build_transformer_model(config_path, checkpoint_path)  # 建立模型，加载权重

token_ids, segment_ids = tokenizer.encode(u'语言模型')
token_ids, segment_ids = to_array([token_ids], [segment_ids])

print('\n ===== predicting =====\n')
print(model.predict([token_ids, segment_ids]))
```

### 输出信息

# bert as service 
![image](https://user-images.githubusercontent.com/33677809/113566659-b80e8f00-963f-11eb-8ca5-d9704eb321df.png)

# bert4keras
![image](https://user-images.githubusercontent.com/33677809/113566755-e68c6a00-963f-11eb-8a0a-77337170e43f.png)

**Comment by bojone** [comment]
那这个你应该去研读bert as service的源码，bert4keras跟官方bert的输出是对齐的。

**Comment by Jhangsy** [comment]
@lxy417 你好，我最近也遇到这个问题，请问您解决了吗？
