### ISSUE TITLE
加载模型报错TypeError: Expected float32 passed to parameter 'y' of op 'Equal', got 'history_only' of type 'str' instead. Error: Expected float32, got 'history_only' of type 'str' instead.

### ISSUE THREAD

**Issue by BatterToMe** [bojone/bert4keras#33]
大佬你好，我在构建seq2seq的bert时出现
TypeError: Expected float32 passed to parameter 'y' of op 'Equal', got 'history_only' of type 'str' instead. Error: Expected float32, got 'history_only' of type 'str' instead.
环境为python3.6  tensorflow2.0
这个类型错误，发现是在layer.py中有
if a_mask is not None:
            if a_mask == 'history_only':
                ones = K.ones_like(a[:1])
                a_mask = (ones - tf.linalg.band_part(ones, -1, 0)) * 1e12
                a = a - a_mask
            else:
                a = a - (1 - a_mask) * 1e12
应该是a_mask是张量，不允许和字符串用做对比吧，所以我改了一下
将if a_mask == 'history_only':改为
if isinstance(a_mask,str):
这样可以成功加载模型

**Comment by bojone** [comment]
感谢你的测试和建议。根据你的建议我做了一下微调，欢迎重新测试。

**Comment by Animath3099** [comment]
我在构建seq2seq的bert时也出现报错，但是错误不太一样
环境python 3.6.4  Keras 2.3.1 Tensorflow 2.0  bert4keras 0.2.6, OS Ubuntu
ValueError: Duplicate node name in graph: 'Attention-Mask/ones/packed'
目测也是seq2seq的mask部分出错，希望楼主或者作者可以给点指导
basic_extract_features运行是没问题的

**Comment by bojone** [comment]
@Animath3099 你这个问题不是类似问题，请提新issue反馈你的具体改动过程。

**Comment by BatterToMe** [comment]
这个问题我也遇到过，是在bert.py里这段
def seq2seq_attention_mask(s, repeats=1):
                import tensorflow as tf
                seq_len = K.shape(s)[1]
                ones = K.ones((1, repeats, seq_len, seq_len))
                a_mask = tf.linalg.band_part(ones, -1, 0)
                s_ex12 = K.expand_dims(K.expand_dims(s, 1), 2)
                s_ex13 = K.expand_dims(K.expand_dims(s, 1), 3)
                a_mask = (1 - s_ex13) * (1 - s_ex12) + s_ex13 * a_mask
                a_mask = K.reshape(a_mask, (-1, seq_len, seq_len))
                return a_mask
其中的ones = K.ones((1, repeats, seq_len, seq_len))
将K.ones((1, repeats, seq_len, seq_len))改为
tf.ones((1, repeats, seq_len, seq_len))就行了。
原因我也没有很清楚，可能是后端没有处理好吧。

**Comment by BatterToMe** [comment]
> 我在构建seq2seq的bert时也出现报错，但是错误不太一样
> 环境python 3.6.4 Keras 2.3.1 Tensorflow 2.0 bert4keras 0.2.6, OS Ubuntu
> ValueError: Duplicate node name in graph: 'Attention-Mask/ones/packed'
> 目测也是seq2seq的mask部分出错，希望楼主或者作者可以给点指导
> basic_extract_features运行是没问题的

这个问题我也遇到过，是在bert.py里这段
def seq2seq_attention_mask(s, repeats=1):
import tensorflow as tf
seq_len = K.shape(s)[1]
ones = K.ones((1, repeats, seq_len, seq_len))
a_mask = tf.linalg.band_part(ones, -1, 0)
s_ex12 = K.expand_dims(K.expand_dims(s, 1), 2)
s_ex13 = K.expand_dims(K.expand_dims(s, 1), 3)
a_mask = (1 - s_ex13) * (1 - s_ex12) + s_ex13 * a_mask
a_mask = K.reshape(a_mask, (-1, seq_len, seq_len))
return a_mask
其中的ones = K.ones((1, repeats, seq_len, seq_len))
将K.ones((1, repeats, seq_len, seq_len))改为
tf.ones((1, repeats, seq_len, seq_len))就行了。
原因我也没有很清楚，可能是后端没有处理好吧。

**Comment by BatterToMe** [comment]
> > 我在构建seq2seq的bert时也出现报错，但是错误不太一样
> > 环境python 3.6.4 Keras 2.3.1 Tensorflow 2.0 bert4keras 0.2.6, OS Ubuntu
> > ValueError: Duplicate node name in graph: 'Attention-Mask/ones/packed'
> > 目测也是seq2seq的mask部分出错，希望楼主或者作者可以给点指导
> > basic_extract_features运行是没问题的
> 
> 这个问题我也遇到过，是在bert.py里这段
> def seq2seq_attention_mask(s, repeats=1):
> import tensorflow as tf
> seq_len = K.shape(s)[1]
> ones = K.ones((1, repeats, seq_len, seq_len))
> a_mask = tf.linalg.band_part(ones, -1, 0)
> s_ex12 = K.expand_dims(K.expand_dims(s, 1), 2)
> s_ex13 = K.expand_dims(K.expand_dims(s, 1), 3)
> a_mask = (1 - s_ex13) * (1 - s_ex12) + s_ex13 * a_mask
> a_mask = K.reshape(a_mask, (-1, seq_len, seq_len))
> return a_mask
> 其中的ones = K.ones((1, repeats, seq_len, seq_len))
> 将K.ones((1, repeats, seq_len, seq_len))改为
> tf.ones((1, repeats, seq_len, seq_len))就行了。
> 原因我也没有很清楚，可能是后端没有处理好吧。

一直报出ones不能处理输入同时包含张量的shape，但是我看后端逻辑是有处理这个问题的，不知道为什么没有运行，而是直接报错

**Comment by bojone** [comment]
如果是这样的话，我加了个name_scope，可以再试试 @Animath3099
