### ISSUE TITLE
get_layer函数找不见源码

### ISSUE THREAD

**Issue by InsaneLife** [bojone/bert4keras#331]
您好，看到例子中有get_layer函数，但是具体代码中没有找到model类的get_layer函数，请问下是废弃或者说更名了吗？

**Comment by i4never** [comment]
`keras.Model.get_layer`

**Comment by bojone** [comment]
> 您好，看到例子中有get_layer函数，但是具体代码中没有找到model类的get_layer函数，请问下是废弃或者说更名了吗？

你在哪里找不到？keras的源码都找完了？

**Comment by InsaneLife** [comment]
> > 您好，看到例子中有get_layer函数，但是具体代码中没有找到model类的get_layer函数，请问下是废弃或者说更名了吗？
> 
> 你在哪里找不到？keras的源码都找完了？

找到了，感谢
