### ISSUE TITLE
加载google albert和albert_small_google_zh错误，提示 Layer weight shape (384, 384) not compatible with provided weight shape (384, 128)

### ISSUE THREAD

**Issue by tiandiweizun** [bojone/bert4keras#36]
https://github.com/bojone/bert4keras/blob/f5741a40092a31df430734a24731f8d24e40cccd/bert4keras/bert.py#L245

加载google的时候，提示attempt to get argmax of an empty sequence，如是我加了个判断，其实根本原因应该是因为进行了pop操作，而hiddern有多层，由于albert参数共享机制，variable_names参数个数严重少于实际情况，导致出错。

由于实际原因，线上往往是旧版本，上个bert2keras挺好的，支持keras2.2，升级到2.3后就如网友说的set_weights的情况，只能舍弃了2.2了。

**Comment by bojone** [comment]
albert_small_google_zh 已经测试加载了很多次了，肯定可以成功加载的。你这个问题，更像是build_bert_model的时候没有设置albert=True参数

**Comment by tiandiweizun** [comment]
确实是那样，谢谢
