### ISSUE TITLE
GlobalPointer 不相容TF2

### ISSUE THREAD

**Issue by haojiunlo** [bojone/bert4keras#362]
https://github.com/bojone/bert4keras/blob/b3c28c3a7219c5a152082b1159af0e828923364d/bert4keras/layers.py#L1199
這邊會導致tf2 
```module 'tensorflow' has no attribute 'matrix_band_part'```
可能要改成tf.linalg.band_part或tf.compat.v1.matrix_band_part

**Comment by bojone** [comment]
好的，感谢指正哈，已经修正
https://github.com/bojone/bert4keras/commit/d068f86b1d5b54f4ec23042686e6bfbed744976c

**Comment by haojiunlo** [comment]
順便感謝作者提供實用工具，收穫良多～
