### ISSUE TITLE
NER可以成批预测数据么

### ISSUE THREAD

**Issue by WMeng1** [bojone/bert4keras#363]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: windows
- 你使用的**Python**版本: 3.7.0
- 你使用的**Tensorflow**版本: 1.15.0
- 你使用的**Keras**版本: 2.2.4
- 你使用的**bert4keras**版本: 0.9.6
- 你使用纯**keras**还是**tf.keras**:keras 
- 你加载的**预训练模型**:albert

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```
因为想提高模型的预测效率，所以想类似分类一样进行批量预测，过程中对NER类的输入进行了类似分类的输入数据拼接进行预测，但是会报错。想请问一下是不能进行批量预测么，还是需要进行一些其它的调整；
    def recognize(self, text):
        tokens_list = list()
        mapping_list = list()
        token_ids_list = list()
        segment_ids_list = list()
        for t in text:
            tokens = tokenizer.tokenize(t)
            tokens_list.append(tokens)
        for tokens in tokens_list:
            while len(tokens) > 512:
                tokens.pop(-2)
            token_ids = tokenizer.tokens_to_ids(tokens)
            token_ids_list.append(token_ids)
        for i in range(len(tokens_list)):
            mapping = tokenizer.rematch(text[i], tokens_list[i])
            mapping_list.append(mapping)
        for token_ids in token_ids_list:
            segment_ids = [0] * len(token_ids)
            segment_ids_list.append(segment_ids)
        for i in range(len(token_ids_list)):
            token_ids, segment_ids = token_ids_list[i], segment_ids_list[i]
            token_ids, segment_ids = to_array([token_ids], [segment_ids])
            token_ids_list[i], segment_ids_list[i] = token_ids, segment_ids
        a = list()
        for i in range(len(token_ids_list)):
            a.append([token_ids_list[i], segment_ids_list[i]])
        nodes = model.predict(a)[0]

### 输出信息
```shell
# 请在此处贴上你的调试输出
```
  File "C:\Users\wangm-s\Anaconda3\lib\site-packages\keras\engine\training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "C:\Users\wangm-s\Anaconda3\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\wangm-s\Anaconda3\lib\site-packages\keras\engine\training_utils.py", line 102, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected.

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by bojone** [comment]
能。自行实现即可。

**Comment by WMeng1** [comment]
已解决，谢谢您的回复

**Comment by rucieryi369** [comment]
> 已解决，谢谢您的回复

请问是怎么处理的呢，谢谢

**Comment by zhuyanshuo183** [comment]
hello，can you share your coding of inference? thans!

**Comment by WMeng1** [comment]
@zhuyanshuo183 @rucieryi369 我这里大概调整成这个样子，时间过去有点久了，可以试一下
`    def recognize(self, text):
        # 当传入text为string时
        if isinstance(text, str):
            # 参数拼接
            temp_text = list()
            temp_text.append(text)
            text = temp_text
        # token与hash映射的list
        tokens_list, mapping_list = list(), list()
        # token_ids, segment_ids的列表
        token_ids_list, segment_ids_list = list(), list()
        # 字符长度列表
        token_len_list = list()
        for t in text:
            tokens = tokenizer.tokenize(t)
            tokens_list.append(tokens)
        for tokens in tokens_list:
            while len(tokens) > 512:
                tokens.pop(-2)
            token_ids = tokenizer.tokens_to_ids(tokens)
            segment_ids = [0] * len(token_ids)
            token_len_list.append(len(token_ids))
            token_ids_list.append(token_ids)
            segment_ids_list.append(segment_ids)
        for i in range(len(tokens_list)):
            mapping = tokenizer.rematch(text[i], tokens_list[i])
            mapping_list.append(mapping)
        token_ids_list, segment_ids_list = to_array(token_ids_list, segment_ids_list)
        # 输入数据可能不等长，通过padding进行列数补齐，注意是在后边补零
        token_ids_list, segment_ids_list = sequence.pad_sequences(token_ids_list, maxlen=maxlen, padding='post'), sequence.pad_sequences(segment_ids_list, maxlen=maxlen, padding='post')
        token_ids_list, segment_ids_list = token_ids_list.tolist(), segment_ids_list.tolist()
        nodes = model.predict([token_ids_list, segment_ids_list])
        # 解码后的预测结果列表
        entities_list = list()
        # 逐个解码预测结果
        for j in range(len(nodes)):
            token_len = token_len_list[j]
            node = nodes[j][:token_len]
            labels = self.decode(node)
            entities, starting = [], False
            for i, label in enumerate(labels):
                if label > 0:
                    if label % 2 == 1:
                        starting = True
                        entities.append([[i], id2label[(label - 1) // 2]])
                    elif starting:
                        entities[-1][0].append(i)
                    else:
                        starting = False
                else:
                    starting = False
            real_entities = [(text[j][mapping_list[j][w[0]][0]:mapping_list[j][w[-1]][-1] + 1], l) for w, l in entities]
            entities_list.append(real_entities)
        return entities_list`
