### ISSUE TITLE
请问bert4keras怎么处理多个batch_labels 和多个loss的处理

### ISSUE THREAD

**Issue by luoqishuai** [bojone/bert4keras#378]
### 核心代码
model构建
```
output=bert.model.output
cls_output = Lambda(lambda x: x[:, 0], name='CLS-token')(bert.model.output) # cls
cls_output_findall= Dense(
    units=num_classes,
    activation='softmax',
    kernel_initializer=bert.initializer,
    name='cls_output'
)(cls_output)

output_layer = 'Transformer-%s-FeedForward-Norm' % (bert_layers - 1)
crf_output = Dense(num_labels)(output)
CRF = ConditionalRandomField(lr_multiplier=crf_lr_multiplier)
crf_output_findall = CRF(crf_output,name='crf_output')

model = tf.keras.models.Model(bert.model.input, outputs=[cls_output_findall, crf_output_findall])

model.compile(optimizer=Adam(1e-5),
              loss={'cls_output': 'categorical_crossentropy', 'crf_output': CRF.dense_loss},
              loss_weights={'cls_output': 1., 'crf_output': 1)
```
data_generator yield是
```[batch_token_ids,batch_token_ids],[batch_classification_labels,batch_ner_labels]```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

以多任务学习为例,一个任务是分类任务一个任务是NER任务.
inputs应该是文本的特征,和 分类标签和NER标签
然后根据不同的特征,计算loss,最后拼接loss(loss怎么对接先不管,假定比例1:1)

请问该怎么利用bert4keras完成这种任务呢?inputs该从哪里进行更具体的处理逻辑和模型该怎么处理?
苏神有大概的方向吗?我对代码的理解比较少,能指点一下吗?
是不是函数式api已经不适用这种任务了,要用Model类来进行?

**Comment by bojone** [comment]
那你现在这样写报了什么错？看上去没啥问题呀。

**Comment by luoqishuai** [comment]
大体上,如果是简单的处理.这个数据输入和,模型构建流程没问题.
当初报的是network错误.
我当时对NER任务的Dense认知不清,直接设置的Dense(num_labels) 应该为 Dense(num_labels*2+1)
还有自己粗心,
crf_output 应该取 'Transformer-%s-FeedForward-Norm' % (bert_layers - 1) 层的output

修改后,即正常. 目前还在跑公开数据集中,看看是什么效果.
后面在看看有没有必要自定义loss 
谢谢苏神@bojone

**Comment by luoqishuai** [comment]
@bojone 苏神,我想自定义loss,需要用到 y_true和 y_pred.
其中y_pred由自己的网络层生成.对应的是:cls_output_findall crf_output_findall
现在还缺y_true,分别找到cls_label,和ner_label

请问我去哪里找到fit时候传入的参数 [batch_classification_labels,batch_ner_labels] 呢
