### ISSUE TITLE
task_iflytek_bert_of_theseus.py中的这行代码没看明白

### ISSUE THREAD

**Issue by SuMeng123** [bojone/bert4keras#379]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**:  linux
- 你使用的**Python**版本:  3.6
- 你使用的**Tensorflow**版本:  1.14
- 你使用的**Keras**版本:  2.3.1
- 你使用的**bert4keras**版本:   0.10.6
- 你使用纯**keras**还是**tf.keras**:  keras
- 你加载的**预训练模型**: 自己预训练的bert模型

### 核心代码
在task_iflytek_bert_of_theseus.py中有这段代码：
```python

# 加载预训练模型（12层）
predecessor = build_transformer_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
    return_keras_model=False,
    prefix='Predecessor-'
)

# 判别模型
# 没有看懂task_iflytek_bert_of_theseus.py中的这段代码，想请教一下哈。
x_in = Input(shape=K.int_shape(predecessor.output)[1:])
x = Lambda(lambda x: x[:, 0])(x_in)
x = Dense(units=num_classes, activation='softmax')(x)
classfier = Model(x_in, x)

```
### 问题
1、没想明白为什么`x_in = Input(shape=K.int_shape(predecessor.output)[1:])`要有`[1:]`

2、如果我换一种写法，改为x_in = Input(shape=K.int_shape(predecessor.model.output))，这样对吗？

### 自我尝试
我在bert4keras/models.py源码，看到
```
    def set_outputs(self, outputs):
        """设置output和oututs属性
        """
        if not isinstance(outputs, list):
            outputs = [outputs]

        outputs = outputs[:]
        self.outputs = outputs
        if len(outputs) > 1:
            self.output = outputs
        else:
            self.output = outputs[0]

```
我理解在build_transformer_model的时候，with_pool、with_nsp、with_mlm都是false，所以在上述函数中 len(outputs) 应该为1，所以执行self.output = outputs[0]。这个时候self.output本身就是bert的main_layers的最后输出了吧，所以我感觉应该写为下式才对，我是哪里想错了呢，麻烦指正一下。
```
x_in = Input(shape=K.int_shape(predecessor.output))
```

**Comment by bojone** [comment]
因为keras会自动补充batch这一维，所以定义Input不用声明batch那一维。。。。
