### ISSUE TITLE
基础类BertModel中，if self.with_mlm 情况下有问题

### ISSUE THREAD

**Issue by jsksxs360** [bojone/bert4keras#39]
bert4keras/bert.py 文件中 `if self.with_mlm` 情况下:
`x = EmbeddingDense(embedding_name='Embedding-Token', activation=self.with_mlm, name='MLM-Proba')(x)` 中的 `activation=self.with_mlm` 语句会报错，
EmbeddingDense 中对应语句为 `self.activation = activations.get(activation)` ，activation 应该为激活函数名称，这里好像传了一个布尔值。

**Comment by bojone** [comment]
请问这是你猜测报错，还是实际运行报错呢？我在EmbeddingDense那里做了判断，传入True也不会报错的，我自己也测过不会报错。

**Comment by jsksxs360** [comment]
你好，实际运行时报错了（Python 3.7.3, tf==1.14, keras==2.3.1）

```
File ".../task_seq2seq.py", line 126, in <module>
    keep_words=keep_words,  # 只保留keep_words中的字，精简原字表
  File ".../bert4keras/bert.py", line 468, in build_bert_model
    bert.build()
  File ".../bert4keras/bert.py", line 140, in build
    name='MLM-Proba')(x)
  File ".../bert4keras/layers.py", line 313, in __init__
    self.activation = activations.get(activation)
  File "/Library/Python/3.7/site-packages/keras/activations.py", line 239, in get
    'activation function identifier:', identifier)
ValueError: ('Could not interpret activation function identifier:', True)
```

**Comment by bojone** [comment]
你直接是不是没更新完整？最新版的layers.py的313行并不是`self.activation = activations.get(activation)`呀

**Comment by jsksxs360** [comment]
好的，确实是这个问题，谢谢！
