### ISSUE TITLE
关于环境组合

### ISSUE THREAD

**Issue by Luffffffy** [bojone/bert4keras#394]
### 基本信息
![image](https://user-images.githubusercontent.com/49063302/133540079-bc70ed1c-dc61-421e-89a0-a02e4fc72c91.png)

### 描述
我不明白这里的组合环境是什么意思，因为当我安装bert4keras的时候，发现自动给我依赖安装了一个keras2.3.1，然后此时直接使用bert4keras，提示找到tensorflow模块，还需要安装tensorflow才可以运行bert4keras，如果安装的tensorflow版本不受兼容或者和原先依赖的keras2.3.1版本不想兼容就会抛出一些异常。

### 提问
1，既然依赖了keras2.3.1，为什么不预装对应的tensorflow版本呢，因为据我所知keras底层应该是依赖tensorflow的
2，如果我自行安装tensorflow，使用tf.keras，是否原先的keras2.3.1可以直接删除

**Comment by bojone** [comment]
1、因为哪怕是keras 2.3.1，可用的tf版本也有很多，没必要统一要求；
2、如果用tf.keras，可以卸载keras 2.3.1。
