### ISSUE TITLE
bert对抗训练FGM,iflytek_adversarial_training问题

### ISSUE THREAD

**Issue by fghg123** [bojone/bert4keras#399]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: colab
- 你使用的**Python**版本: 
- 你使用的**Tensorflow**版本: 尝试过1.14
- 你使用的**Keras**版本: 尝试过2.2，2.3和2.3.1
- 你使用的**bert4keras**版本: 尝试过0.6，0.7,0.10
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:chinese_L-12_H-768_A-12

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```
根据这个链接测试的https://github.com/bojone/bert4keras/blob/master/examples/task_iflytek_adversarial_training.py
### 输出信息
```shell
# 请在此处贴上你的调试输出
```
encode() got an unexpected keyword argument 'maxlen'
### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
一开始是尝试用其它数据集进行bert的对抗训练，一直调试不成功，然后采用和源代码一样的数据集以及代码进行测试看有什么问题，竟然一直出现了encode() got an unexpected keyword argument 'maxlen'，尝试了不同版本的bert4keras，还是一样，不知道什么地方出错了，请帮忙看下是需要怎么调整

**Comment by fghg123** [comment]
经过不断努力，已经找到解决办法了。经过很多版本的迭代，maxlen要修改为max_length,就可以运行了，只是一个epochs需要3个多小时，后面再看看有什么可以优化的地方

**Comment by bigbrother001** [comment]
> Reference

请问你用的什么版本？我的情况恰好相反，我是encode() got an unexpected keyword argument 'max_length'.修改为maxlen后，又报新错ValueError: not enough values to unpack (expected 3, got 2)

**Comment by fghg123** [comment]
来信已收到。                  邓林权

**Comment by bigbrother001** [comment]
> 经过不断努力，已经找到解决办法了。经过很多版本的迭代，maxlen要修改为max_length,就可以运行了，只是一个epochs需要3个多小时，后面再看看有什么可以优化的地方

请问你用的什么版本？我的情况恰好相反，我是encode() got an unexpected keyword argument 'max_length'.修改为maxlen后，又报新错ValueError: not enough values to unpack (expected 3, got 2)

**Comment by fghg123** [comment]
> > 经过不断努力，已经找到解决办法了。经过很多版本的迭代，maxlen要修改为max_length,就可以运行了，只是一个epochs需要3个多小时，后面再看看有什么可以优化的地方
> 
> 请问你用的什么版本？我的情况恰好相反，我是encode() got an unexpected keyword argument 'max_length'.修改为maxlen后，又报新错ValueError: not enough values to unpack (expected 3, got 2)

keras==2.3    bert4keras==0.6.0
这个是当初研究对抗训练的版本，我记得逻辑是这样的，你看下你自己的版本是多少，然后去苏神的源代码里看一下用的是max_length还是什么命名
你的新报错因为我还没看过代码。目前估计是数据集的问题，你可以先弄一个可以跑通的版本后再加对抗训练，会好一些
