### ISSUE TITLE
load_pretrained_model加载参数时出现error，怎么回事？

### ISSUE THREAD

**Issue by ccteeya** [bojone/bert4keras#4]
You called `set_weights(weights)` on layer "Encoder-1-MultiHeadSelfAttention" with a weight list of length 8, but the layer was expecting 16 weights. Provided weights: [array([[-0.01839516, -0.02298158,  0.07288713, .....

报错如上。
求大佬帮助

**Comment by bojone** [comment]
bert和albert权重我都试过了，没有错误。麻烦你提供更详细的信息。

**Comment by ccteeya** [comment]
苏老师你好！
  今天看到您的github上看到您重写的keras4bert，于是：
  1.pip install git+https://www.github.com/bojone/bert4keras.git
 2.下载albert_base_zh

 3.下载您github上的dataset以及task_sentiment_albert.py
环境：Keras2.3 + jupyter



运行后发现报错，看了一下源码，但是自己是小白，所以只能来问您。
下面附上附件。



能收到苏老师的回复非常开心！！！



------------------ 原始邮件 ------------------
发件人: "苏剑林(Jianlin Su)"<notifications@github.com>;
发送时间: 2019年10月7日(星期一) 下午5:19
收件人: "bojone/bert4keras"<bert4keras@noreply.github.com>;
抄送: "陈天宇"<656308023@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [bojone/bert4keras] load_pretrained_model加载参数时出现error，怎么回事？ (#4)




bert和albert权重我都试过了，没有错误。麻烦你提供更详细的信息。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

examples.rar (1.74M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=796566333729d0ce0f1278141137061e5d57520b030356041507560b031a00030b514b0a550e571c0f5153020e560302015d5055373b345440040b435b52471f4a0414330a&t=exs_ftn_download&code=8ef37741

**Comment by bojone** [comment]
客气了。

目前发现是keras 2.3.0的问题，你先用keras 2.2.5及之前的版本吧，我正在想办法修复。

**Comment by ccteeya** [comment]
好的，我把keras降一下版本。建议苏神以后用python3，哈哈哈哈，牺牲小我，方便大伙




------------------ 原始邮件 ------------------
发件人: "苏剑林(Jianlin Su)"<notifications@github.com>;
发送时间: 2019年10月7日(星期一) 晚上8:10
收件人: "bojone/bert4keras"<bert4keras@noreply.github.com>;
抄送: "陈天宇"<656308023@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [bojone/bert4keras] load_pretrained_model加载参数时出现error，怎么回事？ (#4)




客气了。
 
目前发现是keras 2.3.0的问题，你先用keras 2.2.5及之前的版本吧，我正在想办法修复。

**Comment by bojone** [comment]
已经兼容好Keras 2.3.x了

**Comment by xxllp** [comment]
我这边还是报错哈  python3.6

**Comment by bojone** [comment]
@xxllp 报错就提新issue，附上详细报错信息，不要就说一句报错～
