### ISSUE TITLE
如何正确地在vocab里增加一些token？

### ISSUE THREAD

**Issue by mocorr** [bojone/bert4keras#408]
### 基本情况
bert4keras==0.10.8

### 问题
希望在现有的预训练模型（比如simbert或bert）权重的基础上finetune，
并在vocab中增加一些中英文词汇，
但因为需要增加的词汇个数超过[unused]的个数，
所以需要增加整个vocab的长度，而非直接替换现有的[unused]。

### 自我尝试
尝试过直接在vocab最后增加了一些词，训练能跑起来，但loss会变成nan。
猜测是新增token对应的embedding没有正确初始化？
（补充：我又看了一下model的summary，MLM-Activation (Activation) 和 MLM-Bias (BiasAdd) 的 outputshape，对应的维度都还是原来的词表长度。也就是说我只是按原来的vocab_size加载了预训练模型，但我不知道该怎么在加载之后，让model知道vocab_size变化了。）

通过阅读本项目的源码、issue、您的博客，了解到
①中文以及特殊符号开头的token，需要通过Tokenizer的pre_token进行处理，该问题已自行解决。
②transformers包里，向vocab里添加自己的词汇需要对tokenizer做一个add_tokens的操作，且对model使用resize_token_embeddings。
我在您bert4keras的源码里的transformer基类找到一个compound_token的参数，看起来似乎也是向embedding中增加新的token？但我不知道该如何正确使用。

**Comment by mocorr** [comment]
又努力理解了一下compound_token相关的源码
感觉它的作用应该是 新增token，并用现有tokens的embedding对其初始化，不知道这样理解对不对？
基于此理解，我随机为我待新增的token各选择了一些embedding进行初始化，现在能正常训练了。
但不知道针对我本来的需求，是不是有更合适的做法？

**Comment by bojone** [comment]
1、在vocab.txt后面追加你所需要的token，假设追加了16个；

2、build_transformer_model的时候，传入compound_tokens参数：compound_tokens是一个list，长度为16；list里边的每个item也是一个list，长度不定，里边的元素则是int，代表用这些int代表的token的embedding的平均来初始化新的token的embedding。

为什么要“平均”这种操作？主要是之前实现WoBERT的时候，追加了新词，所以考虑用词的各个字Embeding的平均来初始化词。如果你的token跟字没有什么特殊关系，可以全部用[UNK]初始化就行。

**Comment by mocorr** [comment]
> 1、在vocab.txt后面追加你所需要的token，假设追加了16个；
> 
> 2、build_transformer_model的时候，传入compound_tokens参数：compound_tokens是一个list，长度为16；list里边的每个item也是一个list，长度不定，里边的元素则是int，代表用这些int代表的token的embedding的平均来初始化新的token的embedding。
> 
> 为什么要“平均”这种操作？主要是之前实现WoBERT的时候，追加了新词，所以考虑用词的各个字Embeding的平均来初始化词。如果你的token跟字没有什么特殊关系，可以全部用[UNK]初始化就行。
> 
> 内置的方法里边，标准的操作就是这样了。其他方法（比如自定义随机初始化新词）都需要修改bert4keras源码了～

非常感谢您的解答~

**Comment by songsa1** [comment]
> 1、在vocab.txt后面追加你所需要的token，假设追加了16个；
> 
> 2、build_transformer_model的时候，传入compound_tokens参数：compound_tokens是一个list，长度为16；list里边的每个item也是一个list，长度不定，里边的元素则是int，代表用这些int代表的token的embedding的平均来初始化新的token的embedding。
> 
> 为什么要“平均”这种操作？主要是之前实现WoBERT的时候，追加了新词，所以考虑用词的各个字Embeding的平均来初始化词。如果你的token跟字没有什么特殊关系，可以全部用[UNK]初始化就行。
> 
> 内置的方法里边，标准的操作就是这样了。其他方法（比如自定义随机初始化新词）都需要修改bert4keras源码了～

苏神您好，请问这个能给出一个示例出来吗？感激不尽

**Comment by halfbottles** [comment]
用上述方法修改词表之后，如何把这个修改固定下来呢，阅读源码，b4k中似乎没有保存词表的方法
