### ISSUE TITLE
keras和bert4keras导包顺序不同导致keras版本也出现变化

### ISSUE THREAD

**Issue by Kalafinaian** [bojone/bert4keras#409]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: centos 7.6.1810
- 你使用的**Python**版本: 3.6.4
- 你使用的**Tensorflow**版本: 1.15.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.10.8 
- 你使用纯**keras**还是**tf.keras**:  keras
- 你加载的**预训练模型**: 无

### 核心代码
```python
import os
import warnings
import numpy as np
import tensorflow as tf
# Part1
import keras
from keras.layers import Layer,Embedding, Dense, Dropout, Input, Bidirectional, LSTM
from keras.models import Model
# Part 2
import bert4keras
from bert4keras.models import build_transformer_model
from bert4keras.tokenizers import Tokenizer
from bert4keras.snippets import to_array

print("tf ", tf.__version__)
print("keras ", keras.__version__)
print("bert4keras ", bert4keras.__version__)
```

```python
import os
import warnings
import numpy as np
import tensorflow as tf
# Part1
import bert4keras
from bert4keras.models import build_transformer_model
from bert4keras.tokenizers import Tokenizer
from bert4keras.snippets import to_array
# Part 2
import keras
from keras.layers import Layer,Embedding, Dense, Dropout, Input, Bidirectional, LSTM
from keras.models import Model

print("tf ", tf.__version__)
print("keras ", keras.__version__)
print("bert4keras ", bert4keras.__version__)
```
### 输出信息
前者输出
```shell
tf  1.15.0
keras  2.3.1
bert4keras  0.10.8
```
后者输出
```shell
tf  1.15.0
keras  2.2.4-tf
bert4keras  0.10.8
```

### 自我尝试
无法解决

**Comment by bojone** [comment]
这个现象出现的前提，是你设置了TF_KERAS=1的全局变量，说明你想使用tf.keras。

在这个前提下，你的第一种用法就是非法操作，因为你明明想用tf.keras，你导入keras的函数干嘛？

至于第二种用法，因为你先导入了bert4keras，bert4keras识别到你想用tf.keras，所以强行把keras的路径指到了tf.keras，结果就是你使用`import keras`的结果实际上相当于`from tensorflow import keras`，目的就是最大程度上防止你的第一种非法操作。

**Comment by Kalafinaian** [comment]
> 这个现象出现的前提，是你设置了TF_KERAS=1的全局变量，说明你想使用tf.keras。
> 
> 在这个前提下，你的第一种用法就是非法操作，因为你明明想用tf.keras，你导入keras的函数干嘛？
> 
> 至于第二种用法，因为你先导入了bert4keras，bert4keras识别到你想用tf.keras，所以强行把keras的路径指到了tf.keras，结果就是你使用`import keras`的结果实际上相当于`from tensorflow import keras`，目的就是最大程度上防止你的第一种非法操作。

查看了os系统变量不知什么时候持久化成了TF_KERAS=1，但不想用tf.keras，只能手动修改 os.environ["TF_KERAS"]='0'

**Comment by liyunhan** [comment]
> 这个现象出现的前提，是你设置了TF_KERAS=1的全局变量，说明你想使用tf.keras。
> 
> 在这个前提下，你的第一种用法就是非法操作，因为你明明想用tf.keras，你导入keras的函数干嘛？
> 
> 至于第二种用法，因为你先导入了bert4keras，bert4keras识别到你想用tf.keras，所以强行把keras的路径指到了tf.keras，结果就是你使用`import keras`的结果实际上相当于`from tensorflow import keras`，目的就是最大程度上防止你的第一种非法操作。

那请问苏神如果项目全部使用tf.keras（即指定TF_KERAS=1），是不是就可以使用tensorflow2.3及其以上版本了呢？即不单独安装keras，只安装tensorflow2.3以上版本+bert4keras就好
