### ISSUE TITLE
extend_with_piecewise_linear_lr 没有生效

### ISSUE THREAD

**Issue by stevewyl** [bojone/bert4keras#426]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Ubuntu 20.04
- 你使用的**Python**版本: 3.7.0
- 你使用的**Tensorflow**版本: 1.15.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.10.8
- 你使用纯**keras**还是**tf.keras**: keras
- 你加载的**预训练模型**: chinese_rbtl3_L-3_H-1024_A-16和albert_zh_base

### 核心代码

尝试使用线性分段递减学习率进行模型训练，打印每个step优化器的学习率，发现没有变化

```python
AdamLR = extend_with_piecewise_linear_lr(Adam, name='AdamLR')
# 第一个epoch增大到100%，接着第三个epoch降低到50%，在第5个epoch降低到10%，最后维持在10%
lr_schedule = {len(train_generator): 1, len(train_generator) * 3: 0.5, len(train_generator) * 5: 0.1}
optimizer = AdamLR(learning_rate=5e-5, lr_schedule=lr_schedule)
# 在Evaluator中加入on_batch_end方法，验证线性分段递减学习率正常工作
def on_batch_end(self, batch, logs=None):
      print(f"Step [{batch}] learning_rate: {K.get_value(self.model.optimizer.lr)}")
```
### 输出信息

验证lr_schedule是否正确
![1639116323(1)](https://user-images.githubusercontent.com/12755003/145525629-398cd5fc-22d6-4d4a-9196-d0199b506759.png)
每个step打印的优化器的学习率变化
![1639116215(1)](https://user-images.githubusercontent.com/12755003/145525316-da170b40-7b29-476a-abe8-3b13229a7df2.png)

### 自我尝试

修改为keras自带的callback，验证学习率是否能在训练过程中被修改
```python
def scheduler(epoch, lr):
      if epoch < 1:
          return lr
      else:
          return lr * np.exp(-0.1)
lr_scheduler = keras.callbacks.LearningRateScheduler(scheduler)
```
LearningRateScheduler学习率变化情况，变化符合预期
![1639116725(1)](https://user-images.githubusercontent.com/12755003/145526140-38b83f82-3f82-45fd-bc42-62733ecd7a62.png)

查看bert4keras中调用extend_with_piecewise_linear_lr的代码示例：examples/task_sentiment_albert.py
只在Evaluator中增加如下代码以查看每个step的学习率变化，发现学习率保持不变，不符合预期
```python
def on_batch_end(self, batch, logs=None):
      print(f"Step [{batch}] learning_rate: {K.get_value(self.model.optimizer.lr)}")
```
![1639116885(1)](https://user-images.githubusercontent.com/12755003/145526413-bffb470f-ea38-4927-821e-d33463a76fe7.png)

于是尝试基于Keras的callbacks基类和苏神实现的分段线性函数，动手实现了下分段线性学习率
```python
def piecewise_linear(t, schedule, from_zero=True):
    """分段线性函数
    其中schedule是形如{1000: 1, 2000: 0.1}的字典，
    表示 t ∈ [0, 1000]时，输出从0均匀增加至1，而
    t ∈ [1000, 2000]时，输出从1均匀降低到0.1，最后
    t > 2000时，保持0.1不变。
    """
    schedule = sorted(schedule.items())
    if from_zero and schedule[0][0] != 0:
        schedule = [(0, 0.0)] + schedule

    x = (t * 0 + 1) * schedule[0][1]
    for i in range(len(schedule)):
        t_begin = schedule[i][0]
        x_begin = x
        if i != len(schedule) - 1:
            dx = schedule[i + 1][1] - schedule[i][1]
            dt = schedule[i + 1][0] - schedule[i][0]
            slope = 1.0 * dx / dt
            x = schedule[i][1] + slope * (t - t_begin)
        else:
            x = (t * 0 + 1) * schedule[i][1]
        if t < t_begin:
            x = x_begin

    return x

class LRLinearPiecewiseScheduler(Callback):
    """带有分段线性学习率的优化器

    # Arguments
        schedule: 形如{1000: 1, 2000: 0.1}的字典，
        表示0～1000步内学习率线性地从零增加到100%，然后
        1000～2000步内线性地降到10%，2000步以后保持10%
        verbose: int. 0: quiet, 1: update messages.
    """

    def __init__(self, lr, schedule, verbose=0):
        super(LRLinearPiecewiseScheduler, self).__init__()
        self.base_lr = lr
        self.lr_schedule = schedule
        self.verbose = verbose
        self.steps = 1

    def on_batch_begin(self, batch, logs=None):
        lr_multiplier = piecewise_linear(self.steps, self.lr_schedule)
        lr = lr_multiplier * self.base_lr
        if not isinstance(lr, (float, np.float32, np.float64)):
            raise ValueError('The output of the "schedule" function '
                            'should be float.')
        K.set_value(self.model.optimizer.lr, lr)
        if self.verbose > 0:
            print('\Step %05d: LRLinearPiecewiseScheduler setting learning '
                  'rate to %s.' % (self.steps, lr))
        self.steps += 1

    def on_batch_end(self, batch, logs=None):
        logs = logs or {}
        logs['lr'] = K.get_value(self.model.optimizer.lr)
```

学习率变化符合预期
第一个epoch结束，学习率从0变化到5e-5，第三个epoch结束，学习率为原有的学习率的0.5，之后学习率保持原有学习率的0.1
![1639122813(1)](https://user-images.githubusercontent.com/12755003/145537496-105b0914-1073-40fd-8069-2c19338db19f.png)

**Comment by bojone** [comment]
首先，搞清楚一件事：`extend_with_piecewise_linear_lr`有没有生效，跟`self.model.optimizer.lr`有没有改变，没有什么必然关系。

只要稍微读一下`extend_with_piecewise_linear_lr`的源码，就会知道`extend_with_piecewise_linear_lr`生效时，`self.model.optimizer.lr`是不会改变的。`extend_with_piecewise_linear_lr`直接使得更新量做相应的缩放，不用显式改变`extend_with_piecewise_linear_lr`。
