### ISSUE TITLE
pretraining的data_utils.py运行出错

### ISSUE THREAD

**Issue by zhenshiqi1996** [bojone/bert4keras#431]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**:  cent os
- 你使用的**Python**版本: 3.6
- 你使用的**Tensorflow**版本: tensorflow-gpu==1.14.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.10.8
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**: 

### 核心代码
```python
    def some_texts():
        filename = './data/leida/content.txt'
        f = open(filename,'r',encoding='utf-8')
        count, texts = 0, []
        for l in f.readlines():
            l = l.strip()
            if not l:
                continue
            texts.extend(re.findall(u'.*?[\n。.]+', l))
            count += 1
            if count == 10:  # 10篇文章合在一起再处理
                yield texts
                count, texts = 0, []
        if texts:
            yield texts
```

### 输出信息
```shell
Building prefix dict from the default dictionary ...
Loading model from cache /data/biggertmp/jieba.cache
Loading model cost 0.942 seconds.
Prefix dict has been built succesfully.
1740it [00:00, 2174.62it/s]
Traceback (most recent call last):
  File "data_utils.py", line 385, in <module>
    max_queue_size=max_queue_size,
  File "data_utils.py", line 126, in process
    callback=write_to_tfrecord,
  File "/root/miniconda3/envs/tf1.14/lib/python3.6/site-packages/bert4keras/snippets.py", line 295, in parallel_apply
    callback(d)
  File "data_utils.py", line 114, in write_to_tfrecord
    writer.write(serialized_instance)
  File "/root/miniconda3/envs/tf1.14/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py", line 236, in write
    self._writer.WriteRecord(record, status)
  File "/root/miniconda3/envs/tf1.14/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 905, in WriteRecord
    return _pywrap_tensorflow_internal.PyRecordWriter_WriteRecord(self, record, out_status)
TypeError: expected bytes, int found
```
就改了所贴代码部分（输入的文本，一行一段话），其他部分都没动，请问怎么解决？

**Comment by zhenshiqi1996** [comment]
> 提问时请尽可能提供如下信息：
> 
> ### 基本信息
> * 你使用的**操作系统**:  cent os
> * 你使用的**Python**版本: 3.6
> * 你使用的**Tensorflow**版本: tensorflow-gpu==1.14.0
> * 你使用的**Keras**版本: 2.3.1
> * 你使用的**bert4keras**版本: 0.10.8
> * 你使用纯**keras**还是**tf.keras**:
> * 你加载的**预训练模型**:
> 
> ### 核心代码
> ```python
>     def some_texts():
>         filename = './data/leida/content.txt'
>         f = open(filename,'r',encoding='utf-8')
>         count, texts = 0, []
>         for l in f.readlines():
>             l = l.strip()
>             if not l:
>                 continue
>             texts.extend(re.findall(u'.*?[\n。.]+', l))
>             count += 1
>             if count == 10:  # 10篇文章合在一起再处理
>                 yield texts
>                 count, texts = 0, []
>         if texts:
>             yield texts
> ```
> 
> ### 输出信息
> ```shell
> Building prefix dict from the default dictionary ...
> Loading model from cache /data/biggertmp/jieba.cache
> Loading model cost 0.942 seconds.
> Prefix dict has been built succesfully.
> 1740it [00:00, 2174.62it/s]
> Traceback (most recent call last):
>   File "data_utils.py", line 385, in <module>
>     max_queue_size=max_queue_size,
>   File "data_utils.py", line 126, in process
>     callback=write_to_tfrecord,
>   File "/root/miniconda3/envs/tf1.14/lib/python3.6/site-packages/bert4keras/snippets.py", line 295, in parallel_apply
>     callback(d)
>   File "data_utils.py", line 114, in write_to_tfrecord
>     writer.write(serialized_instance)
>   File "/root/miniconda3/envs/tf1.14/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py", line 236, in write
>     self._writer.WriteRecord(record, status)
>   File "/root/miniconda3/envs/tf1.14/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 905, in WriteRecord
>     return _pywrap_tensorflow_internal.PyRecordWriter_WriteRecord(self, record, out_status)
> TypeError: expected bytes, int found
> ```
> 
> 就改了所贴代码部分（输入的文本，一行一段话），其他部分都没动，请问怎么解决？

bert4keras版本改为0.8.4就解决了

**Comment by bojone** [comment]
> > 提问时请尽可能提供如下信息：
> > ### 基本信息
> > 
> > * 你使用的**操作系统**:  cent os
> > * 你使用的**Python**版本: 3.6
> > * 你使用的**Tensorflow**版本: tensorflow-gpu==1.14.0
> > * 你使用的**Keras**版本: 2.3.1
> > * 你使用的**bert4keras**版本: 0.10.8
> > * 你使用纯**keras**还是**tf.keras**:
> > * 你加载的**预训练模型**:
> > 
> > ### 核心代码
> > ```python
> >     def some_texts():
> >         filename = './data/leida/content.txt'
> >         f = open(filename,'r',encoding='utf-8')
> >         count, texts = 0, []
> >         for l in f.readlines():
> >             l = l.strip()
> >             if not l:
> >                 continue
> >             texts.extend(re.findall(u'.*?[\n。.]+', l))
> >             count += 1
> >             if count == 10:  # 10篇文章合在一起再处理
> >                 yield texts
> >                 count, texts = 0, []
> >         if texts:
> >             yield texts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 输出信息
> > ```shell
> > Building prefix dict from the default dictionary ...
> > Loading model from cache /data/biggertmp/jieba.cache
> > Loading model cost 0.942 seconds.
> > Prefix dict has been built succesfully.
> > 1740it [00:00, 2174.62it/s]
> > Traceback (most recent call last):
> >   File "data_utils.py", line 385, in <module>
> >     max_queue_size=max_queue_size,
> >   File "data_utils.py", line 126, in process
> >     callback=write_to_tfrecord,
> >   File "/root/miniconda3/envs/tf1.14/lib/python3.6/site-packages/bert4keras/snippets.py", line 295, in parallel_apply
> >     callback(d)
> >   File "data_utils.py", line 114, in write_to_tfrecord
> >     writer.write(serialized_instance)
> >   File "/root/miniconda3/envs/tf1.14/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py", line 236, in write
> >     self._writer.WriteRecord(record, status)
> >   File "/root/miniconda3/envs/tf1.14/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 905, in WriteRecord
> >     return _pywrap_tensorflow_internal.PyRecordWriter_WriteRecord(self, record, out_status)
> > TypeError: expected bytes, int found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 就改了所贴代码部分（输入的文本，一行一段话），其他部分都没动，请问怎么解决？
> 
> bert4keras版本改为0.8.4就解决了

嗯，退回一个版本应该就行了（0.10.7），最新版（0.10.8）的多进程忘记向后兼容了，目前的GitHub上的版本已经修正，但还没有打包发布。
