### ISSUE TITLE
提问帖：snippets.sequence_padding方法length和seq_dims作用

### ISSUE THREAD

**Issue by tiandiweizun** [bojone/bert4keras#457]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: windows
- 你使用的**Python**版本: 3.6
- 你使用的**Tensorflow**版本:1.13 
- 你使用的**Keras**版本: 
- 你使用的**bert4keras**版本: 
- 你使用纯**keras**还是**tf.keras**: 
- 你加载的**预训练模型**:

### 我的疑问

1. 对于常规的使用，seq_dims=1，如bert4keras项目examples文件夹下的例子，都是得到形如：batch_size * sequence_length的结果
2. 那么对于seq_dims=2的情况，是为了处理2维数据吗？比如把图片padding到batch_size * height * width，是这样吗？

期待您的讲解

**Comment by bojone** [comment]
目前的场景是我用globalpointer的时候，标签矩阵是[batch_size, seq_len, seq_len]的，所以需要多个维度来padding
