### ISSUE TITLE
除去mask后剩下部分的loss权重

### ISSUE THREAD

**Issue by ccchang0111** [bojone/bert4keras#46]
https://github.com/bojone/bert4keras/blob/369f7d4c038e7728ab99f45f9866b922456bb269/pretraining/roberta/pretraining.py#L83-L84

想請問一下有reference說這麼做會比原來的Bert還stable嗎，還是case by case 要自己試看看呢？

**Comment by bojone** [comment]
我正在做对比实验，还没有对比结果，这里只是提供一个可选参数

**Comment by ccchang0111** [comment]
滿有趣的想法, 大家有機會也可以測試看看
