### ISSUE TITLE
在padding部分减去一个大正数

### ISSUE THREAD

**Issue by ccchang0111** [bojone/bert4keras#47]
想請問一下，在attention matrix裡，為什麼要把Pad㵴去一個大正數呢？這樣會使attention matrix裡padding部分變的很負。如果選`mode=0`效果不好嗎？
https://github.com/bojone/bert4keras/blob/a993fc67ec213647a4c66ec59270f15b3a2671a2/bert4keras/layers.py#L106-L107

感謝苏神！

**Comment by bojone** [comment]
https://kexue.fm/archives/6810#Mask

**Comment by ccchang0111** [comment]
謝謝 好聰明 獲益良多！

所以主要是看下一層是做什麼，如果是般linear loss, 就選`mode=0`, 讓padding部分乘上0。
如果下一層有用到exp(x) 像是softmax, 就把padding變的超負，這樣exp(超負) ~ 0.
