### ISSUE TITLE
extend_with_gradient_accumulation cause OOM

### ISSUE THREAD

**Issue by hanggun** [bojone/bert4keras#477]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**:  windows
- 你使用的**Python**版本:  3.7.13
- 你使用的**Tensorflow**版本:  1.15.0
- 你使用的**Keras**版本:  2.3.1
- 你使用的**bert4keras**版本:  0.11.3
- 你使用纯**keras**还是**tf.keras**:  纯keras
- 你加载的**预训练模型**:  chinese_L-12_H-768_A-12

### 核心代码
```python
AdamG = extend_with_gradient_accumulation(Adam, 'AdamG')
model.compile(
    loss=global_pointer_crossentropy,
    # optimizer=Adam(learning_rate),
    optimizer=AdamG(learning_rate, grad_accum_steps=4),
    metrics=[global_pointer_f1_score]
)
```

### 输出信息
```shell
Resource exhausted: OOM when allocating tensor with shape[768,3072] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node training/AdamG/Square_191}}]]
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

苏神你好，在您写的CLUENER_GlobalPointer中，我想使用accumulate_grad进行训练，但是一直出现OOM的情况，我是使用1060 6G的显卡进行训练的，在原始代码下可以运行batch_size=16，但是使用extend_with_gradient_accumulation之后，连batch_size=4都会造成OOM，我猜测是因为保存了多个gradient导致的，看bert4keras.optimizer.extend_with_gradient_accumulation发现self.accum_grads是一直存在的，请问是因为这个原因么，谢谢指教~

**Comment by bojone** [comment]
梯度累积需要新建一组变量来缓存梯度，理论上是需要更多的显存。但是你说batch_size从16到4都不行，我就不大确定什么问题了，印象中不至于新增那么多显存消耗。
