### ISSUE TITLE
预训练，求助，大神，菜菜，捞捞

### ISSUE THREAD

**Issue by flymushroom** [bojone/bert4keras#478]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Ubuntu
- 你使用的**Python**版本: 3.7
- 你使用的**Tensorflow**版本:1.14 
- 你使用的**Keras**版本: 2.31
- 你使用的**bert4keras**版本:0.11 
- 你使用纯**keras**还是**tf.keras**:tf.keras 
- 你加载的**预训练模型**:选的none，加载也试过，都不行

### 核心代码
```python
没改动啥，就动了一些参数，把batchsize啥的都改的很小想运行一下
```

### 输出信息
![image](https://user-images.githubusercontent.com/90736820/175918554-cf6b06e6-6193-42ce-b247-2a4451a669d1.png)

### 自我尝试
去网上百度过了，然后自己windows也又装了一次，cuda10.0的tf1.14，cuda10.1的tf2.2，都有尝试，还是报错，网上也没看到有效信息。本人比较菜。望大神嫌弃地甩一个解决方式扇我脸上，万分感谢

**Comment by flymushroom** [comment]
我知道了。。之前的tfrecord有问题，但是我又遇到了一个新的搜了好几遍没解决的问题。。求路过的大神懂的指点一
![Snipaste_2022-06-28_18-10-28](https://user-images.githubusercontent.com/90736820/176154745-af44fc59-e8a0-455c-b0a7-6a8ba049e6a8.png)
下

**Comment by flymushroom** [comment]
没问题了。放服务器就没报错了。打扰各位大佬了

**Comment by flymushroom** [comment]
顺便有个问题，生成pretraining的data时候maskid+1，是因为把0充当占位符，所以往后挤了一位吗

**Comment by bojone** [comment]
> 顺便有个问题，生成pretraining的data时候maskid+1，是因为把0充当占位符，所以往后挤了一位吗

是的。但后面会还原回来的。
