### ISSUE TITLE
模型保存和加载Unknown optimizer: new_optimizer

### ISSUE THREAD

**Issue by shichengcn** [bojone/bert4keras#48]
您好，在examples/task_sentiment_albert.py中使用
`
model.save_weights
`
`
model.load_weights
`
不会有问题，当使用
`
model.save("test.hdf5", overwrite=True, include_optimizer=True)
`
`
test_model = load_model("test.hdf5")
`
报错
_deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown optimizer: new_optimizer_
如果把loss改掉，或者include_optimizer=False能解决这个问题，不知道这是否是一个需要优化的地方。

**Comment by bojone** [comment]
目前来说确实是一个不好解决的问题。

**Comment by bojone** [comment]
原来此问题当初已经解决过，只需要在`extend_with`新优化器的时候，传入name参数即可，比如
```python
AdamLR = extend_with_piecewise_linear_lr(Adam, 'AdamLR')
```
这样使用AdamLR来`compile`，然后`model.save`并`load_model`，就不会报`Unknown optimizer: new_optimizer`了

**Comment by liuchenbaidu** [comment]
python 3.6
bert4keras 0.8.1
model.save("test.h5", overwrite=True, include_optimizer=True)
然后load_model时候出现
ValueError: Unknown optimizer: AdamLR
