### ISSUE TITLE
由于版本原因需要使用keras2.2.4

### ISSUE THREAD

**Issue by LucasJau** [bojone/bert4keras#49]
您能指点下哪里需要修改吗？感恩~

**Comment by bojone** [comment]
将layers.py里边包含“层中层”的所有层全部重写。

**Comment by LucasJau** [comment]
> 将layers.py里边包含“层中层”的所有层全部重写。

谢谢啦~

**Comment by bojone** [comment]
早上参考keras 2.3实现了一下，目前应该可以兼容2.2.4了，欢迎测试
