### ISSUE TITLE
bert4keras0.11.4版本加载GAU模型报错

### ISSUE THREAD

**Issue by tianyunzqs** [bojone/bert4keras#494]
bert4keras0.11.4加载GAU模型会报错，降到0.11.3版本就正常了~

报错信息：  
ValueError: Shapes (128,) and (1536, 768) are incompatible

加载代码：  
```
pre_model = build_transformer_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
    model=GAU_alpha,
    return_keras_model=False
)
```
GAU_alpha模型：  
https://github.com/ZhuiyiTechnology/GAU-alpha

**Comment by bojone** [comment]
已经修复。https://github.com/ZhuiyiTechnology/GAU-alpha/commit/f21e819f34995efff43e4f31cb555dd080dd12d0
