### ISSUE TITLE
parallel_apply多线程出错

### ISSUE THREAD

**Issue by nihuizhidao** [bojone/bert4keras#50]
windows环境下报了个错：

> Connected to pydev debugger (build 193.5662.61)
> 2019-12-24 11:52:07.952336: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
> 构建词汇表中: 0it [00:00, ?it/s]Traceback (most recent call last):
>   File "D:\Anaconda3\envs\tf2\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
>     reduction.dump(process_obj, to_child)
>   File "D:\Anaconda3\envs\tf2\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> AttributeError: Can't pickle local object 'parallel_apply.<locals>.worker_step'
> 2019-12-24 11:52:13.359467: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
> Traceback (most recent call last):
>   File "D:\Anaconda3\envs\tf2\lib\multiprocessing\spawn.py", line 115, in _main
>     self = reduction.pickle.load(from_parent)
> EOFError: Ran out of input

但是Ubuntu下不会报错，这个是为啥？

**Comment by bojone** [comment]
就是这种写法不支持windows的意思～～

**Comment by nihuizhidao** [comment]
> 就是这种写法不支持windows的意思～～

秒回啊。。。

好吧，那不用windows了。。。对了，我还有个问题，`seq2seq`时，用`tfrecord`，指定了`fixed length`的类型后，是不是不需要再用`sequence__padding`了?因为 `FixedLenFeature = tf.io.FixedLenFeature([sequence_length], tf.int64) `已经指定了`sequence_length`？

**Comment by bojone** [comment]
1、parallel_apply那里，如果非得用windows的话，可以考虑在parallel_apply中传入参数dummy=True，这样应该能跑，但是会慢一些；

2、你就算用FixedLenFeature，好像也得自己把单个样本向量padding好吧？（我对tfrecord其实不熟悉）。

**Comment by nihuizhidao** [comment]
1、好吧，那不纠结parallel_apply了

2、对单个样本向量padding的话会不会对准确率有影响啊，因为之前没用tfrecord的时候，我们用的是sequence_padding，是取一个batch里最大的长度padding。。。

**Comment by bojone** [comment]
padding多少个0都不会有影响的呀，模型会自动排除padding部分的影响，最终等价于没有padding。

**Comment by nihuizhidao** [comment]
哦哦，这样啊，谢谢大佬~
