### ISSUE TITLE
where is the function "_set_hyper" in class LionV2

### ISSUE THREAD

**Issue by focox** [bojone/bert4keras#510]
where is the "_set_hyper" function in class LionV2

**Comment by bojone** [comment]
From the base class `Optimizer`

**Comment by focox** [comment]
My version of keras is 2.3.1, I still can not  find the function under the keras.optimizers.Optimizer.

**Comment by focox** [comment]
I got the solution, thx.

**Comment by bojone** [comment]
Add environment variable `TF_KERAS=1`

**Comment by focox** [comment]
Yes, there you are.
