### ISSUE TITLE
Tokenizer.load_vocab加载词典特需字符的问题

### ISSUE THREAD

**Issue by tiandiweizun** [bojone/bert4keras#52]
我在python3环境下，使用load_vocab，codecs在处理vocab.txt时候，第13504和344行字符（对应的id为13503和343）的时候都会被处理成空格，但是python的open没有这个问题，这个小问题主要是我再次保存词典的时候，发现少了一行

**Comment by bojone** [comment]
感谢，感谢反馈，着手修复中。
