### ISSUE TITLE
可否在readme添加下bert4torch的链接

### ISSUE THREAD

**Issue by Tongjilibo** [bojone/bert4keras#520]
苏神您好，之前参考bert4keras写了对应的pytorch版[bert4torch](https://github.com/Tongjilibo/bert4torch), 方不方便在bert4keras的readme中添加下该项目链接呢？按照您自己的意愿来就可以了:)
ps. 知道苏神之前不太喜欢使用pytorch

**Comment by bojone** [comment]
应该的，已经加上
