### ISSUE TITLE
如何取出某一层的输出 作为特征？

### ISSUE THREAD

**Issue by bestpredicts** [bojone/bert4keras#55]
试了下面的方法，报错 不知道是不是姿势不对， 如果可以的话 ，望老师解答一下
`  

  bert = build_bert_model(
        config_path=config_path,
        checkpoint_path=checkpoint_path,
        with_pool=False,
        return_keras_model=True )
  
    x1= K.function([bert.layers[0].input],
                                  [bert.layers[-2].output])
    
    x2 = K.function([bert.layers[0].input],
                                  [bert.layers[-3].output])
    
`

**Comment by bojone** [comment]
```
bert.model.get_layer('xxxx').output
```

你需要补习Keras： https://keras.io/applications/
