### ISSUE TITLE
albert的example的分词器没有更新为sentencepiece分词器

### ISSUE THREAD

**Issue by sparkingarthur** [bojone/bert4keras#58]
照着example写的话会报错。

from bert4keras.tokenizer import SpTokenizer
sentencepiece_model_path = "albert_base/30k-clean.model"
###分词器
tokenizer = SpTokenizer(sentencepiece_model_path, do_lower_case=True)

**Comment by bojone** [comment]
你想表达什么？

官方albert v1请参考：
https://github.com/bojone/bert4keras/issues/29#issuecomment-552188981

**Comment by sparkingarthur** [comment]
> 你想表达什么？
> 
> 官方albert v1请参考：
> [#29 (comment)](https://github.com/bojone/bert4keras/issues/29#issuecomment-552188981)

https://github.com/bojone/bert4keras/blob/master/examples/task_sentiment_albert.py
我的意思是现在版本的example是针对的徐亮的版本的albert，分词器还是用的bert的分词器，直接运行会报错。苏神你的分词器其实已经实现了Sptokenizer了，但是albert的example的代码还没有更新。

Google版v2格式和分词器要使用的example:

`
from bert4keras.tokenizer import SpTokenizer
config_path = 'albert_base/albert_config.json'
checkpoint_path = 'albert_base/model.ckpt-best'
dict_path = 'albert_base/30k-clean.vocab'
sentencepiece_model_path = "albert_base/30k-clean.model"
tokenizer = SpTokenizer(sentencepiece_model_path, do_lower_case=True)
`

**Comment by bojone** [comment]
> > 你想表达什么？
> > 官方albert v1请参考：
> > [#29 (comment)](https://github.com/bojone/bert4keras/issues/29#issuecomment-552188981)
> 
> https://github.com/bojone/bert4keras/blob/master/examples/task_sentiment_albert.py
> 我的意思是现在版本的example是针对的徐亮的版本的albert，分词器还是用的bert的分词器，直接运行会报错。苏神你的分词器其实已经实现了Sptokenizer了，但是albert的example的代码还没有更新。
> 
> Google版v2格式和分词器要使用的example:
> 
> ```
> from bert4keras.tokenizer import SpTokenizer
> config_path = 'albert_base/albert_config.json'
> checkpoint_path = 'albert_base/model.ckpt-best'
> dict_path = 'albert_base/30k-clean.vocab'
> sentencepiece_model_path = "albert_base/30k-clean.model"
> tokenizer = SpTokenizer(sentencepiece_model_path, do_lower_case=True)
> ```

我的例子就是用徐亮的albert，所以例子就是bert的tokenizer，有什么问题么？哪来的“没更新”之说？

至于Sptokenizer，我的README.md已经通过链接给出了官方albert的加载例子，如果你没看到，只能说明你没认真读README.md

**Comment by sparkingarthur** [comment]
好的~
