### ISSUE TITLE
请问有没有像keras bert里面的AdamWarmup优化器

### ISSUE THREAD

**Issue by tiandiweizun** [bojone/bert4keras#59]
使用keras bert+AdamWarmup与本项目里面的bert+adam做多分类，本项目acc差了1%，且稳定复现。

**Comment by bojone** [comment]
自然是有的，我连pretraining的代码都实现了，自然也不会少了warmup。

我这里实现了一个分段线性学习率的优化器，而warmup只是特殊的一个：
```python
from bert4keras.optimizers import Adam, extend_with_piecewise_linear_lr

AdamLR = extend_with_piecewise_linear_lr(Adam)
optimizer = AdamLR(learning_rate=1e-4, lr_schedule={1000: 1, 2000: 0.1})
```

这指的是0～1000步时，学习率从0线性增加到1*1e-4，然后1000～2000步时，学习率从1*1e-4线性下降到0.1*1e-4，2000步后学习率保持0.1*1e-4不变。

**Comment by tiandiweizun** [comment]
非常感谢
