### ISSUE TITLE
使用多GPU报错

### ISSUE THREAD

**Issue by qiuhuiGithub** [bojone/bert4keras#6]
您好，想问一下，单GPU运行的时候没有问题，但是当使用多GPU的时候报错是什么原因呢？
代码如下：
from keras.utils import multi_gpu_model  
os.environ["CUDA_VISIBLE_DEVICES"] = "6,7"  
with tf.device('/cpu:0'):  
    model = Model(albert_model.input, output)  
model.summary()  
model = multi_gpu_model(model, gpus=2)
错误如下：
`tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [256,10,10] vs. [512,1,10]
	 [[{{node replica_0/model_2/Encoder-1-MultiHeadSelfAttention/sub_1}}]]
  (1) Invalid argument: Incompatible shapes: [256,10,10] vs. [512,1,10]
	 [[{{node replica_0/model_2/Encoder-1-MultiHeadSelfAttention/sub_1}}]]
	 [[training/Adam/gradients/replica_1/model_2/Embedding-Norm/Mean_1_grad/Shape_2/_436]]`
祝好。

**Comment by bojone** [comment]
抱歉我没试过用多gpu训练，所以无法提供调试思路。

**Comment by xiaoshan0609** [comment]
您好，想问一下，我最近在跑一个单GPU的程序，直接用的keras没用tf.keras就不行吗？ GPU没调用起来

**Comment by bojone** [comment]
> 您好，想问一下，我最近在跑一个单GPU的程序，直接用的keras没用tf.keras就不行吗？ GPU没调用起来

此种问题请直接到keras官方github提问，此处是bert4keras，不管gpu调用。
