### ISSUE TITLE
y_mask = model.get_layer('Sequence-Mask').output_mask[:, 1:]

### ISSUE THREAD

**Issue by Bigmai-1234** [bojone/bert4keras#60]
TypeError: 'NoneType' object is not subscriptable

**Comment by Bigmai-1234** [comment]
y_mask = model.get_layer('Sequence-Mask').output_mask[:, 1:]# 目标mask
TypeError: 'NoneType' object is not subscriptable

**Comment by bojone** [comment]
如果要更新，请把整个repository都更新，不要只更新一部分就来提问。
