### ISSUE TITLE
pretraining预训练支持哪些bert版本？

### ISSUE THREAD

**Issue by luckper** [bojone/bert4keras#61]
pretraining支持albert_tiny版本吗？
还有预训练数据转成 .tfrecord 的数据格式是怎么样的？可以上一份数据格式样例吗？
谢谢！

**Comment by ZhuiyiAI** [comment]
预训练的区分是按照预训练任务来区分的，目前支持mlm和单向lm，跟模型架构没关系。

如果你想预训练一个albert，只需要在`pretraining.py`里边改一下`build_bert_model`那一句就行了。

.tfrecord里边具体是什么格式，这个不用关心。至于原数据是什么格式，答案是没有格式，自行读懂`data_utils.py`（至少读懂`if __name__ == '__main__': `后面部分）， 然后修改`some_texts`的定义来适配自己的数据格式。如果这一点做不到，不建议玩从零预训练。

**Comment by bojone** [comment]
预训练的区分是按照预训练任务来区分的，目前支持mlm和单向lm，跟模型架构没关系。

如果你想预训练一个albert，只需要在`pretraining.py`里边改一下`build_bert_model`那一句就行了。

.tfrecord里边具体是什么格式，这个不用关心。至于原数据是什么格式，答案是没有格式，自行读懂`data_utils.py`（至少读懂`if __name__ == '__main__': `后面部分）， 然后修改`some_texts`的定义来适配自己的数据格式。如果这一点做不到，不建议玩从零预训练。

**Comment by luckper** [comment]
好的，谢谢解答，目前已经弄明白了
