### ISSUE TITLE
加载google发布的albert中文版报错

### ISSUE THREAD

**Issue by gyangfan** [bojone/bert4keras#63]
==> searching: bert/encoder/transformer/group_0/inner_group_0/output/dense/kernel, found name: bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/output/dense/kernel
==> searching: bert/encoder/transformer/group_0/inner_group_0/output/dense/bias, found name: bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/output/dense/bias
==> searching: bert/encoder/transformer/group_0/inner_group_0/output/LayerNorm/gamma, found name: bert/encoder/transformer/group_0/inner_group_0/LayerNorm_1/gamma
==> searching: bert/encoder/transformer/group_0/inner_group_0/output/LayerNorm/beta, found name: bert/encoder/transformer/group_0/inner_group_0/LayerNorm_1/beta
==> searching: bert/encoder/transformer/group_0/inner_group_0/attention/self/query/kernel, found name: cls/predictions/transform/dense/kernel
==> searching: bert/encoder/transformer/group_0/inner_group_0/attention/self/query/bias, found name: cls/predictions/transform/dense/bias
==> searching: bert/encoder/transformer/group_0/inner_group_0/attention/self/key/kernel, found name: cls/predictions/transform/LayerNorm/beta
==> searching: bert/encoder/transformer/group_0/inner_group_0/attention/self/key/bias, found name: cls/predictions/transform/LayerNorm/gamma
==> searching: bert/encoder/transformer/group_0/inner_group_0/attention/self/value/kernel, found name: bert/pooler/dense/kernel
==> searching: bert/encoder/transformer/group_0/inner_group_0/attention/self/value/bias, found name: bert/pooler/dense/bias
==> searching: bert/encoder/transformer/group_0/inner_group_0/attention/output/dense/kernel, found name: cls/predictions/output_bias
==> searching: bert/encoder/transformer/group_0/inner_group_0/attention/output/dense/bias, found name: cls/seq_relationship/output_bias

  File "/home/share/gyf/sa/model/bert.py", line 420, in load_weights_from_checkpoint
    K.batch_set_value(zip(weights, values))
  File "/home/share/anaconda3/envs/tf_keras/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2960, in batch_set_value
    tf_keras_backend.batch_set_value(tuples)
  File "/home/share/anaconda3/envs/tf_keras/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3066, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/share/anaconda3/envs/tf_keras/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1141, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/share/anaconda3/envs/tf_keras/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 1103, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (768, 768) and (768, 128) are incompatible

**Comment by bojone** [comment]
看README.md了吗？看examples了吗？指定`model='albert'`了吗？

**Comment by gyangfan** [comment]
抱歉！
