### ISSUE TITLE
载入英文vocab问题

### ISSUE THREAD

**Issue by erichen510** [bojone/bert4keras#64]
使用英文albert模型遇到的问题：
在载入官方的 albert_base_v2的时候， 官方模型目录包含：
30k-clean.vocab 应该是包含30k的字典文件，直接用Tokenizer载入出来是错误的 token_id 对应表
使用原先bert的vocab.txt（含有30522个token），可以训练，但是结果不佳，应该是token embedding对不上。
请问如何载入官方对应的 vocab文件。

**Comment by bojone** [comment]
用`SpTokenizer`加载`30k-clean.model`

**Comment by erichen510** [comment]
谢谢苏神！！
