### ISSUE TITLE
commit信息能否是针对功能的说明

### ISSUE THREAD

**Issue by Jothangan** [bojone/bert4keras#65]
如题，commit信息能否是针对功能的说明，当前这提交记录看着有点懵

**Comment by bojone** [comment]
一直没养成这个习惯，抱歉～～

你是要看什么信息呢？常规的内核改动都会保证api使用上的兼用，所以一般不用关注。一般的大改动会在README.md记录。

因为我通常直接在网页版直接改动的，而且同一个改动可能分成多次来改，因此记录变动有点麻烦，真的很抱歉。
