### ISSUE TITLE
extend_with_gradient_accumulation使用报错

### ISSUE THREAD

**Issue by fushengwuyu** [bojone/bert4keras#66]
苏神，你好，很感谢你的bert4keras，让我受益匪浅。今天在用extend_with_gradient_accumulation优化器的时候，报错:
ValueError: The two structures dont have the same nested structure

First structure: type=IndexedSlices  str=IndexedSlices(indices=Tensor("training/new_optimizer/gradients/Embedding-Token/embedding_lookup_grad/ReShape_1:0", shape=(?,), dtype=int32), values=Tensor("training/new_optimizer/gradients/Embedding-Token/embedding_lookup_grad/ReShape:0", shape=(?,768), dtype=float32), dense_shape=Tensor("training/new_optimizer/gradients/Embedding-Token/embedding_lookup_grad/const:0", shape=(2,), dtype=int32))

Second structure: type=Tensor str=Tensor("training/new_optimizer/add_598:0", shape=(2111, 768), dtype=float32)

我的使用代码如下：
optimizer = extend_with_gradient_accumulation(Adam)
optimizer = optimizer(learning_rate=1e-5, grad_accum_steps=10)
model.compile(optimizer=optimizer, ....)

我的环境是：keras2.3.1+tensorflow1.14.1+bert4keras0.4.2

我开始怀疑是数据类型不对，所以又测试了extend_with_piecewise_linear_lr和extend_with_weight_decay，均可正常训练，只有extend_with_gradient_accumulation出错，很是疑惑。

麻烦苏神，能否帮忙看一下是怎么回事，谢谢了。

**Comment by bojone** [comment]
不好意思，是我测试不充分，现在应该已经修复了，你再试试。

**Comment by fushengwuyu** [comment]
好的，我再测试一下，麻烦苏神了，十分感谢
