### ISSUE TITLE
请问支持百度的ERNIE吗？

### ISSUE THREAD

**Issue by ArconB** [bojone/bert4keras#67]
RT

**Comment by bojone** [comment]
https://github.com/ArthurRizar/tensorflow_ernie
使用这个转换后的权重，跟使用普通bert一样。

**Comment by ArconB** [comment]
> https://github.com/ArthurRizar/tensorflow_ernie
> 使用这个转换后的权重，跟使用普通bert一样。

直接用给的百度云链接下的权重，在load_weight的时候好像少这些？
[ 'cls/predictions/output_bias',
 'cls/predictions/transform/LayerNorm/beta',
 'cls/predictions/transform/LayerNorm/gamma',
 'cls/predictions/transform/dense/bias',
 'cls/predictions/transform/dense/kernel',
 'cls/seq_relationship/output_bias',
 'cls/seq_relationship/output_weights']
