### ISSUE TITLE
获取albert中间层输出

### ISSUE THREAD

**Issue by erichen510** [bojone/bert4keras#68]
目的：获取albert后四层输出的cls向量
想在训练中获取最后四层的cls向量concate，利用得到的新向量进行分类。
```
# 加载预训练模型
bert = build_bert_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
    model='albert',
    with_pool=True,
    return_keras_model=False,
)

from keras import Model
model = Model(
    inputs=bert.model.input,
    outputs=[
        bert.model.get_layer('Encoder-1-FeedForward-Norm').output, 
        #bert.model.get_layer('Encoder-1-FeedForward-Norm').output[10][0], 
    ]
)

output = model.output

output = Dropout(rate=0.1)(bert.model.output)
output = Dense(units=2,
               activation='softmax',
               kernel_initializer=bert.initializer)(output)

model = keras.models.Model(bert.model.input, output)
```
参考了苏神博客中的 提取中间层的写法， 但好像并不能提取出
错误为

> Layer Encoder-1-FeedForward-Norm has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.

不知道应该怎么取到最后四层（pool之前的最后四层）
理想情况是 我的新model的output shape是（4 , batch_size, 768) 
不知有没有表述清楚，还请指教。

**Comment by erichen510** [comment]
`已经可以取到中间层的输出了，代码如下：
```
rom keras import Model
model = Model(
    inputs=bert.model.input,
    outputs=[
        # bert.model.get_layer('Encoder-1-FeedForward-Norm').get_output_at(0),
        bert.model.layers[-3].get_output_at(0),
    ]
)

output = model.output

output = Dropout(rate=0.1)(bert.model.output)
output = Dense(units=2,
               activation='softmax',
               kernel_initializer=bert.initializer)(output)

model = keras.models.Model(bert.model.input, output)
```
但是输出向量的shape是(none, none, 768)，我需要得到这个向量的 [:,0]
而且我需要四个这样的向量， output会变为
```
    outputs=[
        # bert.model.get_layer('Encoder-1-FeedForward-Norm').get_output_at(0),
        bert.model.layers[-3].get_output_at(11),
        bert.model.layers[-3].get_output_at(10),
        bert.model.layers[-3].get_output_at(9),
       bert.model.layers[-3].get_output_at(8),
    ]
)
```
如何不通过为每个输出添加lambda层，快速实现concate四个hidden layer的cls
keras好像不能像torch一样直接取，类似 `bert.model.layers[-3].get_output_at(11)[:,0]`

**Comment by bojone** [comment]
> 如何不通过为每个输出添加lambda层，快速实现concate四个hidden layer的cls

不存在这样的方法。Lambda层已经是很快速的方法了。

**Comment by erichen510** [comment]
自己实现了下：
```
from keras import Model
model = Model(
    inputs=bert.model.input,
    outputs=[
        bert.model.layers[-4].get_output_at(11),
        bert.model.layers[-4].get_output_at(10),
        bert.model.layers[-4].get_output_at(9),
        bert.model.layers[-4].get_output_at(8),
    ]
)

output = model.outputs
output1 = Lambda(lambda x: x[:, 0], name='Pooler')(output[0])
output2 = Lambda(lambda x: x[:, 0], name='Pooler')(output[1])
output3 = Lambda(lambda x: x[:, 0], name='Pooler')(output[2])
output4 = Lambda(lambda x: x[:, 0], name='Pooler')(output[3])

output = keras.layers.concatenate([output1, output2, output3, output4], axis=1)

```
不是到是不是最简洁的，大家帮着看看

**Comment by bojone** [comment]
嗯，可以

**Comment by erichen510** [comment]
谢谢苏神指教～

**Comment by jk123vip** [comment]
> 自己实现了下：
> 
> ```
> from keras import Model
> model = Model(
>     inputs=bert.model.input,
>     outputs=[
>         bert.model.layers[-4].get_output_at(11),
>         bert.model.layers[-4].get_output_at(10),
>         bert.model.layers[-4].get_output_at(9),
>         bert.model.layers[-4].get_output_at(8),
>     ]
> )
> 
> output = model.outputs
> output1 = Lambda(lambda x: x[:, 0], name='Pooler1')(output[0])
> output2 = Lambda(lambda x: x[:, 0], name='Pooler2')(output[1])
> output3 = Lambda(lambda x: x[:, 0], name='Pooler3')(output[2])
> output4 = Lambda(lambda x: x[:, 0], name='Pooler4')(output[3])
> 
> output = keras.layers.concatenate([output1, output2, output3, output4], axis=1)
> ```
> 
> 不知道是不是最简洁的，谢谢苏神的回答～～

@erichen510 你好，请问下你这段不是取albert倒数第四层后四个节点的输出吗？可是我看你最初的问题是获取最后四层的cls向量concate。这俩一样嘛？
