### ISSUE TITLE
ERROR    tensorflow.python.framework.errors_impl.

### ISSUE THREAD

**Issue by SlytherinWyne** [bojone/bert4keras#69]
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./albert_base/model.ckpt

我的环境是macOS, python-3.7.3, tensorflow-1.15.0, keras-2.3.1

**Comment by bojone** [comment]
不知道你想表达什么。错误信息不是很明显了么？没找到./albert_base/model.ckpt啊

**Comment by SlytherinWyne** [comment]
谢谢大佬🙏，那个问题已经解决了。但是使用build_bert_model的时候提示 Shapes (768, 768) and (?,) are incompatible.
是因为build_bert_model传入参数的问题吗？我只是用了几行代码测试

from bert4keras.bert import build_bert_model
config_path=‘XXX’
checkpoint_path=‘XXX’
model = build_bert_model(config_path, checkpoint_path)

**Comment by SlytherinWyne** [comment]
谢大佬🙏，问题找到了。build_bert_model加载albert模型时要设置参数model=‘albert’.之前的问题是因为ckpt路径没写全
