### ISSUE TITLE
請問 bert4keras 可以做文本分類的任务嗎

### ISSUE THREAD

**Issue by chiyiliao** [bojone/bert4keras#71]
请问 bert4keras 可以做文本分类吗？
有没有范例可以参考呢？
谢谢！

**Comment by luoy2** [comment]
examples/task_sentiment_albert.py

**Comment by luoy2** [comment]
@chiyiliao 文本分类是一类任务， bert4keras只是将bert用keras实现， 建议先了解bert的机制以及如何作用于文本分类
