### ISSUE TITLE
albert_xlarge_zh_183k 目前不支持加载么？

### ISSUE THREAD

**Issue by wentixiaogege** [bojone/bert4keras#74]
尝试了两种加载方式
1.本方式可以加载，因为咱们的examples本身就是用的这个
config_path = './albert/albert_small_zh_google/albert_config_small_google.json'
checkpoint_path = './albert/albert_small_zh_google/albert_model.ckpt'
dict_path = './albert/albert_small_zh_google/vocab.txt'

2.本方式加载报错
config_path = './albert/albert_xlarge_zh_183k/albert_config_xlarge.json'
checkpoint_path = './albert/albert_xlarge_zh_183k/albert_model.ckpt'
dict_path = './albert/albert_xlarge_zh_183k/vocab.txt'

报错内容如下：
model = build_bert_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
    model='albert')

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-12-6e79b6565800> in <module>
      2     config_path=config_path,
      3     checkpoint_path=checkpoint_path,
----> 4     model='albert')

/data/anaconda3/envs/py37/lib/python3.7/site-packages/bert4keras/bert.py in build_bert_model(config_path, checkpoint_path, with_pool, with_nsp, with_mlm, model, application, keep_tokens, attention_mask, position_ids, layer_norm_cond, layer_norm_cond_size, layer_norm_cond_hidden_size, layer_norm_cond_hidden_act, additional_input_layers, att_pool_size, ffn_pool_size, return_keras_model)
    581         else:
    582             reference = 'bert'
--> 583         bert.load_weights_from_checkpoint(checkpoint_path, reference)
    584 
    585     if return_keras_model:

/data/anaconda3/envs/py37/lib/python3.7/site-packages/bert4keras/bert.py in load_weights_from_checkpoint(self, checkpoint_file, reference, mapping)
    397                 return variable
    398 
--> 399         values = [load_variable(name) for name in mapping]
    400 
    401         bert_layer_names = [

/data/anaconda3/envs/py37/lib/python3.7/site-packages/bert4keras/bert.py in <listcomp>(.0)
    397                 return variable
    398 
--> 399         values = [load_variable(name) for name in mapping]
    400 
    401         bert_layer_names = [

/data/anaconda3/envs/py37/lib/python3.7/site-packages/bert4keras/bert.py in load_variable(name)
    383         def load_variable(name):
    384             # 加载单个变量的函数
--> 385             variable = tf.train.load_variable(checkpoint_file, name)
    386             if name in [
    387                     'bert/embeddings/word_embeddings',

/data/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/checkpoint_utils.py in load_variable(ckpt_dir_or_file, name)
     82     name = name[:-2]
     83   reader = load_checkpoint(ckpt_dir_or_file)
---> 84   return reader.get_tensor(name)
     85 
     86 

/data/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py in get_tensor(self, tensor_str)
    913       from tensorflow.python.util import compat
    914 
--> 915       return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
    916 
    917     __swig_destroy__ = _pywrap_tensorflow_internal.delete_CheckpointReader

NotFoundError: Key bert/encoder/embedding_hidden_mapping_in/kernel not found in checkpoint

感觉好像不支持么？

**Comment by wentixiaogege** [comment]
模型来自 github 
https://github.com/brightmart/albert_zh

**Comment by wentixiaogege** [comment]
https://github.com/bojone/bert4keras/issues/57  看到了这个，不支持不带google的哈~

**Comment by bojone** [comment]
这个转换后的可以加载
https://github.com/bojone/albert_zh
