### ISSUE TITLE
在运行pretraining的时候遇到了如下错误

### ISSUE THREAD

**Issue by wutong4012** [bojone/bert4keras#75]
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1618   try:
-> 1619     c_op = c_api.TF_FinishOperation(op_desc)
   1620   except errors.InvalidArgumentError as e:

InvalidArgumentError: slice index -1 of dimension 0 out of bounds. for 'loss_3/mlm_loss_loss/strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, input[2] = <0>, input[3] = <1>.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-8-1a0ae26aea72> in <module>
    138 
    139 with strategy.scope():
--> 140     train_model = build_bert_model_for_pretraining()
    141     train_model.summary()
    142 

<ipython-input-8-1a0ae26aea72> in build_bert_model_for_pretraining()
    124 
    125     # 模型定型
--> 126     train_model.compile(loss=loss, optimizer=optimizer)
    127 
    128     # 如果传入权重，则加载。注：须在此处加载，才保证不报错。

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, distribute, **kwargs)
    444 
    445       # Creates the model loss and weighted metrics sub-graphs.
--> 446       self._compile_weights_loss_and_weighted_metrics()
    447 
    448       # Functions for train, test and predict will

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in _compile_weights_loss_and_weighted_metrics(self, sample_weights)
   1590       #                   loss_weight_2 * output_2_loss_fn(...) +
   1591       #                   layer losses.
-> 1592       self.total_loss = self._prepare_total_loss(masks)
   1593 
   1594   def _prepare_skip_target_masks(self):

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in _prepare_total_loss(self, masks)
   1650 
   1651           if hasattr(loss_fn, 'reduction'):
-> 1652             per_sample_losses = loss_fn.call(y_true, y_pred)
   1653             weighted_losses = losses_utils.compute_weighted_loss(
   1654                 per_sample_losses,

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py in call(self, y_true, y_pred)
    218     if tensor_util.is_tensor(y_pred) and tensor_util.is_tensor(y_true):
    219       y_pred, y_true = tf_losses_util.squeeze_or_expand_dimensions(
--> 220           y_pred, y_true)
    221     return self.fn(y_true, y_pred, **self._fn_kwargs)
    222 

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/ops/losses/util.py in squeeze_or_expand_dimensions(y_pred, y_true, sample_weight)
     77       squeeze_dims = lambda: confusion_matrix.remove_squeezable_dimensions(  # pylint: disable=g-long-lambda
     78           y_true, y_pred)
---> 79       is_last_dim_1 = math_ops.equal(1, array_ops.shape(y_pred)[-1])
     80       maybe_squeeze_dims = lambda: control_flow_ops.cond(  # pylint: disable=g-long-lambda
     81           is_last_dim_1, squeeze_dims, lambda: (y_true, y_pred))

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py in _slice_helper(tensor, slice_spec, var)
    896         ellipsis_mask=ellipsis_mask,
    897         var=var,
--> 898         name=name)
    899 
    900 

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py in strided_slice(input_, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, var, name)
   1062       ellipsis_mask=ellipsis_mask,
   1063       new_axis_mask=new_axis_mask,
-> 1064       shrink_axis_mask=shrink_axis_mask)
   1065 
   1066   parent_name = name

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py in strided_slice(input, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, name)
   9533                         ellipsis_mask=ellipsis_mask,
   9534                         new_axis_mask=new_axis_mask,
-> 9535                         shrink_axis_mask=shrink_axis_mask, name=name)
   9536   _result = _outputs[:]
   9537   if _execute.must_record_gradient():

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py in _apply_op_helper(op_type_name, name, **keywords)
    740       op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    741                                  name=scope, input_types=input_types,
--> 742                                  attrs=attr_protos, op_def=op_def)
    743 
    744     # `outputs` is returned as a separate return value so that the output

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py in _create_op_internal(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_device)
    593     return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    594         op_type, inputs, dtypes, input_types, name, attrs, op_def,
--> 595         compute_device)
    596 
    597   def capture(self, tensor, name=None, shape=None):

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py in _create_op_internal(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_device)
   3320           input_types=input_types,
   3321           original_op=self._default_original_op,
-> 3322           op_def=op_def)
   3323       self._create_op_helper(ret, compute_device=compute_device)
   3324     return ret

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1784           op_def, inputs, node_def.attr)
   1785       self._c_op = _create_c_op(self._graph, node_def, grouped_inputs,
-> 1786                                 control_input_ops)
   1787       name = compat.as_str(node_def.name)
   1788     # pylint: enable=protected-access

~/anaconda3/envs/wutong/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1620   except errors.InvalidArgumentError as e:
   1621     # Convert to ValueError for backwards compatibility.
-> 1622     raise ValueError(str(e))
   1623 
   1624   return c_op

ValueError: slice index -1 of dimension 0 out of bounds. for 'loss_3/mlm_loss_loss/strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, input[2] = <0>, input[3] = <1>.

**Comment by bojone** [comment]
预训练暂不支持tf2，请换tf 1.14和tf 1.15跑

**Comment by luoqishuai** [comment]
这个问题是构建模型的问题
这个报错是y_true在target中获取的shape导致的 修改 tf2.0 源码后能解决
tensorflow_core->python->keras->engine->training     name=self.output_name + '_target',
增加 shape=self.shape,
代码变为
```
        target = K.placeholder(
            shape=self.shape,
            ndim=len(self.shape),
            name=self.output_name + '_target',
            sparse=K.is_sparse(self.output),
            dtype=target_dtype)
```
至于后面的预训练问题.
我这里还在报错中
