### ISSUE TITLE
测试task_sentiment_albert.py时模型的问题

### ISSUE THREAD

**Issue by bigcash** [bojone/bert4keras#76]
@bojone 作者您好，我看readme中说明，必须要用brightmart/albert_zh项目中的带google的模型，但是我从这个项目中下载并使用了albert_small_zh_google.zip这个模型，解压后的文件列表是这样：
albert_config_small_google.json
albert_model.ckpt.data-00000-of-00001
albert_model.ckpt.index
albert_model.ckpt.meta
albert_small_zh_google.zip
checkpoint
vocab.txt
而我们的task_sentiment_albert.py文件中设置的模型文件是这样的：
config_path = '/home/work/text/albert_small_zh_google/albert_config_small_google.json'
checkpoint_path = '/home/work/text/albert_small_zh_google/checkpoint'
dict_path = '/home/work/text/albert_small_zh_google/vocab.txt'
这个checkpoint_path要引用的模型文件和brightmart项目中解压的不太一样啊，我挨个测试了，都不对。请问这个是什么问题，多谢！

**Comment by bojone** [comment]
checkpoint_path = '/home/work/text/albert_small_zh_google/albert_model.ckpt'
如有疑问，请直接百度ckpt文件格式介绍。

**Comment by bigcash** [comment]
好的，多谢！已解决
我以为必须要有这个albert_model.ckpt文件呢，而实际上checkpoint这个文件定义了有哪些模型
