### ISSUE TITLE
example中三元组抽取例子subject模型首尾预测概率远小于0.6

### ISSUE THREAD

**Issue by xinzhuang** [bojone/bert4keras#79]
环境：
- TF 1.15
- python 3
- GPU cuda 10
- bert4keras 0.5.6

模型：
- albert 中文预训练模型，albert_tiny_google_zh_489k.zip
- 语料，当时比赛的数据，从百度下载

 问题描述：
下载git仓库后，进行安装，进入example目录，想要复现task_relation_extraction.py, 修改数据和模型路径路径，加载albert的预训练模型，修改模型加载参数为‘albert’，其他未作改动，训练10个epoch后，subject 模型预测的首尾概率值都小于0.1，在0.02 左右，并且每一个token的概率一样（列元素相同），请问下这是合理的吗？感谢您最近的版本更新~

**Comment by bojone** [comment]
运行过程中有显示验证集F1吗？验证集F1有多少？

https://github.com/ZhuiyiTechnology/pretrained-models
这里边有我之前评测albert tiny和small版的结果，显示也有76%的F1。

**Comment by xinzhuang** [comment]
之前的版本f1和recall都是0，pecision是1，又更新了一下几小时之前的一个版本，似乎有所改善，我再验证下。感谢~

**Comment by xinzhuang** [comment]
再次验证了下，训练20 epoch后，f1: 0.71361, precision: 0.84613, recall: 0.61698，没有问题了，我注意到在这个commit中更新了albert模型layer normalization gamma层的位置，不知道之前的问题是否和这个有关系。
总之，现在问题解决了，感谢~

**Comment by bojone** [comment]
> 再次验证了下，训练20 epoch后，f1: 0.71361, precision: 0.84613, recall: 0.61698，没有问题了，我注意到在这个commit中更新了albert模型layer normalization gamma层的位置，不知道之前的问题是否和这个有关系。
> 总之，现在问题解决了，感谢~

昨天github上有个版本确实是改错了，后来才修正的。
