### ISSUE TITLE
bert4keras安装问题：ModuleNotFoundError: No module named 'bert4keras.models'

### ISSUE THREAD

**Issue by YL1113** [bojone/bert4keras#80]
你好，我通过pip install bert4keras安装了bert4keras， 然后尝试运行task_iflytek_adversarial_training.py，结果报错：ModuleNotFoundError: No module named 'bert4keras.models', 请问该如何解决这个问题，谢谢~

**Comment by bojone** [comment]
更新github上的最新版，或者将`bert4keras.models`改为`bert4keras.bert`
