### ISSUE TITLE
bert4keras加载bert_base模型，输出句子向量时能否指定长度

### ISSUE THREAD

**Issue by chros425** [bojone/bert4keras#81]
bert4keras加载bert_base模型，输出句子向量时能否指定长度，目前默认的是768，但是感觉在只有十几个字的短句上，这个维度有点长，不知道是否有参数可以指定输出的特征向量的长度，谢谢大佬！

**Comment by bojone** [comment]
这是bert模型决定的，不是框架可以随便改的。

你可以考虑：
- 后面接一个全连接层降微
- 用小型模型（比如 RoBERTa small/tiny:https://github.com/ZhuiyiTechnology/pretrained-models  )

**Comment by chros425** [comment]
好的，明白了，谢谢大佬的及时回复！
