### ISSUE TITLE
keras的h5文件转pb文件

### ISSUE THREAD

**Issue by erichen510** [bojone/bert4keras#83]
请问keras的h5文件转pb文件有没有什么好方法，在用 https://github.com/amir-abdi/keras_to_tensorflow/ 转albert_base的时候，会出现 Unknown layer:  ZeroMasking的错误

**Comment by bojone** [comment]
```python
from bert4keras.layers import *
```

**Comment by erichen510** [comment]
把这行加到 keras_to_tensorflow.py后 报错：  Unkonwn optimizer: new optimizer

**Comment by bojone** [comment]
别compile模型，或者别用extend_with之后的优化器。

**Comment by erichen510** [comment]
from bert4keras.optimizers import * 好像还是不行

**Comment by erichen510** [comment]
![image](https://user-images.githubusercontent.com/16681583/76198046-42f83c80-6228-11ea-9db4-c3bb3122a4d4.png)
那就是直接用那个没有 lr_schedule的adam了吧

**Comment by erichen510** [comment]
用tf2.0好像也不行 
![image](https://user-images.githubusercontent.com/16681583/76200314-5d341980-622c-11ea-9f7f-69931885b8b3.png)
我加了 
`from bert4keras.layers import *`
但是还是说 zeromasking 找不到

**Comment by bojone** [comment]
设置了环境变量了没有，用tf.keras要设置TF_KERAS=1，README.md有说，请认真阅读。

**Comment by erichen510** [comment]
设置了 完整的代码是
```
from keras import backend as K
from keras.models import load_model
import tensorflow as tf
import os
os.environ['TF_KERAS'] ='1'
model_path = 'best_model.h5'
model = tf.keras.models.load_model(model_path)
model.save('models/resnet/', save_format='tf')

```
我用原本的adam训练以后再试一试把

**Comment by bojone** [comment]
不是保存的时候设置，是转换的时候设置（from bert4keras.layers import *那句话在哪里，就在哪里设置）。

**Comment by erichen510** [comment]
漏加那句话了。。。。我确实是转换的时候设置的

**Comment by erichen510** [comment]
```
from keras import backend as K
from keras.models import load_model
import tensorflow as tf
from bert4keras.layers import *
import os
os.environ['TF_KERAS'] ='1'
model_path = 'best_model.h5'
model = tf.keras.models.load_model(model_path)
model.save('models/resnet/', save_format='tf')
```

**Comment by erichen510** [comment]
tensorflow版本是 2.0.0a0 keras是 2.3.1

**Comment by bojone** [comment]
顺序不对呀。

os.environ['TF_KERAS'] ='1' 必须在bert4keras之前，因为bert4keras要读取TF_KERAS。

**Comment by erichen510** [comment]
意识到了。。不好意思 然后 之后的错误是

> Node object has no attribute 'output_masks'

**Comment by bojone** [comment]
output_masks错误，建议用最新版的bert4keras重新训练并保存一次模型吧，因为早起的版本可能存在一些问题。

**Comment by erichen510** [comment]
好的 我再试试

**Comment by erichen510** [comment]
我用tf1.14 的tf.keras进行训练 然后利用tf2.0的tf.keras进行转换 bert4keras的版本是0.5.4  优化函数用了 bert4keras普通的adam 

报错是： super(type, obj): obj must be an instance or subtype of type

**Comment by erichen510** [comment]
目前成功存储pb文件：
在tf2.0下训练
`
tf.keras.models.save_model(model,"model_save_path", save_format='tf')`
但是会有很多warning:
![image](https://user-images.githubusercontent.com/16681583/76217060-ae540580-624c-11ea-95a0-7d2b6be77a9f.png)
还没有试过能否用tfs进行部署

**Comment by bojone** [comment]
> 目前成功存储pb文件：
> 在tf2.0下训练
> ` tf.keras.models.save_model(model,"model_save_path", save_format='tf')`
> 但是会有很多warning:
> ![image](https://user-images.githubusercontent.com/16681583/76217060-ae540580-624c-11ea-95a0-7d2b6be77a9f.png)
> 还没有试过能否用tfs进行部署

有后续进展的话欢迎继续报告，这是一个不错的参考案例

**Comment by wangweicode** [comment]
import os
os.environ['TF_KERAS'] ='1'
from keras import backend as K
from keras.models import load_model
import tensorflow as tf
from bert4keras.layers import *
model_path = './models/bert_autotitle.h5'
model = tf.keras.models.load_model(model_path)
model.save('./models/resnet/', save_format='tf')

报错误：
  File "\bert4keras\layers.py", line 132, in call
    qw = self.q_dense(q)
ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.

有谁弄成功没有？？

**Comment by lonngxiang** [comment]
> 目前成功存储pb文件：
> 在tf2.0下训练
> ` tf.keras.models.save_model(model,"model_save_path", save_format='tf')`
> 但是会有很多warning:
> ![image](https://user-images.githubusercontent.com/16681583/76217060-ae540580-624c-11ea-95a0-7d2b6be77a9f.png)
> 还没有试过能否用tfs进行部署

直接bert4keras加载进来的预训练模型能save成pb格式吗

**Comment by lonngxiang** [comment]
> > 目前成功存储pb文件：
> > 在tf2.0下训练
> > ` tf.keras.models.save_model(model,"model_save_path", save_format='tf')`
> > 但是会有很多warning:
> > ![image](https://user-images.githubusercontent.com/16681583/76217060-ae540580-624c-11ea-95a0-7d2b6be77a9f.png)
> > 还没有试过能否用tfs进行部署
> 
> 有后续进展的话欢迎继续报告，这是一个不错的参考案例

tf 1.X版本这种方式保存不了

**Comment by earlzz** [comment]
> 目前成功存储pb文件：
> 在tf2.0下训练
> ` tf.keras.models.save_model(model,"model_save_path", save_format='tf')`
> 但是会有很多warning:
> ![image](https://user-images.githubusercontent.com/16681583/76217060-ae540580-624c-11ea-95a0-7d2b6be77a9f.png)
> 还没有试过能否用tfs进行部署

可以进行部署吗，另外1.X有解决方案吗
