### ISSUE TITLE
'Tokenizer' object has no attribute '_token_unk_id'

### ISSUE THREAD

**Issue by mic0608** [bojone/bert4keras#87]
AttributeError                            Traceback (most recent call last)
<ipython-input-13-9a8d314e0f85> in <module>()
      2                     steps_per_epoch=len(trainD),
      3                     epochs=10,
----> 4                     validation_data=testD.__iter__())

12 frames
/tensorflow-2.1.0/python3.6/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1304         use_multiprocessing=use_multiprocessing,
   1305         shuffle=shuffle,
-> 1306         initial_epoch=initial_epoch)
   1307 
   1308   @deprecation.deprecated(

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    817         max_queue_size=max_queue_size,
    818         workers=workers,
--> 819         use_multiprocessing=use_multiprocessing)
    820 
    821   def evaluate(self,

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    233           max_queue_size=max_queue_size,
    234           workers=workers,
--> 235           use_multiprocessing=use_multiprocessing)
    236 
    237       total_samples = _get_total_number_of_samples(training_data_adapter)

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training_v2.py in _process_training_inputs(model, x, y, batch_size, epochs, sample_weights, class_weights, steps_per_epoch, validation_split, validation_data, validation_steps, shuffle, distribution_strategy, max_queue_size, workers, use_multiprocessing)
    591         max_queue_size=max_queue_size,
    592         workers=workers,
--> 593         use_multiprocessing=use_multiprocessing)
    594     val_adapter = None
    595     if validation_data:

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training_v2.py in _process_inputs(model, mode, x, y, batch_size, epochs, sample_weights, class_weights, shuffle, steps, distribution_strategy, max_queue_size, workers, use_multiprocessing)
    704       max_queue_size=max_queue_size,
    705       workers=workers,
--> 706       use_multiprocessing=use_multiprocessing)
    707 
    708   return adapter

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, standardize_function, workers, use_multiprocessing, max_queue_size, **kwargs)
    745     # Since we have to know the dtype of the python generator when we build the
    746     # dataset, we have to look at a batch to infer the structure.
--> 747     peek, x = self._peek_and_restore(x)
    748     assert_not_namedtuple(peek)
    749 

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/data_adapter.py in _peek_and_restore(x)
    848   @staticmethod
    849   def _peek_and_restore(x):
--> 850     peek = next(x)
    851     return peek, itertools.chain([peek], x)
    852 

<ipython-input-10-1dad7cbf6d49> in __iter__(self, random)
      9         for i in idxs:
     10             text, label = self.data[i]
---> 11             token_ids, segment_ids = tokenizer.encode(text, max_length=maxlen)
     12             batch_token_ids.append(token_ids)
     13             batch_segment_ids.append(segment_ids)

/usr/local/lib/python3.6/dist-packages/bert4keras/tokenizers.py in encode(self, first_text, second_text, max_length, first_length, second_length)
    134             self.truncate_sequence(max_length, first_tokens, second_tokens, -2)
    135 
--> 136         first_token_ids = self.tokens_to_ids(first_tokens)
    137         if first_length is not None:
    138             first_token_ids = first_token_ids[:first_length]

/usr/local/lib/python3.6/dist-packages/bert4keras/tokenizers.py in tokens_to_ids(self, tokens)
     87         """token序列转换为对应的id序列
     88         """
---> 89         return [self.token_to_id(token) for token in tokens]
     90 
     91     def truncate_sequence(self,

/usr/local/lib/python3.6/dist-packages/bert4keras/tokenizers.py in <listcomp>(.0)
     87         """token序列转换为对应的id序列
     88         """
---> 89         return [self.token_to_id(token) for token in tokens]
     90 
     91     def truncate_sequence(self,

/usr/local/lib/python3.6/dist-packages/bert4keras/tokenizers.py in token_to_id(self, token)
    201         """token转换为对应的id
    202         """
--> 203         return self._token_dict.get(token, self._token_unk_id)
    204 
    205     def id_to_token(self, i):

AttributeError: 'Tokenizer' object has no attribute '_token_unk_id'

**Comment by bojone** [comment]
你的词表为什么没有[UNK]，应该要你自己去找原因。

**Comment by mic0608** [comment]
@bojone 明白了，感谢。
