### ISSUE TITLE
relation_extract  f1: 0.0, precision: 1.0, recall: 0.0 

### ISSUE THREAD

**Issue by cronousbaby** [bojone/bert4keras#90]
苏神，我参考您的关系抽取的例子，按照相同的格式对我自己标注的语料进行了格式转换{text:'',spo_list:[....]}  在训练的eval中出现了f1: 0.0, precision: 1.0, recall: 0.0 情况，请问这种问题如何解决呢

**Comment by bojone** [comment]
就这么点信息，我怎么知道呀...

**Comment by cronousbaby** [comment]
1、我用了一个kg_2019 json的精简版本版本（数据量大概缩减了10分之1左右），格式不变
{"postag": [{"word": "内容", "pos": "n"}, {"word": "简介", "pos": "n"}, {"word": "《", "pos": "w"}, {"word": "宜兴紫砂图典", "pos": "nw"}, {"word": "》", "pos": "w"}, {"word": "由", "pos": "p"}, {"word": "故宫出版社", "pos": "nt"}, {"word": "出版", "pos": "v"}], "text": "内容简介《宜兴紫砂图典》由故宫出版社出版", "spo_list": [{"predicate": "出版社", "object_type": "出版社", "subject_type": "书籍", "object": "故宫出版社", "subject": "宜兴紫砂图典"}]}
2、我使用原版训练出来的f1跟您说明的保持一致，可以正常训练，但是使用这份缩减版的数据集每个轮次都出现f1: 0.0, precision: 1.0, recall: 0.0
3、于是我又使用您之前写的keras_bert版本的关系抽取模型，在kg_2019还有我自定义的与语料上都可以正常训练没有出现上述情况

**Comment by TPF2017** [comment]
@cronousbaby 请问找到原因了吗，我遇到相同的情况

**Comment by bojone** [comment]
ema需要足够多的步数才收敛。比如你20w数据，跑了一个epoch刚收敛，那么1w数据就至少需要跑20个epoch。
