### ISSUE TITLE
调用extend_with_piecewise_linear_lr报错

### ISSUE THREAD

**Issue by yesic** [bojone/bert4keras#91]
您好，在运行task_sentence_similarity_lcqmc.py例子的时候使用extend_with_piecewise_linear_lr优化器会报错，显示TypeError: Unexpected keyword argument passed to optimizer: learning_rate。请问是什么原因呢？

**Comment by bojone** [comment]
keras < 2.3.0的话，需要将learning_rate改为lr

不过建议还是升级到keras 2.3.1吧，新特性比较多。

**Comment by yesic** [comment]
好的，谢谢。



---原始邮件---
发件人: "苏剑林(Jianlin Su)"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 下午5:40
收件人: "bojone/bert4keras"<bert4keras@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Janus"<786450794@qq.com&gt;;
主题: Re: [bojone/bert4keras] 调用extend_with_piecewise_linear_lr报错 (#91)




 
keras < 2.3.0的话，需要将learning_rate改为lr
 
不过建议还是升级到keras 2.3.1吧，新特性比较多。
