### ISSUE TITLE
NotFoundError: Key bert/encoder/embedding_hidden_mapping_in/kernel not found in checkpoint

### ISSUE THREAD

**Issue by DonaldHwang** [bojone/bert4keras#92]
创建预训练模型的时候报错，预训练模型使用的是https://github.com/brightmart/albert_zh下的albert_xlarge_zh_183k，请问是什么原因呢，bert4keras是最新版本。

/tensorflow-1.15.0/python3.6/tensorflow_core/python/pywrap_tensorflow_internal.py in get_tensor(self, tensor_str)
    913       from tensorflow.python.util import compat
    914 
--> 915       return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
    916 
    917     __swig_destroy__ = _pywrap_tensorflow_internal.delete_CheckpointReader

NotFoundError: Key bert/encoder/embedding_hidden_mapping_in/kernel not found in checkpoint

**Comment by bojone** [comment]
因为没有认真阅读REAMDE.md （https://github.com/bojone/bert4keras/blob/master/README.md ）。
