### ISSUE TITLE
from bert4keras.bert import load_pretrained_model, set_gelu

### ISSUE THREAD

**Issue by zcuuu** [bojone/bert4keras#93]
from bert4keras.bert import load_pretrained_model, set_gelu
from bert4keras.utils import SimpleTokenizer, load_vocab
您好，这句话报错了。这两个函数应该改成什么呀
谢谢

**Comment by bojone** [comment]
这都是多久之前的代码了...

examples目录下这么多例子，一个都不愿意去看看吗？
