### ISSUE TITLE
shape未指定导致的内存问题

### ISSUE THREAD

**Issue by zurex** [bojone/bert4keras#98]
Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.

这块希望能优化下，训练数据一多 就直接OOM

**Comment by bojone** [comment]
这个不会明显增加内存消耗，而且这是keras默认配置，跟bert4keras没关系。要想不oom，降低batch size即可。

**Comment by zurex** [comment]
关键不是每次都OOM, 有时候能跑通  有时候不行，不能每次复现。
试过batch_size = 1, optimizer=AdaFactor 都不管用，语料调整一下 然后又好了。。。代码没有改过

**Comment by bojone** [comment]
再次强调，这个warning所提示的内容不会导致OOM，不要往这方面找原因。

可能的原因：

1、显存太小，模型太大，等等，导致哪怕batch_size=1都跑不起来；

2、如果你是在tf 2.0环境下用tf.keras，那么需要每个batch都固定长度，也就是说不能一个batch长度为128，下一个batch长度为100之类的，原因暂时没找到，只能按照这个思路缓解了。
