### ISSUE TITLE
task_seq2seq_autotitle出现deprecated的warning该怎么处理？

### ISSUE THREAD

**Issue by guoqingpan** [bojone/bert4keras#99]
Epoch 1/10000
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: generator 'DataGenerator.sample' raised StopIteration
  
/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py:709: UserWarning: An input could not be retrieved. It could be because a worker has died.We do not have any information on the lost sample.
  UserWarning)

**Comment by bojone** [comment]
你传入了generator作为data？如果传入generator，要保证它是无限循环的。

**Comment by guoqingpan** [comment]
problem solved

**Comment by jiayalu123** [comment]
我也遇到了这个问题，输入得数据为CNEWs数据

**Comment by yongzhuo** [comment]
应该是open函数引起的，bert4keras重写并引入了open，导致python自带的open用不了，所以读不到数据

**Comment by bojone** [comment]
> 应该是open函数引起的，bert4keras重写并引入了open，导致python自带的open用不了，所以读不到数据

跟open函数没关系，bert4keras的open只是对自带open的简单封装，不管哪个都是可用的。

**Comment by yongzhuo** [comment]
哦哦，习惯问题。之前用到readlines()，重写的open没有这个函数，又写了try expect跳过了，所以没有读到数据，传入为空报这个Warning
